### ISSUE TITLE
Flank documentation website

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#1029]
**Author the user story for this feature**

As a Flank user, I want to visit a documentation website so I can understand how to best use Flank.

**Is your feature request related to a problem? Please describe.**

Currently the Flank readme is huge and difficult to navigate.

**Describe the solution you'd like**

A GitHub pages website using the pages-gem (Jekyll) https://github.com/github/pages-gem would be helpful in making the documentation easy to use. The readme would then link to the doc website and be much more concise.

**Additional context**

Microsoft just launched a cool GitHub pages/jekyll website, that might be a good inspiration. I'll search for the link.

- https://github.com/microsoft/opensource.microsoft.com
- https://opensource.microsoft.com/

**Comment by pawelpasterz** [comment]
@bootstraponline do we have this solved with https://flank.github.io/flank/ ?

**Comment by bootstraponline** [comment]
> @bootstraponline do we have this solved with https://flank.github.io/flank/ ?

yes!
