### ISSUE TITLE
Post a message to Slack after release flank

### ISSUE THREAD

**Issue by piotradamczyk5** [Flank/flank#1033]
**Author the user story for this feature**

As a Developer, I want to post a message to Slack after each release so I do not need to do it manually 😄 .

**Is your feature request related to a problem? Please describe.**
Now after each release developer must post a message to firebase slack channel with info about new release.

**Describe the solution you'd like**
Add step at the end of release job which will post a message

**Additional context**
The message should look like:
```
Flank <version> has been released:
<release notes>
```

**Comment by bootstraponline** [comment]
I love this idea!

**Comment by Sloox** [comment]
Easy to do but need to ask for permission from the Firebase slack channel @bootstraponline do you perhaps know who to contact? I need to either install a webhook or a bot depending on which way we want to install the auto flank release bot.

**Comment by bootstraponline** [comment]
Maybe Paul? He'd redirect us to the best person to talk with.

The other thought is creating a Flank slack user, adding the user to Slack, and then using a token associated with that user account.

**Comment by Sloox** [comment]
@bootstraponline It appears i can request installation. I will see what happens

**Comment by Sloox** [comment]
An inital release for testing purposes is done : https://github.com/Flank/flank/pull/1058
Will wait for permisisons then close this once i can

**Comment by Sloox** [comment]
Pushed into ranked as we are still waiting. There is a test push to our slack channel once a release occurs. Will be waiting for that.
Slack app link: https://api.slack.com/apps/A019J856KKL/install-on-team?
Send To Slack integration: https://github.com/marketplace/actions/send-message-to-slack

**Comment by Sloox** [comment]
Needs some work as the formatting is incorrect and looks ugly
EG: 
Flank "v20.09.0" is released \n ## v20.09.0 ### Bug Fixes - [#1087](https://github.com/Flank/flank/pull/1087) Fix release action () - [#1080](https://github.com/Flank/flank/pull/1080) Flaky Flank-scripts test ([Sloox](https://github.com/Sloox)) - [#1079](https://github.com/Flank/flank/pull/1079) Fix slack notification in slack ([Sloox](https://github.com/Sloox)) - [#1054](https://github.com/Flank/flank/pull/1054) Firebase refresh fails when test zip file doesn't exist (#1052) ([axelzuziak-gogo](https://github.com/axelzuziak-gogo), [jan-gogo](https://github.com/jan-gogo)) - [#1070](https://github.com/Flank/flank/pull/1070) Avoid fast fail while creating a bucket ([adamfilipow92](https://github.com/adamfilipow92)) - [#1066](https://github.com/Flank/flank/pull/1066) Bad validation of local-result-dir by Doctor ([piotradamczyk5](https://github.com/piotradamczyk5)) ### CI Changes - [#1058](https://github.com/Flank/flank/pull/1058) Post slack message about releases ([Sloox](https://github.com/Sloox))

**Comment by bootstraponline** [comment]
@Sloox I don't think Firebase will ever approve integrations because they are on the Free plan and there's a limit. To successfully deploy this, I expect we'll need to create a Flank bot user account on Firebase and use the token from this user account.

**Comment by Sloox** [comment]
@bootstraponline I have already done as you mentioned. I am waiting for a response as when you add a bot onto firebase you must request its permission to be added. Then for us it is as simple as changing one key.

**Comment by Sloox** [comment]
Alright after further talks with @bootstraponline and the fact that the bot will most likely not be granted permission. 
Will look into getting this to work by using an xoxc token and a flank "bot" user. 
The xoxc token does not work with the github actions and will need to be changed accordingly.
If it requires some scripting it will add it to flank_scripts.
However will first see if there is an easier solution such as where we can simply provide the token and send a message.
