### ISSUE TITLE
Firebase throws error on 250 virtual shards, says limit is now 200

### ISSUE THREAD

**Issue by RainNapper** [Flank/flank#1034]
Version 20.08.01

```
com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
POST https://testing.googleapis.com/v1/projects/test-lab-test-project/testMatrices
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Matrix expands to 250 supported executions which is more than the maximum allowed 200",
    "reason" : "badRequest"
  } ],
  "message" : "Matrix expands to 250 supported executions which is more than the maximum allowed 200",
  "status" : "INVALID_ARGUMENT"
}
        at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:149)
   ```

This is the first run really looked at that was running on >200 shards, so I'm not sure if it is supposed to be 200 or 250 now.
https://github.com/Flank/flank/pull/915 changed it to 250, so I'm guessing it was changed recently on the firebase side.

May abandon this PR:
From firebase:
> Looks like one code location didn't get updated to the new 250 limit. We'll try to have a fix for that in the next release.

**Comment by bootstraponline** [comment]
https://firebase-community.slack.com/archives/C1MTSQ5QT/p1597951056010300?thread_ts=1597950018.009700&cid=C1MTSQ5QT

**Comment by bootstraponline** [comment]
issue should be resolved by FTL now, they're considering reworking the sharding limit.

https://firebase-community.slack.com/archives/C72V6UW8M/p1597979321010300?thread_ts=1597950801.008900&cid=C72V6UW8M
