### ISSUE TITLE
Update fladle to latest stable version of flank

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#1045]
**Author the user story for this feature**

As a Fladle user, I want to use the latest version of Flank so I can run tests with confidence in the outcome.

**Upstream issue**

https://github.com/runningcode/fladle/issues/163

**Additional context**

Fladle currently uses a Flank version with the outcome bug. 
https://firebase-community.slack.com/archives/C72V6UW8M/p1598277599029200

**Comment by piotradamczyk5** [comment]
[PR](https://github.com/runningcode/fladle/pull/164) created in Fladle
