### ISSUE TITLE
firebase refresh fails when test zip file doesn't exist

### ISSUE THREAD

**Issue by DocX** [Flank/flank#1052]
**Describe the bug**
Running `flank firebase refresh` for ios project fails when the `test` zip file does not exist, while it does not use it.

We run the tests in async mode in our CI setup, and then we run the refresh later from another machine. If it is not necessary we don't want to be moving the test zip file just for the refresh to run.

**To Reproduce**

Flank version: v20.08.2

1. Build app and run `flank firebase test ios run --async`
2. Store `matrix_ids.json`
3. On clean workspace (another machine) restore the `matrix_ids.json` and run 'flank firebase refresh'
2. See error `'/home/runner/_work/ios/ios/UITests-Build.zip' not found (UITests-Build.zip)`

**Expected behavior**

We expect not to look for the zip file and run the refresh.

**Details (please complete the following information):**
```
version: v20.08.2
revision: 5f9a81d148ae89a84e5c12410eef75ea9abbf698
```

**Additional info**

When we "fake" the zip file just by creating empty file, the refresh run is ok - indicating that the zip file is not even used at all during the refresh command.

**Comment by bootstraponline** [comment]
This is a cool use case! Agreed this is a bug. I've added this to the ranked column. You can see the columns by installing Zenhub. 
https://www.zenhub.com/extension
