### ISSUE TITLE
Investigate Flank commands

### ISSUE THREAD

**Issue by adamfilipow92** [Flank/flank#1060]
**Author the user story for this feature**

As a user, I want to be informed when I use sets of commands that can be mutually exclusive. 

**Is your feature request related to a problem? Please describe.**

When I working about issue https://github.com/Flank/flank/issues/1057 I saw we can have potential more conflicts on commands or unexpected/not clear behavior.

**Describe the solution you'd like**

I think we can investigate commands and add validation or document potential conflicts.

This only my small proposal, please team tell me what do you think?
@bootstraponline  @jan-gogo @pawelpasterz @piotradamczyk5 @Sloox 
Thanks!

**Comment by bootstraponline** [comment]
I love this idea!

**Comment by pawelpasterz** [comment]
Great idea, I think that should also be processed together with reviewing commands documentation
