### ISSUE TITLE
Run ios tests on Linux.

### ISSUE THREAD

**Issue by adamfilipow92** [Flank/flank#1069]
**Describe the bug**
> A clear and concise description of what the bug is.

Originally reported [here](https://firebase-community.slack.com/archives/C72V6UW8M/p1598878883002500)

**To Reproduce**
> Steps to reproduce the behavior:

1. Run any ios tests on Linux
2. See error

```

RunTests
  Uploading MyTests.zip ..
Found xctest: /home/circleci/xcuitest/Build/Products/Debug-iphoneos/UITests-Runner.app/PlugIns/UITests.xctest
isMacOS = false (linux)
Unable to find resource: binaries/nm

```

**Expected behavior**
> A clear and concise description of what you expected to happen.

Flank shouldn't fail

**Details (please complete the following information):**
> Have you tested on the latest Flank snapshot?
>
> Post the output of ` flank --version`.

Version: v20.08.4

**Comment by bootstraponline** [comment]
let's add a test to ensure this doesn't break in the future.

maybe we can run an iOS test on a Linux GitHub action as part of the integration testing ticket.

#1072
