### ISSUE TITLE
release 20.08.4 is not working with bitrise workflow

### ISSUE THREAD

**Issue by andreschab90** [Flank/flank#1073]
**Describe the bug**
bitrise flank step not usable with latest release

**To Reproduce**
add bitrise workflow `Flank` and use `latest` as version

`version: v20.08.4
revision: 0b328fa775ebc69980b765b35a654089a6235d10
Failed to make bucket for testing
Cause: Sorry, that name is not available. Please try a different one.
Flank exited with status code `1`: A general failure occurred. Possible causes include: a filename that does not exist or an HTTP/network error.`

**Expected behavior**
tests get executed

**Details (please complete the following information):**
> Have you tested on the latest Flank snapshot? no
>
> Post the output of ` flank --version`. 0b328fa775ebc69980b765b35a654089a6235d10

**Additional context**
> Add any other context about the problem here.

**Comment by adamfilipow92** [comment]
Thanks for the feedback, this issue is related to this pr: https://github.com/Flank/flank/pull/1070 we have merged it to the master. We release a new version of flank with this fix soon.

**Comment by adamfilipow92** [comment]
We have released v20.09.0 that contains fix this issue. https://github.com/Flank/flank/pull/1070
Thanks for your patience!
