### ISSUE TITLE
Testing GitHub Action

### ISSUE THREAD

**Issue by adamfilipow92** [Flank/flank#1081]
**Author the user story for this feature**

As a flank developer, I want to be able to test GitHub actions so I can always deliver a working GitHub action in a shorter time and without testing it on "production"

**Is your feature request related to a problem? Please describe.**
Actions are hard to test, broken release actions can block our flank releases. 

**Describe the solution you'd like**
I think we can research how to test actions

I found this: https://github.com/nektos/act probably with this tool we can test actions locally.

WDYT?
@bootstraponline @jan-gogo @pawelpasterz @piotradamczyk5 @Sloox @axelzuziak-gogo 
Thanks for your feedback!

**Comment by bootstraponline** [comment]
this is great!

**Comment by Sloox** [comment]
After some research into ACT,
It appears it has some elementary support for running the actions locally.
Most notable it does not support:
windows-latest, windows-2019, macos-latest, macos-10.15.

It also requires manual setup of Secrets. 

Running the default setup also does not pick up all our acts as they arent supported. 
There is the possibility to download a different runner to attempt a retest but it is 18 gigabytes and it is not guaranteed to work.

I would recommend its not well supported enough to run our full set of github actions.

But regardless there are not many up to date alternatives.

However according to documentation here is the way to test the github workflows based on their examples:
https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#testing-out-your-action-in-a-workflow
