### ISSUE TITLE
Snapshot not updating as expected

### ISSUE THREAD

**Issue by MatthewTPage** [Flank/flank#1085]
The [readme says](https://github.com/Flank/flank/blob/master/README.md#ci-integration) that the snapshot should be published after every commit.

Looks like [the snapshot was last updated 6 days ago](https://github.com/Flank/flank/releases/tag/flank_snapshot), but there have been [several commits since then](https://github.com/Flank/flank/commits/master).

Did the snapshot start getting published in a different way? Or is the snapshot publishing flow broken?

**Comment by adamfilipow92** [comment]
Hello, thanks for your feedback.  Our release action is broken and we working on a fix.

**Comment by adamfilipow92** [comment]
Hello, snapshots and release processes working now. 
https://github.com/Flank/flank/releases
We have released v20.09.0
