### ISSUE TITLE
GitHub action to validate is any user is assigned to pull request

### ISSUE THREAD

**Issue by adamfilipow92** [Flank/flank#1092]
**Author the user story for this feature**

As a pull request author, I want to be informed when I forgot to assign my self to pull request so I can avoid empty author on release notes.

**Is your feature request related to a problem? Please describe.**

I forgot to assign myself to this pr: https://github.com/Flank/flank/pull/1087this cause no author assigned in release notes,

```

- [#1087](https://github.com/Flank/flank/pull/1087) Fix release action ()

```
https://github.com/Flank/flank/pull/1089

**Describe the solution you'd like**
Action should fail when no one is assigned to pull requests.

**Describe alternatives you've considered**

The alternative is assign the author of the first commit in pull request.

**Comment by Sloox** [comment]
@adamfilipow92 I saw this github action. It might not check exactly but it can be triggered first and will do all the work automatically. 
https://github.com/marketplace/actions/auto-assign-action

**Comment by bootstraponline** [comment]
Maybe we should create a github action that copies the label, estimation, and asignees from the issue referenced in the pull request to the pull request itself. This would involve using the ZenHub API.

- https://github.com/ZenHubIO/API
