### ISSUE TITLE
Not able to run a test at the beginning using test-targets-always-run

### ISSUE THREAD

**Issue by khannanidhi** [Flank/flank#1106]
**Describe the bug**
> Not able to run a test case as setup before all other test cases using test-targets-always-run flag in the Flank

**To Reproduce**
> Add a test case in test-targets-always-run flag in Flank
> Add a package of test cases in test-targets
> Run the test on Firebase using Flank

**Expected behavior**
> Set up test case should be executed in beginning and then the test cases in packages mentioned in test target

> Have you tested on the latest Flank snapshot?
>No

> Post the output of ` flank --version`.
version: v20.07.0
revision: 02bca2797b2d6c1ce4bba95a12428d5a49cc8f63

**Additional context**
> Add any other context about the problem here.

**Comment by bootstraponline** [comment]
@khannanidhi Is this android or iOS? Have you tested on the latest Flank release?

**Comment by pawelpasterz** [comment]
For android, flank is unable to ensure the order -- documentation to be updated
