### ISSUE TITLE
Cucumber tests fails to run in parallel

### ISSUE THREAD

**Issue by anas-baadshah** [Flank/flank#1118]
**Describe the bug**
An issue with running cucumber tests on multiple shards. When initiating the test, `max-test-shards` running a false number of shards and none of them initiating the test. 

Gradle build command:
`:app:assembleAppDebugAndroidTest :app:assembleAppDebug -PrunCucumber`

Running test:
`adb shell am instrument -w -r  -e debug false com.app.test/com.app.test.CucumberRunner`

**To Reproduce**
Create a couple of cucumber tests and try to run it with flank enabling shards and using `max-test-shards` set to -1
Specified 4 tests but 100+ shards getting created.

**Expected behavior**
4 shards need to be created and tests need to run in parallel

**Details (please complete the following information):**

> Have you tested on the latest Flank snapshot?

 Yes

> Post the output of ` flank --version`.

20.09.1

**Additional context**
> Add any other context about the problem here.

**Comment by piotradamczyk5** [comment]
@anas-baadshah 
Could you share your Flank configuration which you use to run these tests?

**Comment by piotradamczyk5** [comment]
Closing, because Cucumber tests do not support sharding. Please check [document](https://github.com/Flank/flank/blob/master/docs/cucumber_support.md) for more info
