### ISSUE TITLE
Integration tests on Windows

### ISSUE THREAD

**Issue by Sloox** [Flank/flank#1134]
As a developer, I want to have integration tests running on Windows workflow so I can guarantee Flank runs across all common operating systems and works as intended.

**Is your feature request related to a problem? Please describe.**
Currently Integration task workflow encounters errors and needs to be fixed.

**Describe the solution you'd like**
Integration tests running on the windows workflow

**Comment by Sloox** [comment]
@bootstraponline @jan-gogo can we confirm that this might not be necessary?

**Comment by bootstraponline** [comment]
@Sloox I think we want to ensure all the integration tests pass on native Windows. This matches the platform support provided by gcloud CLI.

**Comment by Sloox** [comment]
The ticket which has successfully been merged https://github.com/flank/flank/issues/1140 has shown that at a minimum Flank will work with the WSL. The ticket is now blocked by the investigation done into : https://github.com/flank/flank/issues/1172

**Comment by Sloox** [comment]
@piotradamczyk5 or @adamfilipowicz92  is this a duplicate ticket now?

**Comment by adamfilipow92** [comment]
@Sloox I think yes, maybe we should close this ticket.
