### ISSUE TITLE
Improve error message on matrix failures

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#1155]
**Author the user story for this feature**

As a user, I want to know exactly why a matrix failed so I can fix the problem.

**Is your feature request related to a problem? Please describe.**

Flank is not currently printing the detailed failure reason on errors.
```
  Uploading MatrixResultsReport.txt .
  Uploading JUnitReport.xml .
Matrix is INVALID
```

**Describe the solution you'd like**

We should be able to print the detailed failure reason using the final matrix.

> invalid_matrix_details: NO_SIGNATURE

**Additional context**

https://firebase-community.slack.com/archives/C1MTSQ5QT/p1600856356008900?thread_ts=1600855459.008800&cid=C1MTSQ5QT

**Comment by runningcode** [comment]
Thanks!
