### ISSUE TITLE
Allow dumping shards in the same flank call as executing a test suit

### ISSUE THREAD

**Issue by MatthewTPage** [Flank/flank#1160]
**Author the user story for this feature**

As a user, I want to be able to both dump the shards of a test run into a JSON file and execute the test run so I can better debug why a test run failed.

**Is your feature request related to a problem? Please describe.**
So in my situation, Flank is a lot better about identifying if a test matrix failed than my old test management system did, so there seem to be tests in my current suit that crash firebase in such a way where I don't get useful information. If I knew which tests were causing this issue I could just suppress them so I could roll this out to my code base initially, and deal with the bad tests at a later date.

I'll probably solve this problem before this feature were to get implemented, but this is an example of a problem where this could be helpful.

**Describe the solution you'd like**
I'd like to be able to get a shards.json file as part of the flank output when executing a test suit. It's time consuming to call into flank twice and have it calculate the same shards twice, and it could even be possible that it shards things differently between those two test runs.

**Describe alternatives you've considered**
Running flank twice (once to dump shards, once to run the test suit), which isn't something I want to leave in my CI system long term.

**Additional context**
Can't think of anything, but I'm happy to help out with this if we could agree on a way for it to be done.

**Comment by bootstraponline** [comment]
I like the idea of dumping shards as part of a test run.

**Comment by MatthewTPage** [comment]
@bootstraponline do you think it should dump shards every time the tests are run, or should it be behind a flag in the configuration file?

**Comment by bootstraponline** [comment]
I think every time.

**Comment by adamfilipow92** [comment]
We can also upload dump to bucket like ```FullJunitReport```. WDYT?

**Comment by bootstraponline** [comment]
> We can also upload dump to bucket like `FullJunitReport`. WDYT?

agreed, let's upload this file to the bucket
