### ISSUE TITLE
Port bash scripts to Kotlin

### ISSUE THREAD

**Issue by adamfilipow92** [Flank/flank#1178]
**Author the user story for this feature**

As a flank developer, I want to use have Kotlin scripts instead of bash scripts so I can easily write new, understand existing and easily use it on all platforms.

**Is your feature request related to a problem? Please describe.**

We had a problem with port update_flank.sh to windows bat script, moving them to Kotlin should be easiest and more readable. 

**Describe the solution you'd like**
Port bash scripts to kotlin scripts

- [x] ./test_runner/bash/update_flank.sh
- [x] ./test_runner/src/test/kotlin/ftl/fixtures/tmp/gohello/build.sh (this is same as ./test_projects/gohello/build.sh)

- [x] ./flank-scripts/bash/buildFlankScripts.sh

- [x] ./test_runner/src/main/resources/binaries/update.sh

- [x] ./test_projects/ops.sh (many functions)

- [x] ./test_projects/gohello/build.sh (with possibility to change gohello path)
- [x] ./test_projects/android/ops.sh (many functions)
- [x] ./test_projects/android/bash/test_filters.sh. 

- [x] ./test_projects/ios/EarlGreyExample/ops.sh (many functions)
- [x] ./test_projects/ios/EarlGreyExample/build_example.sh
- [x] ./test_projects/ios/EarlGreyExample/universal_framework.sh
- [x] ./test_projects/ios/EarlGreyExample/run_ftl_local.sh
- [x] ./test_projects/ios/EarlGreyExample/build_ftl.sh

- [x] ./firebase_apis/generate_java_client.sh
- [x] ./firebase_apis/update_api_json.sh

**Comment by Sloox** [comment]
Are we going to include all bashScripts?
We could make use of : https://www.kotlinresources.com/library/kscript/
Its already used in the Github action for scripting. Works very well.

**Comment by bootstraponline** [comment]
yeah let's fully move away from Bash in favor of Kotlin. I think this will set the project up for success going forward.

**Comment by piotradamczyk5** [comment]
- [ ] ./test_runner/out/production/resources/binaries/update.sh
- [ ] ./test_runner/bash/update_flank.sh
- [ ] ./test_runner/build_earlgrey_example.sh
- [ ] ./test_runner/build/resources/main/binaries/update.sh
- [ ] ./test_runner/src/test/kotlin/ftl/fixtures/tmp/gohello/build.sh
- [ ] ./test_runner/src/main/resources/binaries/update.sh
- [ ] ./firebase_apis/generate_java_client.sh
- [ ] ./firebase_apis/update_api_json.sh
- [ ] ./test_projects/ops.sh
- [ ] ./test_projects/ios/EarlGreyExample/ops.sh
- [ ] ./test_projects/ios/EarlGreyExample/build_example.sh
- [ ] ./test_projects/ios/EarlGreyExample/universal_framework.sh
- [ ] ./test_projects/ios/EarlGreyExample/run_ftl_local.sh
- [ ] ./test_projects/ios/EarlGreyExample/build_ftl.sh
- [ ] ./test_projects/gohello/build.sh
- [ ] ./test_projects/android/ops.sh
- [ ] ./test_projects/android/bash/test_filters.sh
- [ ] ./test_projects/android/bash/generate_apks.sh
- [ ] ./test_projects/android/bash/generate-multi-modules-apks.sh
- [ ] ./test_projects/android/bash/generate_duplicated_names_apks.sh
- [ ] ./flank-actions/compile.sh
- [ ] ./flank-actions/entrypoint.sh
- [ ] ./flank-scripts/bash/buildFlankScripts.sh
