### ISSUE TITLE
IOS Integration tests on Windows native (Non-wsl)

### ISSUE THREAD

**Issue by Sloox** [Flank/flank#1180]
As a developer i want to be able to run integration tests on IOS for android

**Is your feature request related to a problem? Please describe.**
It would be good to support flank on non-wsl versions of windows by allowing integration tests to run.

**Describe the solution you'd like**
Integration tests work in the same manner as on Linux and Mac

**Describe alternatives you've considered**
Use the WSL2

It may be important to consider the following discussion while investigating this ticket:
https://docs.google.com/presentation/d/1goan9cXpimSJsS3L60WjljnFA_seUyaWb2e-bezm084/edit#slide=id.p3
```
iOS test sharding is based on using the LLVM symbol table dumper tool to discover tests.
On Mac, we use nm and swift-demangle provided by Xcode. Users are expected to have Xcode already installed.
On Linux, we bundle nm and swift-demangle from LLVM and Swift in this repo:
https://github.com/Flank/binaries
For Windows, we'd need to bundle nm.exe and swift-demangle.exe for iOS test sharding to work.
```

**Comment by Sloox** [comment]
Swift has offical support for windows as of Sept/22/2020
https://appleinsider.com/articles/20/09/22/developers-can-now-build-and-run-swift-code-on-windows
Therefore the swift demangler  can be downloaded offically and bundle along with flank.
NM.exe is a little more complicated and requires some investigation.
There is already the https://github.com/SwiftForWindows/SwiftForWindows which includes a nm.exe executable which will be used and tested if it works as intended.

**Comment by Sloox** [comment]
This ticket will include merging of the pull request : https://github.com/Flank/binaries/pull/1

**Comment by pdumicz** [comment]
Needs investigation, still valid

**Comment by Sloox** [comment]
There is a good possibility that IOS integration tests can run on Windows. It however remains to be seen in what capacity.
The best approach would be to actually attempt to fix the issues found for the integration tests on IOS by adressing the following issues:

1. Find a suitable version of NM.exe (possibly Cygwin nm.exe should do the job https://www.cygwin.com/) 
2. Place this nm.exe into the flank/binaries and differentiate it specifically for windows so it can be identified.
3. Update the integration test for IOS (AssumeFalse(isWindows) removal, path updates and fixes & nm.exe replacement for windows in the ~/.flank directory and usage)
4. Fix the issue with linking files (currently flank makes a symbolic link for the nm.exe file that cannot be used. We need an alternative)
5. Fix any leftover bugs

That is a very basic overview of what will be required to most likely fix IOS integration tests on windows.

Specifically there is nothing effectively stopping a windows machine from containing the iOS application binary and running it on gCloud therefore integration tests should be possible.
