### ISSUE TITLE
Document output-style and other features

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#1183]
**Describe the bug**
> A clear and concise description of what the bug is.

Add `output-style` to the yaml examples and the main readme. Verify if there are any other missing options not documented in the YAML.

##### Missing documentation for:
1. `output-style`
2. `additional-apks`
3.  ~~`default-class-test-time`~~

context on slack:
https://firebase-community.slack.com/archives/C72V6UW8M/p1601596477011400

**Comment by pawelpasterz** [comment]
I think we could also add documentation for `additional-apks` within this issue

**Comment by pawelpasterz** [comment]
Updated issue description

**Comment by pawelpasterz** [comment]
Updated with `default-class-test-time`

**Comment by piotradamczyk5** [comment]
I have just updated `default-class-test-time `in PR #1214
