### ISSUE TITLE
Some config options are not printed during test run

### ISSUE THREAD

**Issue by pawelpasterz** [Flank/flank#1185]
There are some configuration options that are not printed with flank run:
1. `disable-results-upload`
2. ~`default-test-time`~
3. `default-class-test-time`
4. (can be more, needs to be verified)

Are those not printed intentionally? 
  - **No**  we should verify the remaining options and add to the printing logic
  - **Yes** then we should decide how to hide them? Even though not printed it is still possible to set them via yml file

**Comment by pawelpasterz** [comment]
@bootstraponline @adamfilipow92 @piotradamczyk5 @axelzuziak-gogo @Sloox @jan-gogo

**Comment by bootstraponline** [comment]
The only option not printed intentionally is environment variables. Everything else should be printed.

**Comment by piotradamczyk5** [comment]
`default-test-time` is printed 😄

**Comment by pawelpasterz** [comment]
> `default-test-time` is printed 😄

removed
