### ISSUE TITLE
Run Cucumber tests if there is not other Instrumented tests included

### ISSUE THREAD

**Issue by piotradamczyk5** [Flank/flank#1189]
**Author the user story for this feature**

As a User, I want to run Cucumber tests, even I do not have another Instrumented tests in my test suite so I can run tests with a Cucumber-only test suite using Flank.

**Is your feature request related to a problem? Please describe.**
For now, Gcloud could run tests even apk contains Cucumber only tests.
Flank fast fail with the message `No tests to run` (disabling fast fail do not fix this situation)

**Describe the solution you'd like**
Provide additional flag ex. `only-cucumber-tests` which indicate that the new Matrix should be created

**Describe alternatives you've considered**
0. Described solution
1. Print a warning message that other tests should be included
2. Always create a matrix and try to run tests even for empty apks
3. Leave it as it is with information about this in FAQ section of Flank

**Additional context**
See PR connected to issue #1118 for more information 

@bootstraponline @jan-gogo @pawelpasterz @adamfilipow92 @Sloox @axelzuziak-gogo 
**WDYT?**

**Comment by bootstraponline** [comment]
@piotradamczyk5  the existing disable sharding flag should allow Flank to run cucumber tests.

**Comment by bootstraponline** [comment]
If the flag is enabled then we should skip the test count check.

**Comment by bootstraponline** [comment]
@piotradamczyk5 as Cucumber is not officially supported by FTL I think we can pause work on this in favor of higher priority tickets. Thanks for the investigation and updating the readme.
