### ISSUE TITLE
Android | Add --test-targets-for-shard

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#1203]
**Author the user story for this feature**

As an Android developer, I want to use --test-targets-for-shard so I can run tests like gcloud.

**Describe the solution**

> --test-targets-for-shard=TEST_TARGETS_FOR_SHARD
>
> Specifies a group of packages, classes, and/or test cases to run in each shard (a group of test cases). The shards are run in parallel on separate devices. You can repeat this flag up to 50 times to specify multiple shards when one or more physical devices are selected, or up to 250 times when no physical devices are selected.
>
> https://cloud.google.com/sdk/gcloud/reference/alpha/firebase/test/android/run#--test-targets-for-shard

**Comment by pawelpasterz** [comment]
Flank has `test-targets-always-run`, as I see it its behavior is the same as `--test-targets-for-shard `, or isn't it?
