### ISSUE TITLE
Block Flank releases on integration tests

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#1213]
**Author the user story for this feature**

As a Flank developer, I want to run integration tests before releases so I can ensure there are no bugs.

**Describe the solution**

As part of the release CI job, make sure we run the integration tests and they pass before a release artifact is produced.

**Describe alternatives considered**

Not running tests as part of release.

**Comment by piotradamczyk5** [comment]
Probably it could be solved with the current integration tests policy (run when 2 or more approves), but we need to check this ( problematic parts is that PR created by bot could not run workflows)
