### ISSUE TITLE
Allow developers to toggle whether or not an empty matrix throws an exception

### ISSUE THREAD

**Issue by chris-mitchell** [Flank/flank#1235]
**Author the user story for this feature**

As a developer, I want to have a toggle so I can control whether or not an empty matrix throws an exception.

**Describe the solution**
We have a scenario where we only run tests in Android modules which have had changes made to them.  One of our modules has `androidTest`'s and produces an APK, but all the tests are `@Ignore`.  This causes us to run into https://github.com/Flank/flank/blob/5783b5de9b8d07e4120cb8a727e6cd88da5f105b/test_runner/src/main/kotlin/ftl/run/platform/RunAndroidTests.kt#L64 in CI. 

**Describe alternatives considered**
Ideally, we wouldn't build an APK for modules which have all of their tests ignored, however (to the best of my knowledge) that is difficult to determine when building.

**Comment by bootstraponline** [comment]
Does FTL work as expected if you comment out this check in Flank? I'd expect FTL to also produce an error message when there are no tests to run. I think we've seen this with cucumber recently.

**Comment by piotradamczyk5** [comment]
> Does FTL work as expected if you comment out this check in Flank? I'd expect FTL to also produce an error message when there are no tests to run. I think we've seen this with cucumber recently.

I think that this is similiar case as in #1189

**Comment by bootstraponline** [comment]
@chris-mitchell This sounds like a feature request for the FTL team.

**Comment by chris-mitchell** [comment]
Thanks for following up on this.  I tried reproducing this via the web console and FTL does report it as a failure.   I'll close the issue. Thanks again!
