### ISSUE TITLE
Bug: flankScripts is failing on windows os

### ISSUE THREAD

**Issue by jan-gogo** [Flank/flank#1237]
**Describe the bug**
The flankScripts are not working on windows OS.
Gives different errors for native windows and WSL
* https://github.com/Flank/flank/runs/1247913256?check_suite_focus=true
* https://github.com/Flank/flank/runs/1247913323?check_suite_focus=true

**To Reproduce**
1. Create a new pull request 
2. See errors like lined above

**Expected behavior**
Both workflows should passes like for `ubuntu` and `macos`.

**Comment by Sloox** [comment]
@jan-gogo It appears that we need to have some discussion around it.
For now what shall we do with the pull requests that will always fail.
Shall we manually merge them?
WDYT?

**Comment by Sloox** [comment]
Thinking about this task may require us to check in the gradle script which OS we running on and run different tasks.
https://mrhaki.blogspot.com/2017/02/gradle-goodness-check-operating-system.html
