### ISSUE TITLE
Update test shard limits

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#1241]
**Author the user story for this feature**

As a Flank user, I want to use as many shards as possible so I can run tests quickly.

**Describe the solution**

> the next FTL release (hopefully will happen mid next week if no other blocking issues arise) should support an increase to --num-uniform-shards=500 on virtual devices (currently 200 max) and a max of 2000 devices used per matrix (also currently 200).
>
> The 2000 devices per matrix is for real+virtual combined. The limit of 50 shards per physical device is unchanged, since using higher values is usually counterproductive for e2e latency and impacts other users.
>
>
> https://firebase-community.slack.com/archives/C72V6UW8M/p1602801368027100?thread_ts=1597950801.008900&cid=C72V6UW8M

**Comment by jan-gogo** [comment]
If this is only about increasing the limit of shard for virtual devices I guess it's a snake.

**Comment by adamfilipow92** [comment]
> If this is only about increasing the limit of shard for virtual devices I guess it's a snake.

Yes, the increased limit is a snake. But here we have a second part about max devices used per matrix. Now we don't have validation of this. Could we implement it on the second ticket or leave it as is.

@bootstraponline

**Comment by pawelpasterz** [comment]
@adamfilipow92 how much work would it be to implement per matrix validation? If it's relatively easy/quick we could.
On the second thought, a separate ticket is straightforward and clear way
