### ISSUE TITLE
Debug mode | Print HTTP requests and responses

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#1254]
**Author the user story for this feature**

As a Flank user, I want to see network traffic so I can debug connectivity problems.

**Describe the solution**

`gcloud` allows printing network information. Flank should print network requests/responses when in debug mode.

Ping pauldavis to find out the environment variable to set for gcloud to print debugging network traffic.

**Comment by pawelpasterz** [comment]
@bootstraponline isn't already implemented?
`flank --debug firebase test android run`

**Comment by bootstraponline** [comment]
I'll check
