### ISSUE TITLE
iOS | finalize GameLoop addition to Flank

### ISSUE THREAD

**Issue by piotradamczyk5** [Flank/flank#1277]
**Author the user story for this feature**

As a iOS developer, I want to test app using game loop option .

**Describe the solution**
Check [tutorial](https://firebase.google.com/docs/test-lab/game-loop) for running game-loop within iOS

Please finish first following issues:
#1196
#1194
#1280
#1276

**Comment by axelzuziak-gogo** [comment]
@Sloox I think we can close this issue?
