### ISSUE TITLE
iOS | create test app for gameloop

### ISSUE THREAD

**Issue by piotradamczyk5** [Flank/flank#1280]
**Author the user story for this feature**

As a Flank developer, I want to have iOS test app for gameloop so I can test gameloop functionality.

**Describe the solution**
Please provide app for testing gameloop.
Some hints are available in [tutorial](https://firebase.google.com/docs/test-lab/game-loop)

**Comment by Sloox** [comment]
@axelzuziak-gogo are you able to pick this up?
