### ISSUE TITLE
Android | Perf metrics included alongisde test results for physical devices

### ISSUE THREAD

**Issue by spinEdamageD** [Flank/flank#1285]
**Author the user story for this feature**

As an Android developer, I would like to be able to obtain perf metrics included with the test results so I can have a more complete result set whenever running tests.

**Describe the solution**

Whenever a test is run on an android physical device, firebase automatically collects some perf metrics, which provide some useful information complementing the test result.

These results are already shown in the firebase console, but ideally we would obtain these results included alongside the actual test results.

The API used to obtain these results is: 
https://firebase.google.com/docs/test-lab/reference/toolresults/rest/v1beta3/projects.histories.executions.steps.perfMetricsSummary/create

**Comment by bootstraponline** [comment]
let's generate a json report for this

**Comment by spinEdamageD** [comment]
Thanks a lot for taking this on very quickly. Just out of curiosity. Will we obtain the exact same JSON that's returned from the API in the results or will there be any additional processing and a different JSON report will be generated?

**Comment by piotradamczyk5** [comment]
> Thanks a lot for taking this on very quickly. Just out of curiosity. Will we obtain the exact same JSON that's returned from the API in the results or will there be any additional processing and a different JSON report will be generated?

Hey @spinEdamageD 
It will be the same JSON as returned from API

**Comment by spinEdamageD** [comment]
> > Thanks a lot for taking this on very quickly. Just out of curiosity. Will we obtain the exact same JSON that's returned from the API in the results or will there be any additional processing and a different JSON report will be generated?
> 
> Hey @spinEdamageD
> It will be the same JSON as returned from API

Oh that's great. Thanks a lot for the confirmation!
