### ISSUE TITLE
Add names to all our documentation 

### ISSUE THREAD

**Issue by Sloox** [Flank/flank#1297]
The documentation has a mix and match of named or only explanations given for fields that can be used for flank.

This applies to both ios, android and common flank.

EG:
```
## The path to a Robo Script JSON file.
  ## The path may be in the local filesystem or in Google Cloud Storage using gs:// notation.
  ## You can guide the Robo test to perform specific actions by recording a Robo Script in Android Studio and then specifying this argument.
  ## Learn more at https://firebase.google.com/docs/test-lab/robo-ux-test#scripting.
  # robo-script: path_to_robo_script
```

Lets add a name for example:

```
  ### Robo-Script
  ## The path to a Robo Script JSON file.
  ## The path may be in the local filesystem or in Google Cloud Storage using gs:// notation.
  ## You can guide the Robo test to perform specific actions by recording a Robo Script in Android Studio and then specifying this argument.
  ## Learn more at https://firebase.google.com/docs/test-lab/robo-ux-test#scripting.
  # robo-script: path_to_robo_script
```

This makes it more readable when actually reading documentation. Getting hit with a wall of text that starts with explanation of a un-named option is bad practise. 
This will apply to all text found in
index.md, flank.yml. It could be elsewhere in the project too and needs to be investigated and fixed.

WDYT?

**Comment by bootstraponline** [comment]
this is awesome @Sloox !
