### ISSUE TITLE
Fix downloading and updating Gcloud CLI

### ISSUE THREAD

**Issue by piotradamczyk5** [Flank/flank#1303]
**Describe the bug**
> A clear and concise description of what the bug is.

Auto job to update GCloud CLI is not reliable anymore, because Google does not publish packages to gcloud storage so often

**To Reproduce**
> Steps to reproduce the behavior:

1. Run the [action](https://github.com/Flank/gcloud_cli/actions?query=workflow%3A%22Update+Google+Cloud+SDK%22)
2. See error

**Expected behavior**
> A clear and concise description of what you expected to happen.

Gcloud CLI should be properly updated each week without any errors

**Additional context**
> Add any other context about the problem here.

Probably we should download SDK from links published [here](https://cloud.google.com/sdk/docs/install)

**Comment by bootstraponline** [comment]
Thanks for catching this! Up to date gcloud CLI sources are important for developing Flank.
