### ISSUE TITLE
ResolveArtifacts is not working on Windows.

### ISSUE THREAD

**Issue by Sloox** [Flank/flank#1308]
**Describe the bug**
ResolveArtifacts gradlew tasks executes `succesfully` but doesnt actually do anything on Windows.

this is a crucial task to get working on flank.

eg:
`gradlew resolveArtifacts`

![image](https://user-images.githubusercontent.com/17873353/98676256-a4465180-235b-11eb-899b-2b5be318b614.png)

but it does not actually succeed as test_artifacts folder is not created or modified.

![image](https://user-images.githubusercontent.com/17873353/98675630-ce4b4400-235a-11eb-98a9-96468d8a737c.png)

take not that also running

`gradlew test --rerun-tasks`

doesnt work either

To get past this manually downloading the https://github.com/Flank/test_artifacts/releases test_artifacts and creating a symlink from
`.\src\test\kotlin\ftl\fixtures\tmp\` **to** `test_artifacts\<unpacked artifacts>`

can be done manually or via 
flankScripts testArtifacts link

**To Reproduce**
>Delete test_artifacts folder on windows.

@Sloox has a working windows machine to test if its taken by someone else than @Sloox

**Comment by adamfilipow92** [comment]
Hey, I tested it today and it's fixed. So please test it on your machine and if all is ok we could close it.

**Comment by Sloox** [comment]
This ticket has been fixed along side another ticket.
Tested and confirmed.

**Comment by Sloox** [comment]
I will add some documentation to clear it up.
