### ISSUE TITLE
Support for subdirectories in results-dir

### ISSUE THREAD

**Issue by julioz** [Flank/flank#1309]
**Author the user story for this feature**

As an engineer, I want to organize results from different flank runs so I can organize and simplify navigation in my Google Cloud Storage bucket.

On our pipelines we run multiple flank setups for different apps and use Fladle for the integration with Gradle.
I have configured each of the fladle blocks with the lines similar to the following:
```
fladle {
  ...
  resultsDir = "${readFlankResultDirectoryName()}/my-app-test-run-results"
}
```
In order to have multiple separate directories under the GCS bucket so that the test result artifacts (`JUnitReport`, `MatrixResults`, `CostReport`) don’t overwrite each other.

**Describe the solution**

Assuming I have 2 flank runs in a single pipeline, what I want to achieve is
```
gs://<bucket-name>/<pipeline-run>/<flank-run-1>/<artifact.txt>
gs://<bucket-name>/<pipeline-run>/<flank-run-2>/<artifact.txt>
```

**Describe alternatives considered**

What I could do as a workaround is to define a namespace to add as part of my bucket directory name.

Right now I still have to do something like

```
gs://<bucket-name>/<pipeline-run-flank-run-1>/<artifact.txt>
gs://<bucket-name>/<pipeline-run-flank-run-2>/<artifact.txt>
```

This is not optimal for dev. experience within my company because engineers have to search for all these directories on the root of my bucket that _happen to be related_. That is why I would rather organize each pipeline run into a single directory with nested directories for each flank run.

**Comment by piotradamczyk5** [comment]
I made similar logic in #1292, so maybe we could generalize it a little bit
