### ISSUE TITLE
[SPIKE] Flank's run flow --  refactor

### ISSUE THREAD

**Issue by pawelpasterz** [Flank/flank#1317]
### Story
As a flank committer, I'd like to be able to add new features easily and in a straightforward way.

### Detailed info/background
Recently lots of new code was added to the master (new features, bug fixes, etc.). Sometimes it's hard to implement something due to strongly coupled code and unclear logic. Because of that, it takes more and more time to implement solutions as well as to make correct reviews. In order to make everyone's life easier, we should put some effort to track down places in flank's code which we can refactor to be clear and readable, yet concise and robust.

### Result
As a result, a new epic with SDD will be created with detailed info on what should be refactored, with guidelines if possible.

**Comment by axelzuziak-gogo** [comment]
@pawelpasterz @jan-gogo could you research it and convert it to Epic?

**Comment by jan-gogo** [comment]
@axelzuziak-gogo I have changed the label to the tiger. We can estimate it as research. In the description is mentioned that the result of this research will be a fully described epic.
