### ISSUE TITLE
Evaluate moving to Sentry from BugSnag

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#1318]
**Author the user story for this feature**

As a Flank developer, I want to understand crashes in Flank so I can fix them.

**Describe the solution**

Evaluate [Sentry](http://sentry.io/) as a BugSnag alternative.

**Comment by adamfilipow92** [comment]
Sentry have java lib with example available [here](https://github.com/getsentry/sentry-java/blob/main/sentry-samples/sentry-samples-console/src/main/java/io/sentry/samples/console/Main.java)
also, we can register Flank on [Sentry for Open Source](https://sentry.io/for/open-source/) maybe we get higher quotes to make flank more awesome 😄 
WDYT?

**Comment by bootstraponline** [comment]
Sentry approved Flank for an open source account! I can add the team once we're ready to work on this

**Comment by adamfilipow92** [comment]
Sentry have java [library](https://sentry.io/for/kotlin/)

## Initialization

1. Bugsnag

```kotlin
Bugsnag(API_KEY)
```

2. Sentry

```kotlin
Sentry.init {
        it.dsn = DNS_URL
    }
```

## Logging errors

1.  Bugsnag

```kotlin
bugsnag?.notify(error)
```

2. Sentry

```kotlin
 Sentry.captureException(error)
```

## Additional data

We can set 

1. release number
2. user
3. tags (here we can put additional information like os version)

Events can be filtered by user, tag, event level. This feature can be helpful when we need to find a specific issue for a specific system. 

We login errors to ```bugsnag``` in 2 places

1. ```executeWithRetry```
2. ```withGlobalExceptionHandling```

I think we can also log: Flank version, os name, and ```run id``` to easier finding crashes for a specific user. We could display this information before Flank version. It could help with finding errors for specific cases.

WDYT?

**Comment by bootstraponline** [comment]
That sounds awesome
