### ISSUE TITLE
Report missing test results

### ISSUE THREAD

**Issue by RainNapper** [Flank/flank#1327]
**Author the user story for this feature**

In CI, I want to have visibility over which tests have no results so I can handle the case appropriately (e.g. as a failure).

**Describe the solution**
This is coming from Android experience, but I imagine it has some overlap with iOS.

In some scenarios, where a matrix times out, or a matrix hits an unrecoverable internal error, firebase will simply not have results for some or all tests assigned to that matrix. Because flank merges output JUnitReports into the final report. However, with missing tests, they are not there, which complicates detection of missing results, as many tests are run on a package basis rather than an explicit list of tests.

**Describe alternatives considered**
 - Outside of flank, we can parse the outputted `android_shards.json` / `ios_shards.json` files using `--dump-shards` to detect missing results. This is certainly doable, but it seems much simpler to do within flank.
 - Since shards aren't necessarily individual test methods, we could also independently resolve which individual test methods should have ran as a reference. This is also likely overly complicated for most users.

**Comment by jan-gogo** [comment]
Converted to https://github.com/Flank/flank/issues/1677
