### ISSUE TITLE
Make Flank releases more automatically

### ISSUE THREAD

**Issue by piotradamczyk5** [Flank/flank#1346]
**Author the user story for this feature**
As a Develop, I want to have more automatic releases so I can make Flank releases faster.

**Describe the solution**
1. Make Flank release at the start of the calendar month automatically(use schedule), but allow to manually run the job to update release notes
2. Push tag automatically after merging release notes PR (use some auto tagger with filters [example](https://github.com/marketplace/actions/github-pr-auto-tagger))

**Comment by pawelpasterz** [comment]
Just for my understanding, why update the release notes must be started manually? If I got your description correctly, the full release flow won't be fully automatic?

**Comment by piotradamczyk5** [comment]
> Just for my understanding, why update the release notes must be started manually? If I got your description correctly, the full release flow won't be fully automatic?

Release flow will be automatically, but you have the option to run it manually :)

**Comment by pawelpasterz** [comment]
> > Just for my understanding, why update the release notes must be started manually? If I got your description correctly, the full release flow won't be fully automatic?
> 
> Release flow will start automatically in each 1st day of month, but you have the option to run it manually :)

Thanks for the explanation, I was confused by description 👍
