### ISSUE TITLE
Publish Flank scripts after each change

### ISSUE THREAD

**Issue by piotradamczyk5** [Flank/flank#1347]
**Author the user story for this feature**

As a Developer, I want to publish a release of `flank-scripts` so I  do not need to build it every time.

**Describe the solution**
1. Publish Flank scripts to Github packages/maven/brew repository
2. Make proper versioning

**Comment by pawelpasterz** [comment]
Does `flank-scripts` should (will?) have the same version convention as flank does?

**Comment by piotradamczyk5** [comment]
> Does `flank-scripts` should (will?) have the same version convention as flank does?

I think that `flank-script` will follow his own naming with pattern  `<new_feature>.<new_option>.<fix>`
