### ISSUE TITLE
Add gameloop integration test for IOS & Android

### ISSUE THREAD

**Issue by Sloox** [Flank/flank#1348]
**Author the user story for this feature**

As a developer I want functional gameloop integration tests running for both IOS & Android.
However more work needs to be done for the integration testing on Flank before this can be achieved.

**Describe the solution**

Integration tests for game loop on IOS and Android is included alongside other integration tests.

#### Definition of done:

1. A test(s) is(are) added in `integration_tests` module `integration` package
1. Test class name must end with `IT` (for instance `MultipleApksIT`) -- gradle test task filters
1. Compare file is added to the resources directory
1. Tests pass :)

**Comment by Sloox** [comment]
@pawelpasterz is this possible after your `Improve integration test` topic is complete?

**Comment by pawelpasterz** [comment]
I would definitely wait until https://github.com/Flank/flank/pull/1316 is merged. We don't need to wait for the whole epic is done

**Comment by pawelpasterz** [comment]
@Sloox 
I've added DoD to the description, let me know if it makes sense to you

**Comment by Sloox** [comment]
@pawelpasterz happy with it 👍
