### ISSUE TITLE
[IT] Comment trigger for full suite integration tests

### ISSUE THREAD

**Issue by pawelpasterz** [Flank/flank#1349]
PR #1316 introduced a new Gradle task launching full suite integration tests `./gradlew integrationTests`. Those are in addition to already implemented IT, not a replacement. Current IT (let's call them sanity IT) do their job as quick check if flank's jar works correctly and nothing unplanned causes flank to crash with a simple run. Sanity ITs are also cheap. 
Given mentioned I think it's fine to run them automatically.

Full suite IT requires several times more devices (both virtual and physical). `flank-open-source` project has a very high quota limit, yet it's not unlimited. With full suite IT running automatically (similar to sanity IT) we could burn daily quota very quickly, as result PR's would be blocked and general work on repo would be difficult, at least until the end of the day.

#### Requirements for trigger (my proposals in parenthesis):
1. GH action should run ONLY full suite ITs (separated flow/gh action?)
1. we can use a similar trigger that was implemented in #1342 (@flank-it-fs)
1. IT results should be presented to the user, there are some possibilities:
    - PR's checklist (might be tough due to missing PR context for issue comment event)
    - update/change PR description
    - add a comment (separate for each trigger invocation)
1. consider the form of presented results: text, a summary table, etc (I think the easiest would be to print gradle build scan URL, similar to ubuntu-workflow)
1. consider a limitation of who can trigger full suite IT
1. instant feedback, we should inform a user about the current status of IT/action. (This can be achieved via reactions), for instance:
    - :eyes: `noticed`- gh action was triggered 
    - :rocket: `IT started` - full suite ITs were started and are in progress
    -  🎉   - all tests finished successfully
    - :-1: - there are some failed tests
1. sanity IT (currently running) should remain
1. Add/update PR's check (need investigations if it is possible)

#### Additional info:
* as mentioned earlier issue comment is missing PR context (it's due to the fact GH considers PRs as normal issues)
* we don't need to implement super fancy flow/gh action from the beginning, Let's start with the easiest implementation that fulfills requirements

**Comment by piotradamczyk5** [comment]
> as mentioned earlier issue comment is missing PR context (it's due to the fact GH considers PRs as normal issues)

This was fixed in #1342

**Comment by jan-gogo** [comment]
I like the detailed description. 
The work on a pull request for this ticket should be started by creating documentation on how this feature exactly will work.
The description of this issue is a good starting point.
