### ISSUE TITLE
[IT] Add workflow for full suite IT

### ISSUE THREAD

**Issue by pawelpasterz** [Flank/flank#1351]
With https://github.com/Flank/flank/pull/1316 new integration tests are introduced. Flank project should have a cron job that will check the current master periodically. 

#### Requirement:
1. job is launched automatically
1. job should listen to `workflow_dispatch` event to enable manual start
1. in case of failure, new issue should be created
1. job run info should be added in a comment:
    1. info about tests themselves
    1. list of commits since the last IT run
1. if the issue is already created, the next IT runs should add a comment to the existing (opened) issue

**Comment by pawelpasterz** [comment]
Here is my proposal:

1. cron for job `0 0 * * *` -  00:00 everyday
1. I think build scan URL will be enough to get all required info about failure reasons.
1. scan URL will be placed inside issue description
1. issue title will contain date + time of run

**Comment by jan-gogo** [comment]
Algorithm for IT job:

1. For a given branch: (In this case a master)
1. Run integration tests and collect results.
1. Get the latest unresolved IT issue or create a new one.
1. Collect a list of merged pull requests from the previous run to the current.
1. Add comment under issue with:
    - link to build scan
    - list of merged pull requests from the previous run to current.

Consider that IT tests issue can be closed only when the last comment contains results where all tests pass. 
After that, IT tests issue automatically could be closed.
