### ISSUE TITLE
Refactor flank-scripts [PROPOSAL]

### ISSUE THREAD

**Issue by jan-gogo** [Flank/flank#1356]
**User story**

As a developer, I want to have well-structured and described flank-scripts commands so I can clearly understand the purpose of each, also maintain and scale the module without a doubt.

**Description of the problem**
1. The packages structure is designed in a semi-random manner, which makes to code harder to scale and may cause additional inconsequences in the future.
1. The CLI that uses thirty part libraries is bounded with domain and occasionally contains logical operations that break SRP and separation of concerns.
1. The command hierarchy is not well structured and described.

**Requirements**
1. According to the separation of concerns principle, the logical part of the code should be separated from others. 
1. The CLI layer that uses third-party libraries (CliKt) should be thin as possible and free of logical operations for increasing code portability.
1. The domain layer should be designed a flat as possible manner. Each feature should be exposed as a single pure function separated from others, that operates on a utility code.
1. Only non-domain code should be reusable so it's important to design a common package carefully.
1. Each command must have a description that explains the purpose of the command and the possible result of the call.

**Proposed solution**

There are 3 important layers (packages) for `flank-scripts` module:
1. `cli`. Thin non-logical layer, a glue between program arguments and domain logic. Also specifies command-line documentation.
2. `ops`. The domain layer contains logical operations. Should be clean, easy to understand, and straightforward.
3. `util`. A non-domain reusable layer that contains utility code. The API should be simple and declarative.

Working steps:
1. Separate logical operations from CliKt commands.
1. Design a new structure for commands.
1. Group CliKt commands in `cli` package and fix the structure 
1. Fix descriptions of commands.
1. Separate common layer
1. Refactor common layer API
1. Group all domain code in `ops` package (ops as shorthand for operations) 
1. Refactor and restructure `ops` package
1. Use a standardized naming convention for commands (camel-case preferred as easier to write).

**Comment by piotradamczyk5** [comment]
> The packages structure is designed in a semi-random manner, which makes to code harder to scale and may cause additional inconsequences in the future.

Now they are organized by feature not semi-random.
As you mention 

> the logical part of the code should be separated from others

so it is good that each feature has a separate package.

I think that we should discuss it first, before making this kind of task

**Comment by jan-gogo** [comment]
> I think that we should discuss it first, before making this kind of task

This is a proposal, feel free to give any suggestion.

**Comment by jan-gogo** [comment]
> Now they are organized by feature not semi-random.

So tell me which one of the following:
```
ci
dependencies
exceptions
github
pullrequest
release
shell
testartifacts
utils
```
can be classified as a feature in the sense of meaning?

**Comment by piotradamczyk5** [comment]
> > Now they are organized by feature not semi-random.
> 
> So tell me which one of the following:
> 
> ```
> ci
> dependencies
> exceptions
> github
> pullrequest
> release
> shell
> testartifacts
> utils
> ```
> 
> can be classified as a feature in the sense of meaning?

According to [Readme](https://github.com/Flank/flank/blob/master/flank-scripts/README.md) features are 
```
ci
dependencies
pullrequest
release
shell
testartifacts
```

each package represents set of commands
```
exceptions
github
utils
```
should be reorganized to common package

if think that we could follow your proposition, but keep feature packages
```
<feature1>
    cli
    ops
<feature2>
    cli
    ops
...
common
    cli
    ops
```

WDYT?

**Comment by jan-gogo** [comment]
@piotradamczyk5 
The essence of flank-scripts are functions that are called by commands. So my proposition was to group them in `ops` package in the following manner:
(`ops` - `operations` IMO fits well for domain of flank-scripts)

```
cli\
    ...
ops\
    ci\
        GenerateReleaseNotes.kt
        NextReleaseTag.kt
    git\
        LinkGitHooks.kt
    dependency\
        UpdateDependencies.kt
    firebase\
        GenerateJavaClient.kt
        UpdateApiJson.kt
        CheckForSDKUpdate.kt
    ios\
        InstallXcPretty.kt
        BuildEarlGreyExample.kt
    testartifacts\
        ...
    ...
util\
    git\
        ...
    github\
        ...
    zenhub\
        ...
    shell\
        ...
    ...
```
As in the example above:
* The packages structure inside `ops` should be flat.
* The packages names in `ops` should be simple and generic [ci, git, firebase...]
* Each kt file in the `ops` package should contain only one public function which will be the source-level command. Besides that, the file can contain many domain-related private functions.
* The functions in `ops` shouldn't be aware of the CLI library.
* The `cli` layer should be thin as possible and separated from others. It is not required to keep package convention from `ops`, this is a boring `presentation` layer, should be easily replaceable, that's why it should be thin. Any possible operation for `run` method of `CliktCommand` is running one of the public functions from `ops` package with proper arguments.
* The `util` should contain all reusable non-domain stuff necessary for the `ops` package.

With this convention, we can easily navigate through the essence of flank-scripts, which is inside the `ops` package.

I do not recommend the repository pattern for all scripts, only for those which require different implementations for different platforms, otherwise, that layer is useless and `ops` can call `util` directly.

CLI code should be kept separated from the domain because we can have another implementation for the presentation layer in the separated java module. For example with Gradle tasks instead of Clikt.

**Comment by jan-gogo** [comment]
@axelzuziak-gogo @pawelpasterz @adamfilipow92 @Sloox WDYF?

**Comment by piotradamczyk5** [comment]
Hey @jan-gogo 
Great plan, I agree with almost all of the proposed changes, however, I really think that we should package by feature instead of packaging by layers.
With packaging by features, you have a clear overview about the files which belong to feature, code is simpler, files are independent, changes are mostly made in a single package, moving/deleting feature is done quicker.

Please take a look at some articles about them:
- https://phauer.com/2020/package-by-feature/
- https://proandroiddev.com/structural-and-navigation-anti-patterns-in-modularized-android-applications-a7d667e35cd6
- https://proandroiddev.com/package-by-type-by-layer-by-feature-vs-package-by-layered-feature-e59921a4dffa
- http://www.javapractices.com/topic/TopicAction.do?Id=205

**Comment by jan-gogo** [comment]
I know arguments about keeping feature related layers together but IMO for our scripts it is not convenient.
We shouldn't litter clear domain package by keeping it together with nasty object-oriented CliKt API. Presentation code is not interesting because is simple as stupid, there is no logic there so we shouldn't see it often. It's just a wrapper for kotlin functions kind of bridge from the command line to the application it's a noise from a feature perspective.
Additionally. Think about whole `ops` as a dependency for `cli`, and `util` as a dependency for `ops` [cli->ops->util]. This could be even the separated modules.

**Comment by piotradamczyk5** [comment]
Ok let's go with your proposition 👍 
Great job

**Comment by axelzuziak-gogo** [comment]
Converted to #1406
