### ISSUE TITLE
Optimize slack release notification

### ISSUE THREAD

**Issue by Sloox** [Flank/flank#1358]
**Author the user story for this feature**

As a developer I wish to optimize the GitHub action that Flank is currently using to send a release message to flank.
We can either swop to a better well documented solution or attempt to optimize the current solution so it works faster.
**Describe the solution**
We can either.
1. Have a precompiled binary or docker image(needs to be external and requires docker account) so the commands don't need to be run on each release (Its not the end of the world that they run on each release as the releases are so infrequent)
2. Adhere to better documented procedures on how to create GitHub actions : https://docs.github.com/en/free-pro-team@latest/actions/creating-actions

**Describe alternatives considered**
We can follow the current procedure with minor optimizations such as removal of dependencies and automation which shan't be too difficult.

**Comment by pawelpasterz** [comment]
@Sloox 
https://github.com/features/packages

**Comment by Sloox** [comment]
Will also fix teh issues with the slack release notification

**Comment by axelzuziak-gogo** [comment]
@Sloox Can you add a SSD document here?

**Comment by axelzuziak-gogo** [comment]
Closing as it's no longer valid. See: #1595
