### ISSUE TITLE
Always upload matrix_ids.json to GCS

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#1381]
**Author the user story for this feature**

As a user, I want to know all the matrix ids so I can investigate the test results.

**Describe the solution**

Always upload `matrix_ids.json` to gcs. Currently this file is generated and saved locally in `results/matrix_ids.json`

**Comment by jan-gogo** [comment]
Implementation propsal:

1. (Optional) Extract `fun MatrixMap.prettyPrint()` from `fun updateMatrixFile()`
1. Add `fun uploadMatricesId(...)` to `GcStorage`
1. Call `uploadMatricesId(...)` from `ReportManager.generate(...)`

Consider a source for `matrices_ids` data. This can be obtained from:
- `matrices_ids.json` which is generated before `ReportManager.generate` call.
- `MatrixMap` which is passed to `ReportManager.generate` and can be pretty-printed.

**Comment by Sloox** [comment]
Thanks will get on it asap.
