### ISSUE TITLE
fail-fast option is not compatible with gcloud

### ISSUE THREAD

**Issue by pawelpasterz** [Flank/flank#1390]
**Describe the bug**
> A clear and concise description of what the bug is.

Recently introduced `fail-fast` (if present) makes flank config incompatible with gcloud.
Although this flag is possible to use via API, it is not supported by gcloud sdk yet
https://cloud.google.com/sdk/gcloud/reference/alpha/firebase/test/android/run
If present in the config, gcloud terminates test run with an error.

**To Reproduce**
> Steps to reproduce the behavior:

1. Run `flank firebase test android run -c=flank.yml` where `flank.yml` is:
    ```
    gcloud:
      app: [path to app apk]
      test: [path to test apk]
      fail-fast: true (or false, doesn't matter)
    ```
1. Flank proceeds normally
1. Run `gcloud alpha firebase test android run flank.yml:gcloud` (same config)
1. `gcloud` terminates with the error
```
ERROR: (gcloud.alpha.firebase.test.android.run) [fail-fast] is not a valid argument name for: gcloud test run
```
![Screenshot 2020-12-09 at 11 12 59](https://user-images.githubusercontent.com/32893017/101616334-89750480-3a0f-11eb-84f1-7020dd2044a9.png)

**Expected behavior**
> A clear and concise description of what you expected to happen.

Flank config should be always compatible with gcloud.

**Details (please complete the following information):**
> Have you tested on the latest Flank snapshot?
>
> Post the output of ` flank --version`.

```
version: local_snapshot
revision: 2d2982474e9d38ee39639ed7282b84fb5e33ce01
```

**Comment by bootstraponline** [comment]
I think for alpha features that are coming soon to gcloud CLI, we can just wait for Google to update the CLI. I asked on the Slack channel when the release date is for this feature.
