### ISSUE TITLE
[EPIC] Refactor Flank Scripts

### ISSUE THREAD

**Issue by pawelpasterz** [Flank/flank#1406]
# Refactor Flank Scripts

As a developer, I want to have well-structured and described flank-scripts commands so I can clearly understand the purpose of each, also maintain and scale the module without a doubt.

# References

* https://github.com/Flank/flank/issues/1356

# Motivation

Currently is quite hard to overview whole flank-scripts because the layers are mixed together and some of the features are aware of others. As result, the code is harder to understand, scale, and improve. Any new function can bring more tech-debt. Refactor could solve this problem. Also, the command hierarchy contains some legacy concepts that are confusing and should be redesigned.

# Goals

* The presentation layer is tin and not contains any logical operations.
* The features are independent of each other.
* The commands hierarchy has no more than one nestings.
* Each command has a description that helps understand the purpose and results.

# Design

This is the proposition of the new package hierarchy. The final design should be prepared in the scope of issue #1542
```
cli\
    ...
ops\
    ci\
        GenerateReleaseNotes.kt
        NextReleaseTag.kt
    git\
        LinkGitHooks.kt
    dependency\
        UpdateDependencies.kt
    firebase\
        GenerateJavaClient.kt
        UpdateApiJson.kt
        CheckForSDKUpdate.kt
    ios\
        InstallXcPretty.kt
        BuildEarlGreyExample.kt
    testartifacts\
        ...
    ...
util\
    git\
        ...
    github\
        ...
    zenhub\
        ...
    shell\
        ...
    ...
```

# API

Wouldn't change so much, only the namings will change. Preparing a new design for an API is a part of issue #1545.
  
# Results

The flank-scripts module is fully reorganized but the whole functionality is untouched. Additionally renaming the commands will bring some small changes in workflow files and markdown documents.

# Testing

Everything should work the same as before. The most important flank-scripts commands are used by CI so it's important to check manually only the others.

# Working steps:
1. ~Separate logical operations from CliKt commands.~
1. ~Group CliKt commands in `cli` package and fix the structure~
1. ~Separate common layer~
1. ~Refactor common layer API~
1. ~Group all domain code in `ops` package (ops as shorthand for operations)~
1. ~Use a standardized naming convention for commands (camel-case preferred as easier to write).~
1. Refactor and restructure `ops` package
1. Design a new structure for commands.
1. Fix descriptions of commands.

**Comment by piotradamczyk5** [comment]
Is this task is epic for refactor?

**Comment by pawelpasterz** [comment]
> Is this task is epic for refactor?

Correct
