### ISSUE TITLE
Create Github Action for running Flank

### ISSUE THREAD

**Issue by piotradamczyk5** [Flank/flank#1419]
**Author the user story for this feature**
As a User, I want to run flank using Github action so I could integrate easier this great tool.

**Describe the solution**
Create Github action and publish it to the marketplace

**Comment by jan-gogo** [comment]
We should investigate the best way for creating github action and prepare SDD.

**Comment by piotradamczyk5** [comment]
Options:
[Creating a Docker container action](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action)
[Creating a JavaScript action](https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action)
[Creating a composite run steps action](https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action)
