### ISSUE TITLE
Autodetect new features in gcloud SDK

### ISSUE THREAD

**Issue by pawelpasterz** [Flank/flank#1422]
**Author the user story for this feature**

As a flank committer, I want to know when the new gcloud SDK feature is introduced so I can ensure the flank is fully compatible.

**Describe the solution**
An issue should be created when gcloud SDK introduces a new option (command, flag, etc) that is not implemented in the flank.

Possible solutions:
1. The easiest approach would be just to check if a new version of SDK was released and notify (via issue)
2. Manual checking may be time-consuming so ideally, we would have more detailed info. We can achieve this by tracking the release notes https://cloud.google.com/sdk/docs/release-notes#firebase_test_lab and create a new issue with info only related to test lab
3. The best would be to have very specific info on what was changed, missing etc. This approach needs to be investigating.

Once the solution is picked, provide detailed info in the documentation.

**Comment by bootstraponline** [comment]
#1200 🙂

**Comment by pawelpasterz** [comment]
> #1200 🙂

?
1200 is about auto-updating API client only. That one is about SDK

**Comment by bootstraponline** [comment]
ah, makes sense! they looked like two duplicate issues to me
