### ISSUE TITLE
Update picocli to latest version

### ISSUE THREAD

**Issue by piotradamczyk5** [Flank/flank#1452]
**Author the user story for this feature**

As a Developer, I want to use the latest version of picocli so I can be up to date with this tool.

**Describe the solution**
[picocli](https://github.com/remkop/picocli) makes new release which has breaking API changes please update it in Flank

**Comment by piotradamczyk5** [comment]
If this task requires a lot of work, think about rewriting CLI reader to use Clikt

**Comment by bootstraponline** [comment]
Clikt looks awesome
