### ISSUE TITLE
Move shards.json to results directory

### ISSUE THREAD

**Issue by adamfilipow92** [Flank/flank#1475]
**Describe the bug**
> A clear and concise description of what the bug is.

Currently, flank always saves shards file in the current directory. This behavior can cause overriding this file when user run flank multiple times at the same time.

**Expected behavior**
> A clear and concise description of what you expected to happen. 

When we run tests we should save shards file to result directory. This behavior can cause overriding this file when user run flank multiple times at the same time.

**Comment by bootstraponline** [comment]
Makes sense. Thanks for catching this.

**Comment by adamfilipow92** [comment]
# #1475 Save shards.json in the results directory

> Summary of the proposed change

Change save the location of ```shard.json``` file.

# Motivation

> What problem is this project solving?

Currently, Flank always saves shards file in the current directory. This behavior can cause overriding this file when the user runs Flank multiple times at the same time.

# Goals

> Identify success metrics and measurable goals.

The main goal is avoiding inconsistency between ```shard.json``` and results in case when Flank is executed multiple times at the same time.

# Design

> Explain and diagram the technical design
>
> Identify risks and edge cases

Currently in ```dumpShards``` we using a ```ANDROID_SHARD_FILE``` and ```IOS_SHARD_FILE```. This is the reason why Flank saves dump to execution directory.

```kotlin
private fun AndroidMatrixTestShards.saveShards(obfuscateOutput: Boolean) = saveShardChunks(
    shardFilePath =  ANDROID_SHARD_FILE,
    shards = this,
    size = size,
    obfuscatedOutput = obfuscateOutput
)

fun IosArgs.dumpShards(
    shardFilePath: String = IOS_SHARD_FILE,
) 

```

The dump shard file should be saved to the current execution result directory.

# API

> What will the proposed API look like?

## Android

```kotlin

private fun AndroidMatrixTestShards.saveShards(obfuscateOutput: Boolean) = saveShardChunks(
    shardFilePath =  Paths.get(path_to_result_dir,ANDROID_SHARD_FILE).toString(),toString(),
    shards = this,
    size = size,
    obfuscatedOutput = obfuscateOutput
)

```

Flank should also check if the results directory currently exists and create if not.

## iOS

Behavior should be similar to ```android```

```kotlin
private fun IosArgs.dumpShardsIfXcTest() = takeIf { isXcTest }?.let {
   createSHards().saveShardChunks(
        shardFilePath =  Paths.get(path_to_result_dir,IOS_SHARD_FILE).
        shards = rawShards,
        size = size,
        obfuscatedOutput = obfuscateDumpShards
    )
    if (disableResultsUpload.not())
        GcStorage.upload(IOS_SHARD_FILE, resultsBucket, resultsDir)
}
```
  
# Results

> What was the outcome of the ticket?

Flank was saving ```shards``` file to the current directory instead of the current execution result directory. This can cause inconsistency when Flank was used multiple at the same time.

# Dependencies

> What is the ticket blocked on?

> What will be impacted by the ticket?

The ticket is not blocked.

Ticket improve quality and reduce data inconsistency.

# Testing

> How will the project be tested?

Dump shards file should be saved to result in directory instead of execution directory for android and ios.
