### ISSUE TITLE
[FLADLE] Lazily evaluate file paths for debug and instrumentation APKs

### ISSUE THREAD

**Issue by pawelpasterz** [Flank/flank#1486]
https://github.com/runningcode/fladle/issues/139

**Comment by axelzuziak-gogo** [comment]
@adamfilipow92 @jan-gogo can you provide SDD for this ticket?

**Comment by adamfilipow92** [comment]
I have spoken with Flade author and I got the information: ``` The reason path is kept as a string as opposed to a RegularFileProperty is to allow for wildcard characters and not yet existent files. ```` So current implementation is fine. I think we can close this ticket.

**Comment by axelzuziak-gogo** [comment]
Ok, closing it.
