### ISSUE TITLE
[Mixpanel] Prepare basic dashboards and reports 

### ISSUE THREAD

**Issue by adamfilipow92** [Flank/flank#1502]
**Author the user story for this feature**

After investigation and compare mixpanel and segment we decide to use mixpanel. Here is a doc about our investigation: [analytics_comparsion](docs/analytics_comparsion.md). Mixpanel allows defining custom dashboards and reports with the most important data for the team.

**Describe the solution**

Prepare dashboards/reports with:

1. types 
1. platform (ios/android)
1. ```disabled-sharding``` 
1. ```max-test-shards```

Feel free to extend this list
@bootstraponline  @piotradamczyk5 @jan-gogo @pawelpasterz @Sloox @ax\

**Comment by piotradamczyk5** [comment]
Dashboard and report available on https://mixpanel.com/s/1sQL6a
