### ISSUE TITLE
Ubuntu Java warnings

### ISSUE THREAD

**Issue by Sloox** [Flank/flank#1520]
**Describe the bug**

A warning appears during compilation.
If we are constantly updating our libraries to the latest it will most likely become an an issue.

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.junit.contrib.java.lang.system.EnvironmentVariables (file:/home/runner/.gradle/caches/modules-2/files-2.1/com.github.stefanbirkner/system-rules/1.19.0/d541c9a1cff0dda32e2436c74562e2e4aa6c88cd/system-rules-1.19.0.jar) to field java.util.Collections$UnmodifiableMap.m
WARNING: Please consider reporting this to the maintainers of org.junit.contrib.java.lang.system.EnvironmentVariables
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

See the following build https://github.com/Flank/flank/pull/1448/checks?check_run_id=1736270298

**Comment by pawelpasterz** [comment]
I think this is related with JDK version you are using. Ubuntu 20.04 has java 11 as the default one. WIth jdk 11 there were some changes introduced with reflection http://openjdk.java.net/jeps/181

I guess if you change jdk to 8 there will be no warnings. 

BTW, `mockk` is also using reflection, a lot... I use JDK 15 on daily basis and get:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.mockk.proxy.jvm.advice.MethodCall (file:/Users/gogo/.gradle/caches/modules-2/files-2.1/io.mockk/mockk-agent-jvm/1.10.5/a01228a3cc5146c4464b2940264c35e367c42d6b/mockk-agent-jvm-1.10.5.jar) to method java.time.LocalDate.create(int,int,int)
WARNING: Please consider reporting this to the maintainers of io.mockk.proxy.jvm.advice.MethodCall
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

They (`mockk` maintainers) tried recently to abandon jdk 8 and compile source code with jdk 9 (I think). But, well... :)

**Comment by jan-gogo** [comment]
@pawelpasterz @Sloox So for this issue we should investigate which JDKs we can use without those warnings? Correct me if I am wrong. I am trying to assume what should be done in the scope of this issue.

**Comment by pawelpasterz** [comment]
@jan-gogo any JDK 11+ will give warnings, we can switch java version to 8 in gh action to get rid of those warnings
