### ISSUE TITLE
Re-introduce integration tests for windows

### ISSUE THREAD

**Issue by Sloox** [Flank/flank#1527]
**Author the user story for this feature**

I would like to ensure Windows as a platform is supported.
Integration tests need to run successfully on a windows platform

**Describe the solution**
@flank-it should run a successful windows instance.

**Comment by pawelpasterz** [comment]
Unfortunately, tests are failing after the merge https://github.com/Flank/flank/actions/runs/514350557

**Comment by Sloox** [comment]
@pawelpasterz will look into it

**Comment by Sloox** [comment]
Opening due to bug for windows and requirement for PRs to have a valid ticket assigned.
