### ISSUE TITLE
Explore test-target-for-shards with extra features

### ISSUE THREAD

**Issue by Sloox** [Flank/flank#1532]
**Author the user story for this feature**

As a user, I want to be able to make use of `test-target-for-shards` so I can specify tests to run in specific shards and have the possibility of running all other tests available assigned automatically to shards like "smart-flank".

Lets explore and see if first its possible due to making use of the Gcloud specific `test-target-for-shards` option.

**Comment by piotradamczyk5** [comment]
[More info](https://firebase-community.slack.com/archives/C72V6UW8M/p1611322014000600)
