### ISSUE TITLE
IT for all supported OS's 

### ISSUE THREAD

**Issue by Sloox** [Flank/flank#1539]
**Feature Description**

Following from the discussion had here: _Originally posted by @piotradamczyk5 in https://github.com/Flank/flank/pull/1537#discussion_r565460442_
It appears we need to take a closer look at the support and modifications required for integration tests run on all 3 of Flanks supported platforms.

This includes MacOS, Windows & Linux and the integration with its workflow pointers and buildscan commenting.
 
A summary of the discussion is as follows:

**Action items**
1. add more OS ✅
2. figure out how to pass 3 URLs to the another jobs
3. change integration processResult to handle 3 URLs (and 3 results actually)
4. change post-comment_with_results to handle 3 urls

**Discussion solution**
I am wondering how job is behaving with os matrix? Is it run sequentially/in parallel with different os each? How about `outputs` - are they somehow aggregated? Maybe 2) from my previous comment won't be so difficult. We could set URL, for each os, with suffix, like: 
```
echo "::set-output name=scan-url-${{ matrix.os }}::${{ steps.run-it.outputs.build-scan-url }}"
```
and then set explicit job output (example):
```
(...)

outputs:
  build-scan-url-macos: ${{ steps.run-it.outputs.build-scan-url-macos }}
  build-scan-url-ubuntu: ${{ steps.run-it.outputs.build-scan-url-ubuntu }}

(etc...)
```
Then fetching those data will be easy.
Of course, it's my guess and it should be verified

_Originally posted by @pawelpasterz in https://github.com/Flank/flank/pull/1537#discussion_r565853173_

**Notes**
Take a look at: https://github.community/t/can-workflow-specify-which-self-runner-to-run-a-job/17405

**Comment by Sloox** [comment]
@piotradamczyk5 @pawelpasterz please add anything that you think is necceasary

**Comment by axelzuziak-gogo** [comment]
@Sloox can we convert it to Epic and created smaller subtickets?
