### ISSUE TITLE
Organize flank scripts into separated layers

### ISSUE THREAD

**Issue by jan-gogo** [Flank/flank#1541]
**Author the user story for this feature**

As a contributor, I want to have layers grouped in packages so I can easily identify the responsibility of each.

**Describe the solution**
1. Separate logical operations from CliKt commands.
1. Group CliKt commands in `cli` package and fix the structure
1. Group all domain code in `ops` package
1. Separate `utils` and `data`

**Comment by axelzuziak-gogo** [comment]
@jan-gogo / @piotradamczyk5 / @adamfilipow92  can you provide a sdd document for a whole epic?
