### ISSUE TITLE
Redesign package structure for flank scripts domain

### ISSUE THREAD

**Issue by jan-gogo** [Flank/flank#1542]
**Requirements**

* The domain layer ("ops") package should not have more than 2 nests inside.
* Public functions used by CLI commands should be easy to identify and distinguish from internal helper functions.

**Describe the solution**

1. Prepare a list of public flank-scripts functions used in CLI commands.
2. Based on the functions list, identify domains and prepare the proposal for a new packages structure.

**Comment by axelzuziak-gogo** [comment]
@jan-gogo / @piotradamczyk5 / @adamfilipow92  can you provide a sdd document for a whole epic?
