### ISSUE TITLE
Make flank-scripts features not depends on each other

### ISSUE THREAD

**Issue by jan-gogo** [Flank/flank#1543]
**Author the user story for this feature**

As a contributor, I want to keep features not dependent on each other so I don't have to be afraid of the hidden complexity of the domain layer.

**Describe the solution**

1. Identify relations between different `flank-scripts` features.
1. Consider identified code as a standalone utility(ies).
1. Move common implementation to the separated package(s) outside `ops`.

**Comment by axelzuziak-gogo** [comment]
@jan-gogo / @piotradamczyk5 / @adamfilipow92  can you provide a sdd document for a whole epic?
