### ISSUE TITLE
Modify Integration processResult to handle 3 URLs & 3 results

### ISSUE THREAD

**Issue by Sloox** [Flank/flank#1553]
processResult needs to be modified once the 3 urls have been passed to the correct locations. We also need to handle the 3 results correctly at this point.

**Comment by pawelpasterz** [comment]
As discussed:
1) `process_result` should expect 3 URL strings
1) ...but none is required (URL can be empty)
1) print URLs for failure message only
1) print non-empty URL only

cc @Sloox

**Comment by pawelpasterz** [comment]
Reopen - Mistakenly closed in #1624
