### ISSUE TITLE
Only print flank version on Run command

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#1561]
**Describe the bug**
> A clear and concise description of what the bug is.

Every command starts by printing the flank version. I think only the run command should start by printing the version.

The workflow is someone runs Flank and then wants to know what version of flank was used to execute the tests. I don't think it makes sense to print the flank version on `flank provided-software list` for example.

**To Reproduce**
> Steps to reproduce the behavior:

1. Run `flank provided-software list`
2. See the version is printed

```
$ flank provided-software list
version: local_snapshot
revision: ae09391820ab7facaaa5b7679876e9ae2c0edaed
session id: 39f08992-c5c8-4f61-9fb2-e61aea7f7a97

┌──────────────────────┐
│ ORCHESTRATOR VERSION │
├──────────────────────┤
│ 1.0.2                │
└──────────────────────┘
```

**Expected behavior**
> A clear and concise description of what you expected to happen.

No version printed unless we are invoking a `flank run ...` command or the version command directly.

```
$ flank provided-software list

┌──────────────────────┐
│ ORCHESTRATOR VERSION │
├──────────────────────┤
│ 1.0.2                │
└──────────────────────┘
```

**Details (please complete the following information):**
> Have you tested on the latest Flank snapshot?
>
> Post the output of ` flank --version`.

```
flank --version
version: local_snapshot
revision: ae09391820ab7facaaa5b7679876e9ae2c0edaed
session id: 35f6c8a1-2f32-44b7-963d-62b7ff1c6933
```

**Comment by adamfilipow92** [comment]
Currently, version printing is placed in ```Main.kt->main()```

```kotlin

logLn("version: " + readVersion())
logLn("revision: " + readRevision())
logLn("session id: $sessionId")
logLn()

```

## Implementation proposition

1. Move this code to ```Utils.kt``` to a separate function like
```kotlin

fun printVersionInfo() {
    logLn("version: " + readVersion())
    logLn("revision: " + readRevision())
    logLn("session id: $sessionId")
    logLn()
}

```

1. Use ```printVersionInfo()``` function in ```AndroidRunCommand``` and in ```IosRunCommand``` to prevent printing in other places than run commands

1. In ```Main.kt``` modify ```run()``` function to 

```kotlin

    override fun run() {
        if (printVersion) printVersionInfo()
        else CommandLine.usage(Main::class.java, System.out)
    }

 ```
