### ISSUE TITLE
Move publishing flank-scripts from bintray to other place

### ISSUE THREAD

**Issue by piotradamczyk5** [Flank/flank#1565]
**Author the user story for this feature**

As a Developer, I want to upload flank-scripts to maven repository with direct link so I can download it when needed.

**Describe the solution**
Currently, we are uploading flank-scripts to bintray which will be closed at the end of April, so we should found another place to store flank-scripts binaries.

Please update also flank-scripts download task
```kotlin
tasks.register("download") {
    val sourceUrl = "https://dl.bintray.com/flank/maven/com/github/flank/$artifactID/$version/$artifactID-$version.jar"
    val destinationFile = Paths.get("bash", "flank-scripts.jar").toFile()
    ant.invokeMethod("get", mapOf("src" to sourceUrl, "dest" to destinationFile))
}
```

**Requirements**
1. Free
2. Easy to upload and download
3. Possibility to get a direct link to download jar

**Possible solutions**
- [Jitpack](https://jitpack.io/) 

**Describe alternatives considered**
As an alternative, we could upload flank-scripts to Github packages and get a link through Github API, but it needs one additional request with parsing output

**Comment by bootstraponline** [comment]
my preference is to use the github maven repo https://github.com/features/packages

github is unlikely to go away

jitpack could disappear in the same way jcenter did

**Comment by piotradamczyk5** [comment]
@bootstraponline I see your point of view, but please notice, that flank-scripts is just using internally by our team. 
What is more, we do not use it as Gradle dependency, but as a bash program, so we just need to download the right jar for it.
Github packages do not have a direct link to download jar as well as API to retrieve it, so for this particular case I think we should add it to jitpack to use it as easy as possible
