### ISSUE TITLE
Better experience for multi-module Android projects

### ISSUE THREAD

**Issue by asadsalman** [Flank/flank#1573]
As an engineer, I want to be able to run multiple test APKs in the same invocation, so I can save on setup/tear down time and test execution costs.

You can have multiple modules in an Android project, all of which can produce instrumentation app/test APKs. It would be nice to test multiple APKs one flank (and underlying firebase) invocation.

This is currently, partially, possible with the `additional-app-test-apks` flag. One can specify several app and test APKs and they are started in separate matrices in parallel. The limitation of this approach is that tests can not be sharded across modules, a device needs to be started for each module. 

It would be great if Flank could merge test APKs instead of mapping each APK to a separate matrix.

**Comment by bootstraponline** [comment]
I think the root limitation is that FTL only allows one test apk per matrix.

**Comment by asadsalman** [comment]
Yeah I think so. I wonder if there's some way to merge androidTest APKs and upload just the merged one.
This may be a bigger challenge for application modules where there is an app APK and a test APK, but may be easier for library modules where there's just a test APK.

**Comment by pawelpasterz** [comment]
Have you tried https://github.com/runningcode/fladle ? It provides a pretty clever configuration for multiple apks approach. Not sure if it can handle your case though... 🤔

**Comment by jan-gogo** [comment]
I am afraid that this feature is currently impossible to implement. But maybe will be after successful integration with Corellium, we will see.
