### ISSUE TITLE
Document google APIs usecases.

### ISSUE THREAD

**Issue by jan-gogo** [Flank/flank#1580]
**Author the user story for this feature**

As a developer, I want to have a document with described google APIs (method and structures) used in flank so further it would be helpful for preparing an adapter to Corellium API.

**Describe the solution**

1. Find all places in flank code where google APIs are used. 
2. Prepare a list of all google API use cases, and describe them in markdown doc.

**Comment by jan-gogo** [comment]
Split into two issues

**Comment by jan-gogo** [comment]
1. Prepare FTL API commands list used in flank - 5
2. Correlium API research - 8

**Comment by jan-gogo** [comment]
> Split into two issues

DONE

**Comment by adamfilipow92** [comment]
Documentation created in this pull request: https://github.com/Flank/flank/pull/1588, file: docs/gcloud/google_api_usecases.md
