### ISSUE TITLE
Verify iOS sharding on Xcode 12.3

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#1582]
**Describe the bug**
> A clear and concise description of what the bug is.

Verify iOS tests are sharded correctly using Xcode 12.3. See https://firebase-community.slack.com/archives/C1MTSQ5QT/p1612876163203200 for additional context.

**Comment by jan-gogo** [comment]
We need to investigate if it's a flank bug.

**Comment by axelzuziak-gogo** [comment]
Verified - works fine on:
- flank example projects
- few open-source projects
compiled using Xcode 12.3.

Also I found no differences in FTL output between Xcode 12.1 vs Xcode 12.3 versions.
