### ISSUE TITLE
Flank recognises and highlights tests that were not run by FTL

### ISSUE THREAD

**Issue by dbarwacz** [Flank/flank#1591]
When automation fails at very early stage of running, FTL will not include them in the final result xml file:
Let's assume you have test suite with ~270 tests.
`android_shards.json` have 20 shards, with around 13-14 tests each.
JUnitReport.xml does have record of 20 test suites (`<testsuite>` tag in xml).
Failed test run is empty, that is instead of expected: 
```<testsuite name="Pixel2-29-en-portrait" tests="****14****" failures="13" flakes="0" errors="0" skipped="0" time="239.862" timestamp="2021-02-05T13:26:39" hostname="localhost">```
we get:

```<testsuite name="Pixel2-29-en-portrait" tests="****0****" failures="0" flakes="0" errors="0" skipped="0" time="0.000" timestamp="1970-01-01T00:00:00" hostname="localhost"/>```
(emphasis on numbers mine).
5. `{device}-test-results-merged.xml` do not seem to even be aware of missing tests.
6. There is a logcat for 'failed' device available `(test-lab-4nv5xxtjty0h6-isys7vj9jhnm2/2021-02-05_14-22-22.503000_rt8k/matrix_0/Pixel2-29-en-portrait-shard_2/logcat)`
7. As a result, some tests are not run but flank does not connect the dot that they were configured to run as specified in `android_shards.json`.

The feature request I suggest is that upon completion, flank compares sharding file that FTL generated with actual results to check if some tests were not 'lost'.

**Comment by dbarwacz** [comment]
(Initially reported as bug in https://github.com/Flank/flank/issues/1569)

**Comment by jan-gogo** [comment]
We will prepare more details about the solution.

**Comment by jan-gogo** [comment]
Possibly related with https://github.com/Flank/flank/issues/1327

**Comment by jan-gogo** [comment]
Converted to https://github.com/Flank/flank/issues/1677
