### ISSUE TITLE
Test Class with annotation @RunWith(Parameterized::class) not being picked up in Firebase Test Run after upgrading from v4x to v21x

### ISSUE THREAD

**Issue by shawnshaligram** [Flank/flank#1602]
**Describe the bug**
> A clear and concise description of what the bug is.

We have a few test classes which are being annotated by `@RunWith(Parameterized::class)` After upgrading from v4 to v21 of Flank Test Runner we observed the test which is paramterized is not being picked up and run in FTL

**To Reproduce**
> Steps to reproduce the behavior:

1. Upgrade from Flank v4 to v21
2. Create a basic test class without Parameterized class
3. Create a test class with `@RunWith(Parameterized::class)` and import `import org.junit.runners.Parameterized`
4. Run both tests in Firebase

**Expected behavior**
> A clear and concise description of what you expected to happen.

Observe only the none Parameterized class gets picked up and run in FTL

**Details (please complete the following information):**
> Have you tested on the latest Flank snapshot?
>
> Post the output of ` flank --version`.

**Additional context**
> Add any other context about the problem here.

Works fine with v4 but not with v21

**Comment by pawelpasterz** [comment]
Please check https://github.com/Flank/flank/blob/master/docs/test_sharding.md#parameterized-tests

**Comment by jan-gogo** [comment]
@shawnshaligram Do you have any additional questions about the https://github.com/Flank/flank/blob/master/docs/test_sharding.md#parameterized-tests or the issue itself? If not we will close this issue after few days.
