### ISSUE TITLE
Test hybrid app on multiple platform in one run

### ISSUE THREAD

**Issue by adamfilipow92** [Flank/flank#1611]
**Author the user story for this feature**

As a hybrid app developer (eg. Flutter developer), I want to test my application in both ios and android in one Flank run. So I can get one result and save time.

**Describe the solution**

1. Prepare flutter example
2. Allow Flank to run ios and android in one run.

**Additional context**

https://flutter.dev/docs/testing/integration-tests#testing-on-firebase-test-lab

It's only a proposal but I think this feature could be helpful because some cases should be tested on both platforms. Let me know WDYT!

@bootstraponline @jan-gogo @axelzuziak-gogo @pawelpasterz @piotradamczyk5 @Sloox

**Comment by Sloox** [comment]
@adamfilipow92 do we have anyone with flutter experience among us?
Flutter looks interesting and if it gets support would be a good addition.

**Comment by adamfilipow92** [comment]
After a talk with @jan-gogo we decide to close this ticket until FTL starts supporting sharding in flutter projects.
