### ISSUE TITLE
Custom sharding JSON

### ISSUE THREAD

**Issue by asadsalman** [Flank/flank#1665]
I want to be able to provide a custom `android_shards.json` to Flank, so I can write custom sharding logic for my tests.

**Solution**
Flank produces an `android_shards.json` file after parsing APK etc. I want to be able to provide a custom one myself. Flank will construct and execute whatever shards are declared in the custom `android_shards.json`.

**Alternatives**
Flank (and gcloud) do provide `test-targets-for-shard` flag. That will achieve what I'm looking for but, in its current form, it would be pretty hard to use since  I would have to write a flank.yml file for each shard.

**Comment by jan-gogo** [comment]
Looks like a really nice feature.

TODO:
1. New config option
2. `android_shards.json` to `InstrumentationTestContext` mapper
3. Update `List<AndroidTestContext>.setupShards` function for using shards from `android_shards.json` if option is specified.
    * Validate data loaded from `android_shards.json` in `AndroidArgs` context
    * Print proper log if some error occurs.
4. Test the happy path and each known exception.

Just leaving a quick note for estimation.

**Comment by bootstraponline** [comment]
I think we should also support custom sharding JSON on iOS.
