### ISSUE TITLE
Add missing test methods to JUnitReport.xml 

### ISSUE THREAD

**Issue by jan-gogo** [Flank/flank#1677]
**Author the user story for this feature**

As a flank end user, I want to have all tests that were supposed to run, visible and marked properly in JUnitResult so I can easily investigate them all.

**References**

* https://github.com/Flank/flank/issues/1327
* https://github.com/Flank/flank/issues/1591

**Steps proposition**

1. Store info about tests supposed to run before the test run.
    * Should work also when smart sharding is not used.
2. Compare the list of tests with JUnitResult for missing tests.
3. Update JUnitResult with missing tests.

**Describe the solution**

Prepare an SDD:
* Describe XML format for missing tests.
* Investigate and describe required changes.
* Take steps proposition into an account.

The SDD should contain all information necessary for implementation.

**Comment by jan-gogo** [comment]
Parametrized classes can not work

**Comment by adamfilipow92** [comment]
# Missing test methods SDD

Flank users want to see all tests in JunitResult even if tests have no results. 

## References

* https://github.com/Flank/flank/issues/1677
* https://github.com/Flank/flank/issues/1327
* https://github.com/Flank/flank/issues/1591

## Goals

Improved Flank usability by storing tests without results in JUnitResults.xml file so users can easily find them.

## XML format proposition 

Basing on ignored JUnit test node, we can use similar construction.

```xml
    <testsuite name="junit-missing" tests="2" failures="0" errors="0" skipped="2" time="0.0" timestamp="2021-05-26T13:33:40" hostname="localhost">
        <testcase name="missingIgnoredTestWithIgnore" classname="com.example.test_app.MissingInstrumentedTest" time="0.0" />
        <testcase name="missingIgnoredTestWithSuppress" classname="com.example.test_app.MissingInstrumentedTest" time="0.0" />
    </testsuite>
```

## Required changes

Example how to add a custom node to JUnitXml is [here](https://github.com/Flank/flank/blob/5a0acf2c1349532d01ffc64e977e3e3e7f9307aa/test_runner/src/main/kotlin/ftl/reports/util/ReportManager.kt#L67).
We can fetch all test cases by using 
[getAndroidMatrixShards()](https://github.com/Flank/flank/blob/f34ee09f53a1f71a158d10afbb002fabba45839a/test_runner/src/main/kotlin/ftl/run/platform/android/GetAndroidMatrixShards.kt#L9)
or on iOS side by using function like:

```kotlin
private fun IosArgs.getAllTestCases() = when (xcTestRunData.version) {
    XcTestRunVersion.V1 -> xcTestRunData.shardTargets.values.first().flatMap { it.values }
    XcTestRunVersion.V2 -> xcTestRunData.shardTargets.flatMap { it.value }.flatMap { it.values }
}
```

## Design

1. Get all test cases and map it to ``` JUnitTest.Case```
   * There is difference between ios and android format
   * Android test case string looks like ```class class_name#test_name```
      ```kotlin
      fun String.toAndroidTestCase() = JUnitTest.Case(
          classname = split("#").first().replace("class ", ""),
          name = split("#").last(),
          time = "0.0",
          skipped = null
      )
      ```
   * Ios test case string looks like ```class_name/test_name```
      ```kotlin
      fun String.toIosTestCase() = JUnitTest.Case(
          classname = split("/").first(),
          name = split("/").last() + "()",
          time = "0.0",
          skipped = null
      )
      ```
1. Filter only test cases not in ```JUnitTest.Result``` and not in ignored test cases

1. In ReportManager [below adding ignored test cases](https://github.com/Flank/flank/blob/5a0acf2c1349532d01ffc64e977e3e3e7f9307aa/test_runner/src/main/kotlin/ftl/reports/util/ReportManager.kt#L68) 
   add the result of filtering
   
## Dependencies

There are no changes

## Testing

The solution should be unit tested and/or integration tested.

## Results

JUnitResults.xml file should look like

```xml
<testsuites>
  <testsuite name="NexusLowRes-28-en-portrait" tests="2" failures="0" flakes="0" errors="0" skipped="1" time="3.485" timestamp="2021-05-27T14:48:15" hostname="localhost">
    <testcase name="ignoredTestWithIgnore" classname="com.example.test_app.InstrumentedTest" time="1.051">
      <skipped/>
      <webLink>https://console.firebase.google.com/project/flank-open-source/testlab/histories/bh.da0c237aaa33732/matrices/6960342538380617010/executions/bs.5442acc7c7d461b/testcases/2</webLink>
    </testcase>
    <testcase name="test" classname="com.example.test_app.InstrumentedTest" time="2.434">
      <webLink>https://console.firebase.google.com/project/flank-open-source/testlab/histories/bh.da0c237aaa33732/matrices/6960342538380617010/executions/bs.5442acc7c7d461b/testcases/1</webLink>
    </testcase>
  </testsuite>
  <testsuite name="junit-ignored" tests="2" failures="0" errors="0" skipped="2" time="0.0" timestamp="2021-05-27T14:49:03" hostname="localhost">
    <testcase name="ignoredTestWithIgnore" classname="com.example.test_app.InstrumentedTest" time="0.0">
      <skipped/>
    </testcase>
    <testcase name="ignoredTestWithSuppress" classname="com.example.test_app.InstrumentedTest" time="0.0">
      <skipped/>
    </testcase>
  </testsuite>
   <testsuite name="junit-missing" tests="2" failures="0" errors="0" skipped="2" time="0.0" timestamp="2021-05-26T13:33:40" hostname="localhost">
      <testcase name="missingIgnoredTestWithIgnore" classname="com.example.test_app.MissingInstrumentedTest" time="0.0" />
      <testcase name="missingIgnoredTestWithSuppress" classname="com.example.test_app.MissingInstrumentedTest" time="0.0" />
   </testsuite>
</testsuites>
```
