### ISSUE TITLE
iOS IT Windows: nm.exe for windows

### ISSUE THREAD

**Issue by Sloox** [Flank/flank#1684]
**Author the user story for this feature**
A suitable nm.exe needs to be included for windows so iOS integration tests can be run on windows as expected:
**Describe the solution**
To enable use of iOS Integration tests on windows we need to find and include a suitable nm.exe for windows.
Initial research identified nm.exe from _https://www.cygwin.com/_

nm.exe also needs to be included within the ~/.flank so it can be used correctly with flank scripts.

It needs to be tested that it works as intended.

**Describe alternatives considered**
https://swift.org/blog/swift-on-windows/ will most likely have the best support for nm.exe

**Comment by bootstraponline** [comment]
> https://swift.org/blog/swift-on-windows/ will most likely have the best support for nm.exe

I'd fetch the nm binary from the official Apple project releases rather than cygwin. That should match the nm used by users.
