### ISSUE TITLE
Prepare Flutter example for Flank

### ISSUE THREAD

**Issue by adamfilipow92** [Flank/flank#1690]
**Author the user story for this feature**

As a Flutter developer I want to have example how to use Flutter with Flank so I can easly use Flank in my project.

**Describe the solution**

1. Prepare Flutter artifact
1. Prepare test case for android tests for flutter
1. Document how to use Flutter with Flank

**Comment by bitsydarel** [comment]
@axelzuziak-gogo Any plans to add flutter support ?

**Comment by Giuspepe** [comment]
Hey @adamfilipow92, what's the current status of Flutter support in Flank? I'd love to use Flank to speed up our flutter integration tests on Firebase Test Lab.
