### ISSUE TITLE
Dogfood our Flank Github action

### ISSUE THREAD

**Issue by Sloox** [Flank/flank#1702]
**Author the user story for this feature**

As a developer its always good to dogfood our own product. Lets use Flank Github action on the project itself.

**Describe alternatives considered**

This is possibly a duplicate.

**Comment by Sloox** [comment]
@piotradamczyk5 is this already done? I would assume we could remove some of our existing implementation  in favor of using the GitHub action? So I assumed its not.

**Comment by piotradamczyk5** [comment]
It is done, we could use github action instead of our IT tests

**Comment by Sloox** [comment]
@piotradamczyk5 lets then update our ticket as its a cool replacement, wdyt?

**Comment by piotradamczyk5** [comment]
Perfect for me 🎉

**Comment by jan-gogo** [comment]
Provide more information, what should exactly be done in the scope of this issue. It's a tiger or dragon?

**Comment by piotradamczyk5** [comment]
This is a 🐯  
The task is about replacing custom integration tests solution with Flank github action

**Comment by pawelpasterz** [comment]
For my curiosity, what would be added value from it? Does it mean that every change we do in `integration_tests` module needs to be published as gh action with new version?
