### ISSUE TITLE
Refactor Flank Binaries

### ISSUE THREAD

**Issue by Sloox** [Flank/flank#1708]
**Author the user story for this feature**

Flank is directly downloading files for its binaries from direct URLs
eg: https://swift.org/builds/swift-5.0.1-release/ubuntu1604/swift-5.0.1-RELEASE/swift-5.0.1-RELEASE-ubuntu16.04.tar.gz for ubuntu.

Windows is making use of: https://github.com/Flank/binaries
Lets consolidate them to make use of one source of truth as it will reduce the overhead and code. 

**Describe alternatives considered**
Continue to use seperate ways.

**Comment by piotradamczyk5** [comment]
@Sloox Ubuntu also use Flank binaries https://github.com/Flank/binaries/releases/tag/linux

**Comment by jan-gogo** [comment]
One question - are there any benefits of using direct hosting instead of our binaries on GitHub?

If not, the steps for this issue could be:
1. Upload binaries required by Flank into https://github.com/Flank/binaries repo.
    * https://swift.org/builds/swift-5.0.1-release/ubuntu1604/swift-5.0.1-RELEASE/swift-5.0.1-RELEASE-ubuntu16.04.tar.gz
    * Anything else?
2. Update implementation for using binaries from https://github.com/Flank/binaries instead of direct hosting.

**Comment by piotradamczyk5** [comment]
> One question - are there any benefits of using direct hosting instead of our binaries on GitHub?
> 
> If not, the steps for this issue could be:
> 
> 1. Upload binaries required by Flank into https://github.com/Flank/binaries repo.
>    
>    * https://swift.org/builds/swift-5.0.1-release/ubuntu1604/swift-5.0.1-RELEASE/swift-5.0.1-RELEASE-ubuntu16.04.tar.gz
>    * Anything else?
> 2. Update implementation for using binaries from https://github.com/Flank/binaries instead of direct hosting.

@jan-gogo @Sloox  as I mentioned it already works that way
