### ISSUE TITLE
Allow device & shard count validation to be skipped

### ISSUE THREAD

**Issue by inktomi** [Flank/flank#1710]
As a firebase test lab user, I may be offered access from time to time above the normal limits. As a flank & fladle user, I would like to be able to pass in customized config values to use my account to the fullest - but the configuration validation prevents it. 

I would like the ability to skip config validation by passing in a flag at runtime. This flag could even be part of the config, it doesn't need to be a command line option. In the event of having an invalid config but passing the skip validation flag, Flank should crash (unparsable config) or pass the values provided (eg, 1000 shards, or `FluffyBunny` device type, etc). 

As this is part of Flank that's (correctly!) built in, it's not currently possible to work around this when passing in otherwise invalid parameters.

**Comment by jan-gogo** [comment]
**For estimation**
1. Add new option `skip-config-validation`
2. Update implementation for skipping o args validation if this option is used.
