### ISSUE TITLE
Support class-level annotation filtering

### ISSUE THREAD

**Issue by asadsalman** [Flank/flank#1729]
Flank currently supports method-level annotation filtering, i.e. with `annotation` and `notAnnotation` in `test-targets`. But it does not support _class_-level annotation. For example, `notAnnotation androidx.test.filters.LargeTest` will not run test methods with `@LargeTest` annotation, but will still run test classes with `@LargeTest` annotation.

Solution:
Apply annotation  filtering to class level too.

**Comment by pawelpasterz** [comment]
That's a cool feature 👍

**Comment by asadsalman** [comment]
Looks like I wasn't applying test-targets in the wrong `flank.yml`, my bad. Verified that this feature already exists.
