### ISSUE TITLE
Move ftl.cli to ftl.presentation.cli

### ISSUE THREAD

**Issue by jan-gogo** [Flank/flank#1734]
A cosmetic change but required to keep a high level of consistency with [component diagram](http://www.plantuml.com/plantuml/proxy?cache=no&fmt=svg&src=https://raw.githubusercontent.com/Flank/flank/main/docs/hld/flank-component-diagram.puml)

Just copy and paste the whole `ftl.cli` package into `ftl.presentation.cli`. 
Make sure the imports were updated properly.

**Comment by piotradamczyk5** [comment]
@jan-gogo  bad link attached
