### ISSUE TITLE
Data scratch - file reference

### ISSUE THREAD

**Issue by jan-gogo** [Flank/flank#1759]
# Plan

According to the specification described in epic [#1727](https://github.com/Flank/flank/issues/1727)
add abstraction and implementation for the following part of the data layer:

## Abstraction

`ftl/data/FileReference.kt`

```kotlin
package ftl.data

val downloadFileReference: FileReference.Download get() = TODO()
val uploadFileReference: FileReference.Download get() = TODO()
val existFileReference: FileReference.Exist get() = TODO()

data class FileReference(
    val local: String = "",
    val remote: String = ""
) {
    interface Download : (FileReference) -> FileReference
    interface Upload : (FileReference) -> FileReference
    interface Exist : (FileReference) -> Boolean
}
```

## Target

* `FileReference.kt`

## Adapter

`ftl/adapter/GoogleFileReference.kt`

### Note

Consider reuse or expand `RemoteStorage` implementation.

**Comment by Sloox** [comment]
blocked by: https://github.com/Flank/flank/issues/1753
