### ISSUE TITLE
MacOS Test fails

### ISSUE THREAD

**Issue by Sloox** [Flank/flank#1769]
**Describe the bug**
> A clear and concise description of what the bug is.
MacOS Unit tests are flaky with a continual fail on CI with the following error:

```
flank.scripts.ops.testartifacts.TestArtifactsRepoTest > should not throw when gh token not set FAILED
    java.lang.AssertionError at TestArtifactsRepoTest.kt:15
```

**To Reproduce**
> Steps to reproduce the behavior:

1. Most CI builds are failing

**Expected behavior**
> No failure 

**Details (please complete the following information):**
> Usually a "re-run" sorts out the problem.

**Comment by pawelpasterz** [comment]
It will be solved with #1772
