### ISSUE TITLE
`ftl.Main` changed to `ftl.MainKt` in 21.04.0 breaking scripts and Fladle.

### ISSUE THREAD

**Issue by runningcode** [Flank/flank#1780]
**Describe the bug**
In this PR: https://github.com/Flank/flank/pull/1732/files
`ftl.Main` changed to `ftl.MainKt` which breaks scripts and dependencies which were using the old `ftl.Main` task name.
This breaks all versions of `fladle` with the error message: `Error: Could not find or load main class ftl.Main`

**To Reproduce**
1. Update flank in fladle to 21.04.0 with `flankVersion = '21.04.0'`
2. `./gradlew runFlank`
3. `Error: Could not find or load main class ftl.Main`

See this build scan for the error message.

**Comment by bootstraponline** [comment]
@jan-gogo I think we should add a test for this going forward. I don't think we should break people by renaming the entry point.
