### ISSUE TITLE
Non-lowercase project names not supported

### ISSUE THREAD

**Issue by asadsalman** [Flank/flank#1789]
Flank does not support Firebase project names that are not entirely lowercase. 
While tests start and finish just fine, at the end of the run Flank outputs: `Matrix is ERROR`. And the following:

```
  No cost. 0m


MatrixResultsReport
  1 / 1 (100.00%)
┌─────────┬───────────┬──────────┬─────────────────┬──────────────┐
│ OUTCOME │ MATRIX ID │ APP NAME │ TEST AXIS VALUE │ TEST DETAILS │
├─────────┼───────────┼──────────┼─────────────────┼──────────────┤
└─────────┴───────────┴──────────┴─────────────────┴──────────────┘
```

**To Reproduce**
1. Create Firebase project with non-lowercase name 
2. Set project name in `flank.yml`
3. Run flank

**Expected behavior**
Print matrix output as normal.
Normal behavior can be reproduced by setting the project name as all lowercase (even if the project is not entirely lowercase in Firebase). This executes just fine.

**Details (please complete the following information):**
Test on latest flank release and snapshot. Also tested against gcloud (where it worked fine). Also tested by setting project name to all lower case (where it also worked fine).

**Comment by pawelpasterz** [comment]
I think that might be related to FTL API limitations regarding project ID (at least based on your description)
Technically you can create project with name `TEST-PROJECT` but `ID` will be lower cased automatically (`name` is used on UI, `ID` for API requests in flank)
<img width="518" alt="Screenshot 2021-04-09 at 08 23 09" src="https://user-images.githubusercontent.com/32893017/114138942-a8789a00-990e-11eb-8d27-518fff0e6bc4.png">
<img width="509" alt="Screenshot 2021-04-09 at 08 24 37" src="https://user-images.githubusercontent.com/32893017/114139415-4ec49f80-990f-11eb-8f57-6dbe2ca26de9.png">

Even if I try to rename id to have at least one upper letter it won't let me:
<img width="448" alt="Screenshot 2021-04-09 at 08 38 27" src="https://user-images.githubusercontent.com/32893017/114139189-03aa8c80-990f-11eb-823d-56245c31901a.png">

`gcloud` does not have `project` property -- it uses JSON with a private key to authenticate. You can verify the project id in that JSON:
```
{
  "type": "service_account",
  "project_id": "testing-unique-project",
  ...
}
```


All above is true except the case when you have a strongly customized project prepared directly by FTL team for your company. I don't know, maybe there is a way to have a project id with an uppercase letter (with FTL customization).

Let me know what do you think

#### Solution?
I think we could add a fallback logic to the flank, if no project with a given ID is found, lowercase it and try again.

**Comment by piotradamczyk5** [comment]
Project ID should be always lower case, so I have added logic to make the project name lower case always, based on @pawelpasterz , my research, and @asadsalman input

**Comment by asadsalman** [comment]
The project name that shows up on my dashboard definitely supports uppercase. No customization etc.
<img src="https://user-images.githubusercontent.com/8086397/114213774-49b81e00-9918-11eb-842f-e4ae8c499db7.png" width="500">

If I copy the project name from there, there is really no indication of what went wrong when I run it through Flank. But yes, you're absolutely right, in the URL and auth JSON the project names are lower case. I think that's why  `gcloud` never runs into this problem.
