### ISSUE TITLE
Add column with test apk name in result table

### ISSUE THREAD

**Issue by kozaxinan** [Flank/flank#1803]
**Describe the bug**
> A clear and concise description of what the bug is.

21.04.1
In result table, apk name is always app-debug.apk

![Screen Shot 2021-04-13 at 15 27 28](https://user-images.githubusercontent.com/2559837/114552047-d17d8f80-9c6c-11eb-8954-ea7c1a1e4819.png)

**To Reproduce**
> Steps to reproduce the behavior:

1. Have multimodule project
2. Configure it with fladle
3. run and see result table

**Expected behavior**
> A clear and concise description of what you expected to happen.

Apk name column should show apk that used in that test run per module.

**Comment by bootstraponline** [comment]
The table is showing the app apk name. I agree showing the test apk instead may be more useful.

**Comment by kozaxinan** [comment]
Is it possible to have different app apk? I wasnt aware of that. test-apk name would be better as table shows result of test apk.

**Comment by pawelpasterz** [comment]
> Is it possible to have different app apk? 

Yes, you can define app - test app pair with `additional-app-test-apks` https://github.com/Flank/flank/blob/475a124a994f15c1bf7643b9f02578d385501684/test_runner/flank.yml#L295-L301

Changing label to feature request since it is working as designed

Dev note:
https://github.com/Flank/flank/blob/475a124a994f15c1bf7643b9f02578d385501684/test_runner/src/main/kotlin/ftl/json/SavedMatrix.kt#L110

**Comment by kozaxinan** [comment]
I can confirm Fulladle plugin only adds app-debug to top level and doesnt add additional app to tests. https://github.com/runningcode/fladle/blob/master/fladle-plugin/src/main/java/com/osacky/flank/gradle/FulladlePlugin.kt#L73

**Comment by bootstraponline** [comment]
> What is the usecase for adding different app apks? Different variant support or something like that?

Some companies have multiple app apks and prefer to test them as a logical group. Typical use case doesn't need this feature.

**Comment by kozaxinan** [comment]
Even in that case, test apks need to have unique names. Printing test apk names would be much easier to spot which module has test fail. If using same test apk for different app is not possible, printing test apk name would be better in any case.

**Comment by bootstraponline** [comment]
> printing test apk name would be better in any case.

I agree! Thanks for the feedback.
