### ISSUE TITLE
Build and use Fladle plugin together with Flank

### ISSUE THREAD

**Issue by piotradamczyk5** [Flank/flank#1804]
**Author the user story for this feature**

As a Developer, I want to use Fladle together with Flank using composite build so I can develop plugin even better.

**Describe the solution**
1. Setup Fladle as git submodule
1. Use a composite build to substitute the flank dependency.
1. Add an integration test for the fladle plugin in the flank project. This is a good idea whether or not we are going to integrate both projects to prevent regressions.

**Resources**
- [Investigation](https://github.com/Flank/flank/issues/1681)
- [composite builds](https://docs.gradle.org/current/userguide/composite_builds.html)
- [Composite Builds Declared Substitutions](https://docs.gradle.org/7.0-rc-1/samples/sample_composite_builds_declared_substitutions.html)
- [Composite Builds Plugin Development](https://docs.gradle.org/7.0-rc-1/samples/sample_composite_builds_plugin_development.html)

**Comment by bootstraponline** [comment]
do we need the submodule for a composite build?

**Comment by piotradamczyk5** [comment]
We need to substitute in somehow with providing path to module and to make it more automated submodules seems to be good solution

**Comment by axelzuziak-gogo** [comment]
Closing this ticket as #1963 #1964 were created.
