### ISSUE TITLE
Pass adb command to Testlab

### ISSUE THREAD

**Issue by mariuszmachniakzendesk** [Flank/flank#1808]
More like a question: is there a way that flank can pass adb command to Firebase Test Lab? I'm trying to set the keyboard preferences for example with such command:
`adb shell settings put secure show_ime_with_hard_keyboard 1`
Is there any way I can forward such command with flank?

**Comment by bootstraponline** [comment]
Have you tried `executeShellCommandRw`?

- https://developer.android.com/reference/android/app/UiAutomation#executeShellCommandRw(java.lang.String)

**Comment by mariuszmachniakzendesk** [comment]
that solves the problem. thx!
