### ISSUE TITLE
Greatest version on maven is wrong

### ISSUE THREAD

**Issue by kozaxinan** [Flank/flank#1822]
**Describe the bug**
> A clear and concise description of what the bug is.

https://mvnrepository.com/artifact/com.github.flank/flank/2131

on maven repository, flank's highest version is 2131. That seems like a wrong publish. Version update plugin identifies 2131 is greater than 21.04.1 and report possible update. 

This is not blocking or doing any harm but we lost ability to automatic latest version check for Flank.

I also don't have any good suggestion for version to be greater than 2131. We might need to wait 110 years to have 2131.01 release 😄

**Comment by bootstraponline** [comment]
Oh wow! Thanks for reporting this bug.

maybe we can revoke the bad version?

**Comment by piotradamczyk5** [comment]
> As I know you cannot delete a version directly from maven repository. It might require opening a ticket to them and asking for help. But I don't expect them to remove a published version just because name is wrong.

It was published by mistake during changing bintray to maven central, so I would ask them to remove it within the ticket

**Comment by piotradamczyk5** [comment]
Support ticket created: https://issues.sonatype.org/browse/MVNCENTRAL-6683

**Comment by bootstraponline** [comment]
Sonatype agreed to a one time exception. 

@piotradamczyk5 Please link me the tests that check this issue will be detected going forward. I expect flank's upgrade detection will be permanently broken if the issue happens again.

**Comment by piotradamczyk5** [comment]
So basically version number is generated by our scripts and used in[ the release process](https://github.com/Flank/flank/blob/master/.github/workflows/create_new_release.yml). 
Next release tag is generated with [function](https://github.com/Flank/flank/blob/master/flank-scripts/src/main/kotlin/flank/scripts/ops/release/NextReleaseTag.kt) and tested [here](https://github.com/Flank/flank/blob/master/flank-scripts/src/test/kotlin/flank/scripts/ops/release/NextReleaseTagGeneratorTest.kt) and [here](https://github.com/Flank/flank/blob/master/flank-scripts/src/test/kotlin/flank/scripts/cli/ci/NextTagCommandTest.kt) 
Upload manually cannot be trigger without needed credentials and the key stored securely in Github

**Comment by bootstraponline** [comment]
> I've removed the artifacts from repo1.maven.org. They may still appear in directory listing or in search results on search.maven.org, but they shouldn't be download-able. I've also regenerated the maven-metadata files associated with this artifact, though it may take an hour before those propagate to our production servers.

I think the issue should be fixed (based on the comment on the upstream JIRA issue).

**Comment by bootstraponline** [comment]
@piotradamczyk5 what do you think about adding a sanity check in the version number generation to throw an exception if the year is more than two digits? The code and tests look reasonable, however we don't appear to assert on unexpected results.

**Comment by piotradamczyk5** [comment]
Sure I will create a ticket to fail the Gradle task if the version number is not correct

**Comment by piotradamczyk5** [comment]
> Sure I will create a ticket to fail the Gradle task if the version number is not correct

[Issue created,](https://github.com/Flank/flank/issues/1839) this one could be closed
