### ISSUE TITLE
Default to service account auth

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#1831]
**Author the user story for this feature**

As a user, I want to run tests with the same credential as CI so I can have reproducible builds.

**Describe the solution**

Flank currently uses user auth and falls back to service credential authentication. We should consider the reverse.

https://github.com/Flank/flank/blob/458a12ed4a7b364f481101a749fbf0f7a408c8e8/test_runner/src/main/kotlin/ftl/adapter/google/Credentials.kt

I think there may be some historical context for why user auth is first, will be worth searching the old Flank issues/code to see if this has been discussed.

**Comment by adamfilipow92** [comment]
I was checking some tickets related to the service account but I can't find any discussion about it. I think this change can potentially fix #1792. I will create or asap

**Comment by adamfilipow92** [comment]
Realized in: https://github.com/Flank/flank/pull/1955.
