### ISSUE TITLE
Structural output - LoginGoogleAccount

### ISSUE THREAD

**Issue by jan-gogo** [Flank/flank#1866]
# Plan

According to the description of epic #1728, prepare a specification document for the structural output based on the following requirements:

* Identify all places that are producing console logs and list them in the specification. 
* Specify dedicated types and structures for logs with places (packages and namespaces) for them.
* Specify proposition how to pass `out` function reference to low-level functions that producing logs.

Make sure that specification is sufficient to implement structured output without a doubt.

# Command

`LoginGoogleAccount`

**Comment by piotradamczyk5** [comment]
## Places which produce output logs

1. Printing URL to login`UserAuth#L92-93`

   ````kotlin
   logLn("Visit the following URL in your browser:")
   logLn(url)
   ````

   `

2. User token saved `ftl.client.google.UserAuth#L118-119`

   ```kotlin
   logLn()
   logLn("User token saved to $userToken")
   ```

## Structures for messages

```kotlin
sealed interface LoginState {
    data class LoginStarted(val url: String) : LoginState
    data class LoginFinished(val tokenLocation: String) : LoginState
}
```

## Proposition of passing `out` function

- `UserAuth#request`method will return `Flow<LoginState>`

- api contract will be changed 
  from

  ```kotlin
  object UserAuthorization {
      interface Request : () -> Unit
  }
  ```

  to

  ```kotlin
  object UserAuthorization {
      interface Request : () -> Flow<LoginState>
  }
  ```

- `LoginGoogleAcount#invoke` will observe new flow and pass all collected `LoginState`to `out()` function

- `LoginCommand`will be responsible for printing correct message based on `LoginState`
