### ISSUE TITLE
set test-targets for test-run based on env vars

### ISSUE THREAD

**Issue by andreschab90** [Flank/flank#1882]
I want to set the test-targets for my ios test-run based on env vars. That would allow me for example to run only the tests for features which got changed in a PR as a statuscheck

*example config* 
`...`
`test-targets:`
`  - $TESTTARGETS`
`...`

**Comment by axelzuziak-gogo** [comment]
Let's discuss this issue on Thursday grooming session.

**Comment by jan-gogo** [comment]
### Solution draft

Inside Args creating function, parse `test-targers` value from config.
* If parsed value denotes env variable, load variable value and use it.
* Otherwise use parsed value.
