### ISSUE TITLE
My device report me "An infrastructure error occurred. Retrying..."

### ISSUE THREAD

**Issue by maxbetton** [Flank/flank#1922]
**Describe the bug**
when i launch flank in local, my Android device report in a loop `An infrastructure error occurred. Retrying...`

**Comment by bootstraponline** [comment]
do you see the same issue when using gcloud CLI?

**Comment by pawelpasterz** [comment]
@maxbetton please add more info about your case (config, etc)

Infrastructure error usually means there is something wrong with FTL itself.

**Comment by pawelpasterz** [comment]
For reference: https://sentry.io/organizations/flank/issues/2335149051/?project=5514444&query=is%3Aunresolved

**Comment by maxbetton** [comment]
my config is :
`AndroidArgs
    gcloud:
      results-bucket: test-lab-qyczqs0khy7nk-n8u9a9i5hwzy2
      results-dir: 2021-05-13_01-34-30.767000_MYSl
      record-video: false
      timeout: 60m
      async: false
      client-details:
      network-profile: null
      results-history-name: null
      # Android gcloud
      app: /bitrise/src/Betclic/build/outputs/apk/frStub/debug/Betclic-fr-stub-debug.apk
      test: /bitrise/src/Betclic/build/outputs/apk/androidTest/frStub/debug/Betclic-fr-stub-debug-androidTest.apk
      additional-apks:
      auto-google-login: false
      use-orchestrator: false
      directories-to-pull:
        - /sdcard/Android/data/sport.android.[REDACTED].fr.qa/files/
      grant-permissions: all
      type: null
      other-files:
      scenario-numbers:
      scenario-labels:
      obb-files:
      obb-names:
      performance-metrics: false
      num-uniform-shards: null
      test-runner-class: null
      test-targets:
      robo-directives:
      robo-script: null
      device:
        - model: Nexus5
          version: 23
          locale: en
          orientation: portrait
        - model: Nexus5X
          version: 24
          locale: en
          orientation: portrait
        - model: Nexus6P
          version: 26
          locale: en
          orientation: portrait
        - model: NexusLowRes
          version: 27
          locale: en
          orientation: portrait
        - model: Pixel2
          version: 28
          locale: en
          orientation: portrait
        - model: Pixel2
          version: 29
          locale: en
          orientation: portrait
      num-flaky-test-attempts: 0
      test-targets-for-shard:
      fail-fast: false
    flank:
      max-test-shards: 1
      shard-time: -1
      num-test-runs: 1
      smart-flank-gcs-path: 
      smart-flank-disable-upload: false
      default-test-time: 120.0
      use-average-test-time-for-new-tests: false
      files-to-download:
        - .*/matrix*
      test-targets-always-run:
      disable-sharding: true
      project: [REDACTED]-sport-fr
      local-result-dir: results
      full-junit-result: false
      # Android Flank Yml
      keep-file-path: false
      additional-app-test-apks:
      run-timeout: -1
      legacy-junit-result: false
      ignore-failed-tests: false
      output-style: verbose
      disable-results-upload: false
      default-class-test-time: 240.0
      disable-usage-statistics: false
      output-report: none
      skip-config-validation: false
      custom-sharding-json: `

i have the problem about one week

**Comment by jan-gogo** [comment]
Closing due to no response to the question:

> do you see the same issue when using gcloud CLI?
