### ISSUE TITLE
Investigate Flank global state

### ISSUE THREAD

**Issue by jan-gogo** [Flank/flank#1974]
Prepare a list of global state occurrences in code.

The investigation results can be pasted as a comment to this issue.

**Comment by adamfilipow92** [comment]
Here are all the global states I have found.

- [```prettyPrint```](https://github.com/Flank/flank/blob/61aad5795f947ab8491be01104a0a046ec95cf9b/test_runner/src/main/kotlin/ftl/run/common/PrettyPrint.kt#L7)
- [```totalDurationStopWatch```](https://github.com/Flank/flank/blob/3a213579b0b8ed7ca018314f0619146408292b35/test_runner/src/main/kotlin/ftl/reports/DurationReport.kt#L9)
- [```outputReport = OutputReport()```](https://github.com/Flank/flank/blob/42b4be2ba11da457c5f48e52a01c1e9765a55169/test_runner/src/main/kotlin/ftl/reports/output/OutputReport.kt#L10)
- [```useMock = false```](https://github.com/Flank/flank/blob/9bf7b237d2787c82df8883f86106e67e03c1b8e4/test_runner/src/main/kotlin/ftl/config/FtlConstants.kt#L14)
- [```service: ToolResults by lazy```](https://github.com/Flank/flank/blob/d67016a6e7e7adb88743f200a4655eb696772191/test_runner/src/main/kotlin/ftl/client/google/GcToolResults.kt#L31)
- [```JSON_FACTORY: JsonFactory by lazy ```](https://github.com/Flank/flank/blob/9bf7b237d2787c82df8883f86106e67e03c1b8e4/test_runner/src/main/kotlin/ftl/config/FtlConstants.kt#L32)
- [```httpTransport```](https://github.com/Flank/flank/blob/9bf7b237d2787c82df8883f86106e67e03c1b8e4/test_runner/src/main/kotlin/ftl/config/FtlConstants.kt#L34)
- [```GcTesting```](https://github.com/Flank/flank/blob/d67016a6e7e7adb88743f200a4655eb696772191/test_runner/src/main/kotlin/ftl/client/google/GcTesting.kt#L9)
- [```yamlMapper: ObjectMapper by lazy```](https://github.com/Flank/flank/blob/9b780629bf5cf3e55f4d69ac9aa806a6949b811a/test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt#L46)
- [```configureCrashReporter```](https://github.com/Flank/flank/blob/0143dc15ca570482883d01f55d888d595cd115ca/test_runner/src/main/kotlin/ftl/util/CrashReporter.kt#L21)
- [```xmlPrettyWriter```](https://github.com/Flank/flank/blob/ba61ffa207ecde6094fd0f0caf2299d1e1f20ef8/test_runner/src/main/kotlin/ftl/client/junit/JUnitXml.kt#L21)
- [```service: ToolResults by lazy```](https://github.com/Flank/flank/blob/d67016a6e7e7adb88743f200a4655eb696772191/test_runner/src/main/kotlin/ftl/client/google/GcToolResults.kt#L31)
- [```storageOptions```](https://github.com/Flank/flank/blob/d67016a6e7e7adb88743f200a4655eb696772191/test_runner/src/main/kotlin/ftl/client/google/GcStorage.kt#L30)
- [```storage```](https://github.com/Flank/flank/blob/d67016a6e7e7adb88743f200a4655eb696772191/test_runner/src/main/kotlin/ftl/client/google/GcStorage.kt#L42)
- [```credential: GoogleCredentials```](https://github.com/Flank/flank/blob/60dd609cb728fdcda23f2ef58e4696b24ee50814/test_runner/src/main/kotlin/ftl/client/google/Credentials.kt#L16)
- [```httpCredential: HttpRequestInitializer by lazy```](https://github.com/Flank/flank/blob/60dd609cb728fdcda23f2ef58e4696b24ee50814/test_runner/src/main/kotlin/ftl/client/google/Credentials.kt#L48)
- [```messageBuilder, apiClient, objectMapper```](https://github.com/Flank/flank/blob/cabab70653271861b4f10fcb74f4ab33b1a31eae/test_runner/src/main/kotlin/ftl/analytics/UsageStatisticsClient.kt#L14)
