### ISSUE TITLE
Enable GPU support on all provisioned Android devices 

### ISSUE THREAD

**Issue by axelzuziak-gogo** [Flank/flank#1983]
Enable GPU support on all provisioned Android devices so that the pilot companies get the best possible performance.

https://github.com/corellium/corellium-api/commit/413858e03f48b77a8b05787f7a1ee565b00c380a

**Comment by jan-gogo** [comment]
# SDD

## Motivation

GPU acceleration is a valuable improvement if can speed up execution.

## Goal

Providing control over enabling/disabling GPU acceleration.

## Non-Goal

Converting the existing devices **without** into devices *with* GPU acceleration 

## API

* `cli` - `flank.corellium.cli.RunTestCorelliumAndroidCommand.Config.gpuAcceleration: Boolean` (`gpu-acceleration`) (default: false)
* `domain` - `flank.corellium.domain.RunTestCorelliumAndroid.Args.gpuAcceleration: Boolean`
* `api` - `flank.corellium.api.AndroidInstance.Config.gpuAcceleration: Boolean`

## Design

The flank is currently able to create or reuse the required amount of devices just before the test execution.
According to that, there is a simple way to implement partial support for this feature without extending or changing the current logic of device management. But solution design for the full support will require some additional investigation that will be explained later.

### Partial support

1. Add property to domain `Args`.
2. Add option to cli command `Config`.
3. Update `Config` -> `Args` mapper.
4. Add option to `AndroidInstance.Config` 
4. Pass added option in `flank.corellium.domain.run.test.android.step.invokeDevices`
5. Pass option to `Instance.BootOptions` in `flank.corellium.adapter.invokeAndroidDevices`

The drawback is the partial support doesn't update already created virtual devices for `gpu-acceleration` so it's required to remove devices manually before the running execution or run execution on a fresh project without created devices.

### Full support

Before implementing full support is important to make a decision what is the best way for managing the virtual devices for testing in the project scope which isn't a trivial problem. Specifining real use-cases and collecting requirements from the end-users will be extremely helpful. Explaining a complete solution for the full support is not in the scope of this document and should be treated as separated issue.
