### ISSUE TITLE
Research analytics tools suitable for Flank business metrics

### ISSUE THREAD

**Issue by axelzuziak-gogo** [Flank/flank#2012]
Research available analytics tools to measure business metrics. 
Some random examples: Google Analytics, Heap, Hotjar.

Please compare it with Mixpanel. Is Mixpanel suitable for tracking proposend metrics in #2011 ?

**Comment by bootstraponline** [comment]
I think mixpanel is good. https://github.com/Flank/flank/blob/master/docs/analytics_comparsion.md

**Comment by adamfilipow92** [comment]
I checked a mixpanel and yes it's fine. 
I prepared some reports according to #2011. You can check them [here](https://mixpanel.com/s/2PGbdG). The rest of the reports will be created in #2029. Currently Flank doesn't report some data to mixpanel like costs, test duration, and Flank version so this will be implemented in #2030

**Comment by axelzuziak-gogo** [comment]
OK, closing this ticket
