### ISSUE TITLE
Evergreen Flank

### ISSUE THREAD

**Issue by axelzuziak-gogo** [Flank/flank#2014]
> As no one updates Flank, the usefulness of the metrics depends on everyone running the latest Flank client.

One way to do that would be:
* Users download a small stub executable flank (ideally a native image compiled with https://www.graalvm.org/) that then fetches the latest stable download from GitHub releases and caches it. This is similar in spirit to how gradlew works.
* Another way would be building a shell script wrapper that downloads/invokes flank
* 3rd way would be having a client/server model, where we run a Flank server on GCP and maintain that logic independent of the client. This would position us for "flank as a service". Seems like a large effort though.
* Ideas

Motivation:
In addition for the customers, having an out of date Flank can be a problem when we're actively adding new features/functionality. The backends are always changing (firebase test lab, corellium) so users are more likely to get broken by an out of date Flank client than running on a new Flank client. For example when FTL changes the XML format, that's broken older flank clients that don't understand the new structure.

**Comment by piotradamczyk5** [comment]
Flank wrapper was delivered, so we could close this epic
