### ISSUE TITLE
Research "Evergreen Flank" solutions

### ISSUE THREAD

**Issue by axelzuziak-gogo** [Flank/flank#2015]
Goal of this issues is to research and propose solutions for "Evergreen Flank".

**Comment by piotradamczyk5** [comment]
# GrallVM( native image)

Users download a small stub executable `flank` (ideally a native image compiled with https://www.graalvm.org/) that then fetches the latest stable download from GitHub releases and caches it. This is similar in spirit to how `gradlew` works.



## Pros

- multiplatform solution out of the box
- smaller jar size

## Cons

- need to deliver special build ex. using [Gradle plugin](https://github.com/mike-neck/graalvm-native-image-plugin). To build it user/CI must have Graal VM installed
- if we change the script we must ship new version
- Additional logic for downloading flank version is needed



# Script

Shell script wrapper that downloads and invokes flank

## Pros

- very easy to develop

## Cons

- we need to deliver multiple scripts for different OS(Unix, Windows)



# Flank as a service

3rd way would be having a client/server model, where we run a Flank server on GCP and maintain that logic independent of the client.

## Pros

- best to manage
- scalable
- easy to charge potential customers
- Flank always up to date (no need to update script etc)

## Cons

- need additional infrastructure



# Docker image

Deploy docker image and execute Flank there

## Pros

- Easy to run on CI
- easy to deploy
- could be hosted in github

# Cons

- We need to manage docker image tags

- still we need to write a script to download latest version

**Comment by axelzuziak-gogo** [comment]
Thanks @piotradamczyk5.

**Comment by bootstraponline** [comment]
kotlin native might be worth thinking about, similar limitations to graalvm.

https://kotlinlang.org/docs/native-overview.html#sample-projects

**Comment by bootstraponline** [comment]
also found https://github.com/update4j/update4j

**Comment by bootstraponline** [comment]
more ideas: https://stackoverflow.com/questions/4002462/how-can-i-write-a-java-application-that-can-update-itself-at-runtime

**Comment by mordechaim** [comment]
@bootstraponline Thanks for tagging my project update4j 😊.

There are some 3rd party backports to jdk8 if you wish to check them out.

**Comment by bootstraponline** [comment]
nice! I'll let the team know

**Comment by bootstraponline** [comment]
Docker isn't going to work for this use case so I'm reopening the issue.
