### ISSUE TITLE
Parameterized Tests: Add new options #2

### ISSUE THREAD

**Issue by Sloox** [Flank/flank#2024]
**Author the user story for this feature**

Parameterized tests need options to help in sorting out the issues they might represent. 

**Describe the solution**
Two options should be added within the scope of this ticket namely
* `collect-all-multiple` -  All parameterized tests should be collected and sharded in a separate shards smartly.

This will require investigation as `some intelligent preprocessing of the AST is required and to figure out what the parameterized tests will expand to and shard what they expand out to into a separate shard`
It is important to know that according to @bootstraponline , ```In the long term I think we'll likely move to runtime discovery of tests in the new corellium backend. That should enable us to get a complete picture of what tests exist. Parsing out the info from bytecode has limitations.```

This should be applied only to android and an example of the API:

```
### Parameterized Tests
  ## Specifies how to handle tests which contain Parameterization.
  ## 4 options are available
  ## default: treat Parameterized tests as normal and shard accordingly
  ## ignore-all: Parameterized tests are ignored and not sharded
  ## collect-all-single: Parameterized tests are collected and put into a single shard
  ## collect-all-multiple: Smart collection of all the parameterized test and run separately on a per case basis
  ## Note: if left blank default is used.
  # parameterized-tests: default
```

Take note this will require tests & integration tests. Therefore an example parameterized test application needs to be built to accommodate this and test it thoroughly.

More information about the discussion is found here: https://github.com/Flank/flank/issues/1720

**Comment by jan-gogo** [comment]
Investigate if `collect-all-multiple` it is possible to implement.
