### ISSUE TITLE
Create Mixpanel board with business metrics

### ISSUE THREAD

**Issue by axelzuziak-gogo** [Flank/flank#2029]
Create board in Mixpanel containing business metrics defined in #2013.

**Comment by adamfilipow92** [comment]
TODO List

- [X] How many millions per month in spend is Flank responsible for on Firebase Test Lab? (track test time by device type to calculate)

- [X] What is the breakdown of Flank by version?

- [] How frequently do users upgrade from one version of Flank to another?

- [X] Who uses flank? (app ids)

- [X] What are the DAU (daily active users) and MAU (monthly active users)?

- [X] What is the churn? (people who use flank and then stop)

- [X] What is the Month-on-month (MoM) growth of flank?

- [] What is the LTV (Life Time Value) of a flank customer?
https://a16z.com/2015/08/21/16-metrics/
