### ISSUE TITLE
Flank can't find swift test methods from `final` test classes

### ISSUE THREAD

**Issue by manuyavuz** [Flank/flank#2070]
**Describe the bug**
> A clear and concise description of what the bug is.

If you for some reason label your test class as `final`, flank can't find it's test methods as it uses `nm -gU` to list symbols, which would only list global defined symbols.

**To Reproduce**
> Steps to reproduce the behavior:

1. Define a swift test class and mark it as `final`.
2. Build test products and run `flank ios run`
3. See that swift test cases are not found by flank.

**Expected behavior**
> A clear and concise description of what you expected to happen.

**Details (please complete the following information):**
> Have you tested on the latest Flank snapshot?
>
> Post the output of ` flank --version`.

**Additional context**
> Add any other context about the problem here.

I think removing `-g` option should be enough to get non-global methods too. This is already what has been used for ObjC test methods.

**Comment by manuyavuz** [comment]
I have found that only the `open` access level gives a global symbol, enabling flank to find the method. Others (including `public` and `internal`(default level)) do NOT give a global symbol, and flank can not find the test methods.

What I don't understand is the example swift test classes in flank that are used as artifacts in tests do not provide an access level. How does it actually work? Could this be an Xcode version-related issue? My Xcode version is `12.5.1`.

**Comment by bootstraponline** [comment]
The nm commands are based on bluepill.

https://github.com/MobileNativeFoundation/bluepill/blob/0e819600b8fe18e8da5868f986ff0ff0966e50ec/bp/src/BPXCTestFile.m#L18-L19

Sounds like we should drop the `g` flag on Swift. I'll discuss with the team.

**Comment by bootstraponline** [comment]
@manuyavuz If you manually run the `nm -gU` command manually from the terminal, are the tests displayed? Flank bundles a version of nm. It'd be helpful to know if the default nm binary is able to find these tests.

**Comment by manuyavuz** [comment]
@bootstraponline ok i think this will be something related to symbol hiding we do on Release configuration. Will post updates after my examination.

**Comment by manuyavuz** [comment]
@bootstraponline I think this should still be fixed as people might choose to make their test symbols non-global to save space and reduce visibility. Whereas with `nm -U` only, you would still get the available test results. We are not obfuscating or taking other destructive measures.

**Comment by bootstraponline** [comment]
I think that makes sense, we use `-U` anyway for objective C.

could you provide a simple reproducible test case? Then we can fix and add a unit test to flank. We have an existing iOS sample app. https://github.com/Flank/flank/tree/master/test_projects/ios

**Comment by manuyavuz** [comment]
Thank you!
