### ISSUE TITLE
Resolve Artifacts API limit exceeded

### ISSUE THREAD

**Issue by Sloox** [Flank/flank#2077]
**Describe the bug**
> A clear and concise description of what the bug is.

Github has severly throttled the amount of times we can make use of ResolveArtficats.
i.e. Downloaded the latest flank release multiple times.

The error message:
```
Exception in thread "main" java.lang.AssertionError: HTTP response status is not equal to 200:
403 rate limit exceeded [https://api.github.com/repos/Flank/test_artifacts/releases]
Date: Fri, 09 Jul 2021 09:59:21 GMT
Server: Varnish
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
*cookiestuff*
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 0
X-RateLimit-Reset: 1625825068
X-RateLimit-Resource: core
X-RateLimit-Used: 60
Content-Length: 280
X-GitHub-Request-Id: ****

{"message":"API rate limit exceeded for 79.184.217.131. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

```

**To Reproduce**
> Steps to reproduce the behavior:

1. Run 'resolveArtifacts gradle taskt 6+ times in a row.'
2. See error

**Additional context**
> Add any other context about the problem here.
I think the use of resolveArtifacts for every build is unnecessary. 
Commenting out the gradle task allows flank to proceed as usual.

It appears that a simple check to see if the Artifact is present on the system and not grossly out of date (i.e. check the file creation date and if older than lets say a week update) we dont waste time or bandwidth downloading it again.

**Comment by bootstraponline** [comment]
we should use a GitHub token, that'll greatly increase the API limits

GitHub's API is not reliable unless we're using a token

**Comment by Sloox** [comment]
This appeared due to the fact that GITHUB_TOKEN was not present on my machine.
