### ISSUE TITLE
Parse APKs in parallel

### ISSUE THREAD

**Issue by asadsalman** [Flank/flank#2120]
It would be great if Flank could parse APKs (and retrieve smart flank data for them) in parallel. In my testing pipeline, I test many APKs in one flank invocation. It's gotten to a point where parsing APKs is actually taking longer than executing them on FTL. This is, in part, because every APK is parsed serially.

**Describe the solution**
It would be great if flank could parse the APKs in parallel

**Comment by piotradamczyk5** [comment]
Hey @asadsalman 
We already do it in parallel, please check [code snippet](https://github.com/Flank/flank/blob/72a8cd14f15043e72298fea086bff16e4d3f1f18/test_runner/src/main/kotlin/ftl/run/platform/android/CreateAndroidTestContext.kt#L42-L52)

**Comment by axelzuziak-gogo** [comment]
Closing it.
