### ISSUE TITLE
Mixpanel: empty iOS app id

### ISSUE THREAD

**Issue by adamfilipow92** [Flank/flank#2130]
**Describe the bug**
> A clear and concise description of what the bug is.

In mixpanel, ios app id is empty

**To Reproduce**
> Steps to reproduce the behavior:

1. Open mixpanel
2. Go to the Users tab
3. Find users described in the slack message.
4. Find events with empty app id

**Expected behavior**
> A clear and concise description of what you expected to happen.

The issue occurs when flank reporting ios messages. We need to fix fetching app id from ios apps.

**Comment by adamvduke** [comment]
mixpanel integration has been removed
