### ISSUE TITLE
No Matrix output in logs

### ISSUE THREAD

**Issue by mariuszmachniakzendesk** [Flank/flank#2190]
Matrix table is not present in results. I'm able to fetch this by looking on MatrixResultsReport.txt file. But for CI like Github Actions it it is missing in the console log.

Steps to Reproduce:
1. Setup latest version of Flank and use flank.ios.yml with iPhone 11 Pro iOS 14.7
```
  device:
  - model: iphone11pro
    version: 14.7
    locale: en
    orientation: portrait
```
2. Run tests in Firebase using java -jar flank.jar firebase test iOS run

Output I see:
```
 5m 24s matrix-xyz FINISHED
FetchArtifacts
    Updating matrix file
CostReport
  Physical devices
    $....

  Uploading [CostReport.txt] to https://console.developers.google.com/s.....
  Uploading [MatrixResultsReport.txt] to https://console.developers.google.com/....
  Uploading [JUnitReport.xml] to https://console.developers.google.com/.....

WARNING: Matrix path not found in JSON.

  Uploading [matrix_ids.json] to https://console.developers.google.com/...

Matrices webLink
Actual shard times:
  Shard 0: Expected: 0s, Actual: 0s, Diff: 0s
7652
  Shard 1: ..........
  matrix-.......
Total run duration...
	- Preparation...
	- Scheduling tests:...
	- Executing matrices...
	- Generating reports:...
```

_Originally posted by @bootstraponline in https://github.com/Flank/flank/issues/2179#issuecomment-984760017_

**Comment by mariuszmachniakzendesk** [comment]
@bootstraponline do you have some plans when this could be fixed? Thx in advance!

**Comment by bootstraponline** [comment]
I hope to look at this soon, after the holidays! I've been busy working on getting long term funding for Flank.
