### ISSUE TITLE
CostReport as a structurized file like JSON, YAML, etc.

### ISSUE THREAD

**Issue by castus** [Flank/flank#2197]
**Author the user story for this feature**

As a developer, I want to have CostReport.txt file as a structurized file like JSON or YAML so I can parse it easily to get values that I need.

**Describe the solution**
Create for ex. JSON file with all the information:

```
{
  "total": 7.7,
  "currency": "USD",
  "tests": [
    {
      "type": "physical",
      "duration": 15,
      "cost": 7.3
    },
    {
      "type": "virtual",
      "duration": 5,
      "cost": 0.4
    }
  ]
}
```

**Describe alternatives considered**
Separate files to easily parse content. For ex.:
* file `virtual_cost.txt` with content "$0.3"
* file `virtual_duration.txt` with content "10"
* file `physical_cost.txt` with content "$1.1"
* file `physical_duration.txt` with content "15"

**Comment by bootstraponline** [comment]
@castus Hey, I agree this would be an awesome feature. I think JSON makes sense for this. If you'd like to submit a PR with tests, I'm happy to merge it. I think it wouldn't be too difficult to serialize the reports to JSON.

**Comment by castus** [comment]
I'll be happy to contribute. Do you have some document how to set up that project and possibily mock it?

**Comment by bootstraponline** [comment]
@castus we have onboarding docs https://flank.github.io/flank/onboarding/1_environment_setup/

IntelliJ works great. For mocking, checkout some of the existing tests.
