### ISSUE TITLE
Flank action should fail if there are test failures

### ISSUE THREAD

**Issue by adamvduke** [Flank/flank#2334]
According to @andreschab90, the flank action should fail if there are test failures. See https://github.com/Flank/flank/issues/2332 for more details.

Quoting from https://github.com/Flank/flank/issues/2332#issuecomment-1327548367:

* flank runs on ubuntu and all tests are passing -> step is marked as successful as expected
* flank runs on ubuntu and tests are failing -> step is marked as successful, but failed was expected
* flank runs on macOS and all tests are passing -> step is marked as successful
* flank runs on macOS and all tests are failing -> step is marked as successful, but failed was expected

so the issue is that the step is always successful now, even so tests were failing. IMO the step should fail when tests are failing

**Comment by andreschab90** [comment]
@adamvduke can be closed. works as expected. I had a config issue on my side. If a test fails, then step fails as well

**Comment by adamvduke** [comment]
Thanks for the update!
