### ISSUE TITLE
isRoboTest never set in matrix_ids.json for Robo Test matrices

### ISSUE THREAD

**Issue by AaronMT** [Flank/flank#2497]
Noticed in `matrix_ids.json` that `isRoboTest` is never set to `true` for Robo Test matrices as part of the `TestMatrix.Data` object.

We currently do result processing and parse through `matrix_ids.json` for data related to the matrice.

**Comment by SelaseKay** [comment]
Hi @AaronMT , I'm able to reproduce this issue. I'm looking into it.

**Comment by SelaseKay** [comment]
Hi @AaronMT, I'm pushing a fix for this issue.
