### ISSUE TITLE
flankAuth task is not compatible with configuration cache

### ISSUE THREAD

**Issue by qonto-android-team** [Flank/flank#2500]
**Describe the bug**
Running flankAuth with configuration cache enabled fails with the stack trace:

<img width="925" alt="image" src="https://github.com/Flank/flank/assets/87853987/0ab8aee5-8cbe-4780-8f7d-47902d82b0a3">

- Flank version: 23.10.1

**Comment by SelaseKay** [comment]
Hi @qonto-android-team, Do you experience this issue when you run `flank auth login`?
