### ISSUE TITLE
Fetch artifacts only from last run when using flakyTestAttempts

### ISSUE THREAD

**Issue by winterDroid** [Flank/flank#486]
It seems that the artifacts from all runs are fetched when using `flakyTestAttempts`. I guess that's not required and just the one from the last run would be enough.

**Comment by bootstraponline** [comment]
I think this is a duplicate of https://github.com/TestArmada/flank/issues/456

**Comment by winterDroid** [comment]
No I think the other is about the general result reporting, but this is about what should be fetched from gcloud to the local folder.

**Comment by bootstraponline** [comment]
The only artifacts auto fetched are the XML files. You can use a regex to grab anything additional.

I think we need all the XMLs to understand the test results.

**Comment by pawelpasterz** [comment]
@bootstraponline Could you give more input about this issue, what is expected result from this?
I am not sure if there is anything do since current implementation is as you described. Thanks!

**Comment by bootstraponline** [comment]
I think this issue should be closed.
