### ISSUE TITLE
support FTL beta commands

### ISSUE THREAD

**Issue by andreschab90** [Flank/flank#583]
we should support beta commands from firebase to also use some commands, which only exists for beta such as `client-details`

Background: Firebase just release cloud functions for the test lab, which also fetches client details. This could be useful for some notifications via firebase functions

**Comment by bootstraponline** [comment]
Status | Flag
--- | ---
✅ | --client-details=[KEY=VALUE,…]
✅ | --network-profile=PROFILE_ID
✅ |  --additional-apks=APK,[APK,…]
✅ | --other-files=DEVICE_PATH=FILE_PATH,[…]
✅ | --robo-script=ROBO_SCRIPT
✅ | --num-uniform-shards=int


## Skipped flags

- `--app=APP`
- `--scenario-numbers=int,[int,…]`
- `--test-targets-for-shard=TEST_TARGETS_FOR_SHARD`

**Comment by bootstraponline** [comment]
@jan-gogo Are there more beta flags to be added or is this ticket complete?

**Comment by jan-gogo** [comment]
> @jan-gogo Are there more beta flags to be added or is this ticket complete?

It's complete
