### ISSUE TITLE
Realtime streaming of test results via firebase function

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#588]
Prototype how to get firebase function streaming data to Flank.
- https://github.com/firebase/functions-samples/tree/master/quickstarts/test-complete

**Comment by doodla** [comment]
This might not be possible given the function will have to `push` ( `post` ) data to some place, and most CI systems don't allow incoming traffic.

**Comment by bootstraponline** [comment]
We're building a comprehensive build and test analytics platform that integrates with Flank. 😄 This is a research ticket that will help prove out those efforts.

Data will likely be pushed to a Firebase database.

**Comment by bootstraponline** [comment]
For test analytics, we'll parse the final JUnit XML artifact as attached to the CI job. In this approach, the firebase function doesn't add value.
