### ISSUE TITLE
HtmlErrorReport isn't rendering correctly.

### ISSUE THREAD

**Issue by tir38** [Flank/flank#591]
I'm not sure what this is supposed to look like but I don't think HtmlErrorReport.html is being generated correctly:

<img width="1280" alt="Screen Shot 2019-08-20 at 7 21 44 PM" src="https://user-images.githubusercontent.com/1980553/63391250-d3039100-c37f-11e9-9dd0-7ad9383e9b6b.png">

I'm happy to share the underlying html file. I tested this on both Chrome and Firefox.

**Comment by bootstraponline** [comment]
Yeah, that's definitely not correct. If you could share the HTML file, I can investigate. You can email me if you want to keep it private.

The Firebase team has a ticket for test sharding. 
- https://issuetracker.google.com/issues/115928363

When that support lands, all the shards will be on a single web link and then the Flank HTML report won't be required anymore. Until then, I'm maintaining the Flank HTML view as a simple way to view the test results. Bitrise had planned on modernizing the Flank HTML view, however that work was dropped.
