### ISSUE TITLE
Add ignoreFailures to Flank

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#602]
re: https://github.com/runningcode/fladle/issues/48

It seems there's a use case for ignoring the flank exit code. fladle failing will fail the build. In Jenkins, some users want to separate build failures from test failures. To do this, they rely on a Jenkins plugin to inspect the JUnit XML results.

![image](https://user-images.githubusercontent.com/1173057/65200053-e36c6180-da3a-11e9-8185-41311e611071.png)

Gradle supports providing control to the user over if test failures should break the build or not.

**Comment by bootstraponline** [comment]
```
afterEvaluate {
  tasks.named("execFlank", JavaExec::class.java).configure {
    isIgnoreExitValue = true
  }
}
```

https://github.com/runningcode/fladle/issues/48#issuecomment-533007002

It looks like there's a work around in Gradle.

**Comment by bootstraponline** [comment]
We should probably add ignoreExitValue to Flank.

- https://github.com/runningcode/fladle/issues/48#issuecomment-607041919

**Comment by gildor** [comment]
But this ignoreFailures should be more like ignoreFailedTests. So it should exit with 0 only if tests results are successfully retrieved from Firebase

**Comment by bootstraponline** [comment]
> But this ignoreFailures should be more like ignoreFailedTests. So it should exit with 0 only if tests results are successfully retrieved from Firebase

I agree, that's a great point. `ignoreFailedTests` makes sense.
