### ISSUE TITLE
Android Hypershard example

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#606]
Provide an example of using Hypershard for companies that are unable to use dex parsing on Android.

- https://github.com/dropbox/hypershard-android

The example should be described step by step in the markdown document.

**Comment by bootstraponline** [comment]
Here's an example of how ktfmt parses kotlin code:

- https://github.com/facebookincubator/ktfmt/blob/59f7ad8d1fde08f3402a013571c9997316083ebf/core/src/main/java/com/facebook/ktfmt/Parser.kt#L37

**Comment by jan-gogo** [comment]
https://github.com/dropbox/hypershard-android/issues/17 is this related issue?

**Comment by bootstraponline** [comment]
> [dropbox/hypershard-android#17](https://github.com/dropbox/hypershard-android/issues/17) is this related issue?

yes
