### ISSUE TITLE
Flaky test attempt results are unclear

### ISSUE THREAD

**Issue by RainNapper** [Flank/flank#619]
Vocabulary:
Just to make sure everything is on the same page, imagine a scenario where you run a two tests on two devices, with --num-flaky-test-attempts=3.

Each test is run in an `Execution`
Each `Execution` contains two `Environment`s, one per device.
Within each `Environment`, there are either 1 or 4 `Step`s, one for the initial run, and 3 for the flaky retries if the initial run failed.

Scenario:
1. Kick off a known flaky with `--num-flaky-test-attempts=3`
2. Test initially fails, and at least 1 of the 3 retries pass

Expected:
- JUnitReport.xml should show something like 1/3 runs passed, or flaky=true
- Optionally show results of every attempt

Actual:
- Test shows as success, with no indication that there were retries
- You do see attempts in `shard_0/environment-rerun_X`, but there is no summary of the conclusion from these attempts.
- https://github.com/TestArmada/flank/blob/master/test_runner/src/main/kotlin/ftl/json/SavedMatrix.kt#L109 shows that flank has logic to treat flaky tests as successes. However, this is irrelevant to the above issue, because this is the `Execution` level summary, not the `Environment` level summary. FTL reportedly does not support a 'flaky' outcome for an `Execution`.

Thoughts:
- The FTL webapp summarizes the `Execution` at an `Environment` level. Each outcome (pass, fail, flaky, inconclusive, etc.) is counted per `Environment`. See the attached picture.
![Screen Shot 2019-11-22 at 11 36 15 AM](https://user-images.githubusercontent.com/1449656/69455029-584e6700-0d1c-11ea-9c65-754e277ffd7a.png)
- Flank output should mirror the FTL console output.
- One could maintain their own implementation of the environment grouping logic that exists on the FTL webapp. You try to group each `Step` into an `Environment`, then determine on your own if a test was flaky.
- (Preferred) The FTL API could provide a way of grouping the individual test runs by environment, along with a high level summary of the tests within that environment (e.g. flaky, passed 2/5 times, passed, failed). Essentially, an API that surfaces the same summary that is present on the webapp.

Notes:
- FTL is reportedly releasing an environment level API in the near future, which may accomplish some of this. Flank would then need to adapt some of these new APIs into the test results logic (allegedly 1-2 weeks from now). This would save some implementation work and reduce the risk of having duplicate implementations of the execution summary.

**Comment by pawelpasterz** [comment]
@bootstraponline 
With new API based approach we have info about flakiness. Let me know if this meets requirements.
```
<testsuites>
  <testsuite name="NexusLowRes-28-en-portrait" tests="2" failures="0" flakes="1" errors="0" skipped="0" time="4.960" timestamp="2020-04-15T20:28:27">
    <testcase name="test2" classname="com.example.test_app.InstrumentedTest" time="2.581" flaky="true">
```

**Comment by bootstraponline** [comment]
That looks great. Thank you!
