### ISSUE TITLE
Access controls

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#622]
👋 @aktang @anmolvj @archlichking @cgdibble @chiahrens @chrisunder @jarzuaga @tobrien @VtoCorleone

I'm unable to merge PRs. I reached out to my contact at Walmart and it appears he no longer works there. If you can help restore my owner permissions to Flank, that'd be great.

Thanks!

**Comment by sridhar-vadlamani-ck** [comment]
This can be closed. :)

**Comment by bootstraponline** [comment]
Thanks! Yeah, Flank is owned by me now. 😂
