### ISSUE TITLE
Verify flank is setting the flaky outcome correctly

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#626]
rollUp should be reported flaky

> --test-targets-for-shard
> --num-flaky-test-attempts

https://firebase-community.slack.com/archives/C72V6UW8M/p1578091916016600?thread_ts=1574373049.028000&cid=C72V6UW8M

**Comment by pawelpasterz** [comment]
@bootstraponline 
I think with new API based approach we have info about flakiness (if that was the case here).  Let me know, thanks!
```
<testsuites>
  <testsuite name="NexusLowRes-28-en-portrait" tests="2" failures="0" flakes="2" errors="0" skipped="0" time="5.276" timestamp="2020-04-17T13:14:40">
    <testcase name="test1" classname="com.example.test_app.InstrumentedTest" time="2.601" flaky="true">
```
The same applies to #619
