### ISSUE TITLE
Default test run time is too low

### ISSUE THREAD

**Issue by RainNapper** [Flank/flank#632]
### Context
- Enable smart flank
- Set a reasonable test run timeout (e.g. 5m, not 1h)
- Set a shard time below the timeout (e.g. 2m)
- Add a bunch of tests to the test suite

When new tests are discovered (miss in the smart flank cache), [they default to a 10.0 sec runtime.](https://github.com/Flank/flank/blob/d872f9514616b6c9cb137fa9c7215bde76b4cc54/test_runner/src/main/kotlin/ftl/shard/Shard.kt#L69)

### Problem
This presents an issue when too many tests get put into a single shard.
For example, say your tests on average run in 60 seconds. A shard time of 2m should mean you  will have about 2 tests per shard, with 3 minutes of buffer time in case your tests run longer than usual.

If you add 12 tests to your suite, all 12 of these tests will not be found my smart flank, and default to 10 seconds. It is very possible that 12 of the new tests will be placed in a single shard (12 * 10 = 120 = shard time). This now puts your expected run-time at 12 minutes, which will very likely time-out the suite.

To make matters worse, Firebase gives fairly cryptic errors in this scenario:
A few examples:
`Test run failed to complete. Expected 10 tests, received 4`
`java.lang.IllegalStateException: UiAutomation not connected!`
`java.lang.RuntimeException: androidx.test.services.shellexecutor.ClientNotConnected`

### Proposal
Option 1 - Make the 10 second default significantly higher (2-5m)
Having an over-estimated default means that we err on the side of too many shards rather than too few. This effectively trades cost for stability. Enabling smart flank will mitigate this cost.

Option 2 - Add an input param to specify this default, e.g. `--test-run-time-estimate`, to allow users  to choose if they want to prefer cost vs stability with a high vs low value.

**Comment by pawelpasterz** [comment]
Resolved by #635
