### ISSUE TITLE
Flank logs

### ISSUE THREAD

**Issue by mariuszmachniakzendesk** [Flank/flank#634]
Hi Guys,
Flank used to produce a log file from the Firebase execution. That was very useful to get more details like: which shard executed which test, or getting which specific tests had retries.
Right now in the latest version I cannot find a log file. Neither a possibility to see which tests had retries. Is this something that can be achieved?

**Comment by bootstraponline** [comment]
Do you have an example of the old log file? What version of Flank was this?

**Comment by mariuszmachniakzendesk** [comment]
That was in quite an old version v.2. I don't have any file I can easily share here.

**Comment by bootstraponline** [comment]
Ok, there are two changes on the Flank roadmap that will help with this.

* We're moving to Firebase's new server side sharding 
* A new JUnit XML will contain more details about the run

Once that's ready, try again and see if this is still an issue.

**Comment by mariuszmachniakzendesk** [comment]
@bootstraponline thx for the info! Do you know when that likely to be available?

**Comment by bootstraponline** [comment]
I'm in the process of finding an engineering resource to work on Flank. I don't have a specific timeline. We use Flank at Robinhood and are interested in making it better. 🙂

**Comment by bootstraponline** [comment]
Flank has server side sharding support on master. We're actively working on updating the junit xml. The junit xml will be the source of truth for what happened during a run.

FTL has worked on updating the JUnit XML to contain additional metadata (such as flaky tests).
