### ISSUE TITLE
GraalVM

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#651]
See if Flank can be shipped as a native binary via GraalVM

- https://github.com/remkop/picocli/releases/tag/v4.2.0
- https://picocli.info/picocli-on-graalvm.html
- https://github.com/remkop/picocli/blob/master/picocli-codegen/README.adoc

https://github.com/oracle/graal

**Comment by bootstraponline** [comment]
> Added support for compiling classes with irreducible loops in the bytecode. These often occur in Kotlin applications using coroutines with loops. The support both improves performance of such applications and enables their ahead-of-time compilation.
> https://www.graalvm.org/docs/release-notes/20_1/#2010

**Comment by Sloox** [comment]
Some more research is found at: https://github.com/Flank/flank/issues/1062

**Comment by bootstraponline** [comment]
Thanks! Based on the research, I think graalvm is too early for us to use. This matches my earlier findings as well. We’ll probably check back in a year.

**Comment by Sloox** [comment]
Agreed even though there has been some progress on their side I don't think it is the time right now
