### ISSUE TITLE
How to get more details when apk validation fails?

### ISSUE THREAD

**Issue by elihart** [Flank/flank#660]
Using Flank for Android, when I start my tests the Firebase matrix fails with `Error: Internal error during validation`. This is printed out via flanks output, but there doesn't seem to be anyway to get more details about the error.

I know this is on the Firebase side, but is there anything I can do to get more information about what the problem is?

Thanks!

**Comment by bootstraponline** [comment]
I've posted this question in #test-lab on the Firebase Test Lab Slack. If FTL exposes details in the API, then we can update this in Flank. Unfortunately FTL server is generating this message so it's up to Google to send back the reason why validation failed. The validation is entirely server side. I'll let you know if they respond!

Thanks for opening an issue.

**Comment by elihart** [comment]
Thanks for the assistance and passing on the question to #test-lab.

I thought that would be the case, but figured it'd be good to have a record of this documented for others too.
