### ISSUE TITLE
Flank Test Lab session triggered from CI is not cancelled when the CI job is cancelled

### ISSUE THREAD

**Issue by julianD77** [Flank/flank#665]
We are running Flank v8.1.0 from jobs on our BuildKite CI.

 We have noticed that when a CI build job is cancelled whilst a flank session is running the Test Lab test execution is not cancelled and continues to run, thereby incurring unexpected costs.

Is there something we need to do to ensure that cancelling a job ensure that the Firebase Test Lab execution is also cancelled? Thanks in advance.

Launching the Flank session using:

`java -jar flank.jar firebase test android run`

Flank output on launch 

>   | gcloud:
>   | results-bucket: cloud-test-xxx-ed09d
>   | results-dir: null
>   | record-video: false
>   | timeout: 30m
>   | async: false
>   | results-history-name: android-xxx-flank
>   | # Android gcloud
>   | app: /workdir/example/flank/app-debug.apk
>   | test: /workdir/example/flank/app-debug-androidTest.apk
>   | auto-google-login: false
>   | use-orchestrator: true
>   | directories-to-pull:
>   | - /sdcard/
>   | performance-metrics: false
>   | test-runner-class: null
>   | test-targets:
>   |  
>   | device:
>   | - model: Nexus9
>   | version: 25
>   | locale: en
>   | orientation: portrait
>   | - model: Pixel2
>   | version: 29
>   | locale: en
>   | orientation: portrait
>   | - model: m0
>   | version: 18
>   | locale: en
>   | orientation: portrait
>   | num-flaky-test-attempts: 0
>   |  
>   | flank:
>   | max-test-shards: 6
>   | shard-time: -1
>   | num-test-runs: 1
>   | smart-flank-gcs-path:
>   | smart-flank-disable-upload: false
>   | files-to-download:
>   | - .*\.xml$
>   | - .*\.html$
>   | test-targets-always-run:
>   |  
>   | disable-sharding: false
>   | project: xxx-ed09d
>   | local-result-dir: results
>   | # Android Flank Yml
>   | keep-file-path: false
>   | additional-app-test-apks:

**Comment by bootstraponline** [comment]
> Is there something we need to do to ensure that cancelling a job ensure that the Firebase Test Lab execution is also cancelled?

`flank cancel` will cancel a run. Flank issues HTTP requests to FTL. If the Flank process dies, then FTL never gets a cancel message and the matrices will continue execution.

**Comment by elihart** [comment]
Thank you for this @bootstraponline. I have been wondering the same thing and figured it wasn't possible, it would be nice to have this in the readme :)

**Comment by bootstraponline** [comment]
@elihart I will happily merge a pull request to update the readme. :)
