### ISSUE TITLE
Update Fladle to support all the new Flank flags

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#710]
https://github.com/runningcode/fladle

**Comment by pawelpasterz** [comment]
https://github.com/runningcode/fladle/pull/88 
cc @bootstraponline

**Comment by pawelpasterz** [comment]
@bootstraponline 
According to https://github.com/runningcode/fladle/pull/88#pullrequestreview-394115444 . PR will be merged once new stable version of flank is released. In the mean time, I will keep this PR updated.

**Comment by bootstraponline** [comment]
Sounds great. We are targeting a May 15 release date for the new stable version.
