### ISSUE TITLE
Print retries in Flank so that the user knows what's happening

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#717]
As reported in #flank on FTL Slack.

> [task 2020-04-13T20:47:55.150Z]   5m 43s matrix-3ru2up8r1oh9z Pixel2-28 FINISHED
> [task 2020-04-13T20:50:31.384Z]   8m 20s matrix-3ru2up8r1oh9z FINISHED

We should print to stdout on each retry.

**Comment by pawelpasterz** [comment]
[DEV INFO]
Flank now uses FTL server side sharding (for android). We need to verify if FTL sends us info about retrying.
