### ISSUE TITLE
Flank Refactor

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#718]
Refactor proposal from yaneq (copied from Slack)

1. ~~Building simple config data class from cli and config file which will be a context for next step.~~
1. ~~Validating config data class~~
1. ~~Building domain structures which should explicitly specify how to create test matrices.~~
1. ~~Uploading all required files asynchronously and updating file references in domain structures.~~
1. ~~Building and running gc test matrices from domain structures.~~
1. ~~Pooling results.~~
1. ~~Generating reports.~~ (Partially finished)

Of course flank now fulfills those steps but there are not fully visible at first look, and some of responsibilities are mixed.

Additionally:
- We should avoid operations on mutable data.
- All gc operations can be hidden behind interfaces
- We should use Displatchers.IO only in gc api layer.
- Because flank's run has relatively simple lifecycle, we should avoid OOP, and rely on functions and structures. As Edsger Dijkstra said: "Object-oriented programming is an exceptionally bad idea", I am fully agreed with this :).

**Comment by runningcode** [comment]
Can we maintain the current API and outputs of Flank? I worry a refactor would change these and therefore leave certain projects behind which rely on the API and outputs of flank and are unable to migrate.

**Comment by bootstraponline** [comment]
> Can we maintain the current API and outputs of Flank?

I agree, I see this as an internal refactor. We should make sure to maintain the current outputs and not break [fladle](https://github.com/runningcode/fladle)
