### ISSUE TITLE
Create issue template for Flank

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#736]
Ask to always test on latest snapshot
https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository

**Comment by jan-gogo** [comment]
@bootstraponline I need settings permission to resolve this ticket

**Comment by bootstraponline** [comment]
@jan-gogo you should be able to manage all the issues in this repo. I verified you have permission. Are you getting an error message? Have you tried logging out/logging back in?

**Comment by bootstraponline** [comment]
@jan-gogo I upgraded you to maintainer, try now.

**Comment by bootstraponline** [comment]
Fixed in https://github.com/Flank/flank/commit/0d8cfa43c6663977059ada54a4da1447eb3967c2
