### ISSUE TITLE
Print the version of Flank on each test run

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#740]
Users often have no idea what version of Flank they're using. It'd be helpful if each Flank execution printed the current version of flank to stdout before running the tests.

Update Flank to always print a version (instead of the current unknown for local builds)

**Comment by jan-gogo** [comment]
@bootstraponline 

I can handle that but I have two questions first.

1. Which version should be print for snapshot. `SNAPSHOT` will be enough? Or `8.2.0-SNAPSHOT` (if next version is 8.2.0). 

2. Question is about `revision`. The [comment](https://github.com/Flank/flank/blob/master/test_runner/src/main/kotlin/ftl/util/Utils.kt#L105.) suggests that may be commit revision (`git rev-parse HEAD`) if so, I have no idea how to update `revision.txt` without creating another commit with different revision and more how to do that automatically on github using `Squash and merge` button.

**Comment by bootstraponline** [comment]
>java -jar flank.jar --version
>flank_snapshot
>8ae4f2b7857640eb46825da5164c2cc0c2828889

^ That's what snapshot currently prints when built on bitrise. Locally we only see unknowns. Ideally local builds would display the same information.

Yes, revision is the git revision. We can fetch this via `git status`

The idea is if a user builds flank locally, there should be some useful information in the version and revision output. 

In CI, bitrise automatically populates this for us.

**Comment by jan-gogo** [comment]
Ok, so locally the revision can by updated automatically by gradle task. I can handle that
