### ISSUE TITLE
50 Shard limit in flank snapshot

### ISSUE THREAD

**Issue by runningcode** [Flank/flank#744]
We need close to 100 shards to meet the shard-time = 120 seconds. We currently use flank with max-test-shards set to 200. This works fine in 8.1.0.

In the flank snapshot i'm seeing this error:
`max-test-shards must be >= 1 and <= 50, or -1. But current is 200`

Is there a reason this limitation was introduced in the flank snapshot?

**Comment by pawelpasterz** [comment]
Flank currently uses server side sharding. That is limitation forced by FTL api
https://cloud.google.com/sdk/gcloud/reference/alpha/firebase/test/android/run#--test-targets-for-shard

**Comment by runningcode** [comment]
Will the new version of flank support multiple matrices?

**Comment by bootstraponline** [comment]
I think we should push FTL to increase the server side limit.

Ideal for Flank is there's only one matrix. Flakiness and instability comes with having multiple matrices in a test run.

**Comment by bootstraponline** [comment]
If FTL won't increase the 50 limit then Flank can work around this by supporting multiple matrices.

**Comment by bootstraponline** [comment]
I started a thread here: https://firebase-community.slack.com/archives/C1MTSQ5QT/p1588025464344800

I think the best solution is for FTL to increase the arbitrary limit of 50. Feel free to share your feedback there as well.
