### ISSUE TITLE
Test filters fail with Additional Test Apks

### ISSUE THREAD

**Issue by runningcode** [Flank/flank#745]
When using test filters and additional test apks:
If we use a filter which only matches tests in the instrumentation test apk but matches 0 tests in an additional test apk, flank will fail with:
`All tests filtered out`

Is this the expected result? In 8.1.0 flank would run successfully. In the current flank snapshot this fails in the above manner. What is the expected behavior?

**Comment by pawelpasterz** [comment]
Filters are used to match tests in each apk-test pair separately. If pair has all tests filtered out flank run terminated. Looks like we are missing that case you mentioned. Thanks for reporting that!

cc @bootstraponline

**Comment by bootstraponline** [comment]
We should probably ignore when there are zero tests in a particular APK instead of erroring.  https://github.com/Flank/flank/issues/739 is a related bug.Thanks for reporting!
