### ISSUE TITLE
Consider adding a .editorconfig file for external contributors

### ISSUE THREAD

**Issue by fondesa** [Flank/flank#747]
I contributed for the first time some days ago and I had to adjust some settings manually to match some rules defined in the `detekt` config to be able to reformat automatically the code (e.g. on IntelliJ by default is with `CMD + ALT + L`).

Obviously `./gradlew check` on the CI detects anyway an incorrect format so currently there isn't any risk by a contributor to use a different code style. 

The `.editorconfig` would be useful in two cases:
- first time contributors won't need to adjust settings manually to match the detekt basic configs
- if one day the code style of this repo changes (e.g. 2 spaces indent), all the contributors will be automatically aligned without changing their settings again

Consider adding a `.editorconfig` for external contributors so they won't need to adjust the basic settings for this project manually.

**e.g.** https://github.com/fondesa/kpermissions/blob/master/.editorconfig

**Comment by bootstraponline** [comment]
I think detekt has a gradle task that updates your IntelliJ idea settings to match the linter.

**Comment by fondesa** [comment]
Oh, I didn't know it, which is it?

I see the following `detekt` tasks:

```
detekt
detektBaseline - Creates a detekt baseline on the given --baseline path.
detektGenerateConfig - Generate a detekt configuration file inside your project.
detektIdeaFormat - Uses an external idea installation to format your code.
detektIdeaInspect - Uses an external idea installation to inspect your code.
detektMain - EXPERIMENTAL & SLOW: Run detekt analysis for main classes with type resolution
detektTest - EXPERIMENTAL & SLOW: Run detekt analysis for test classes with type resolution
```
I tried them all but none of them had the desired result.

**Comment by bootstraponline** [comment]
Oh, I thought there was a task for this. It may have been replaced.

https://github.com/detekt/detekt-intellij-plugin should allow you to use the detekt config that's already in the repo.

https://github.com/Flank/flank/blob/master/config/detekt.yml

**Comment by fondesa** [comment]
It still doesn't work, but in case, it's something on `detekt` side, not on `Flank` ones. Feel free to close this issue. Thanks.
