### ISSUE TITLE
Automatically store reports in gcloud bucket

### ISSUE THREAD

**Issue by runningcode** [Flank/flank#750]
It would be nice to automatically store the results in the gcloud bucket.

Specifically the html report and the junit xml report.

**Comment by pawelpasterz** [comment]
Do we also want to have possibility to disable this option?

**Comment by adamfilipow92** [comment]
> Do we also want to have possibility to disable this option?

In my opinion we should have possibility to disable it.

**Comment by bootstraponline** [comment]
I think by default we should upload the reports. An option to disable this makes sense.
