### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by digitalbuddha** [Flank/flank#762]
Howdy! Thank you for the delightful library. Would it be possible to do a new stable release? We use flank through fladle which depends on stable versions. Specifically I am looking for the robot test support. Thank you and have a nice day.

**Comment by bootstraponline** [comment]
![image](https://user-images.githubusercontent.com/1173057/80932638-2d5d4a00-8d75-11ea-85cb-50425f92fc7a.png)

Hey, thanks for the positive feedback! We are planning a stable release on May 15. This will also include a new release of Fladle. Flade is being updated [with all the new flags](https://github.com/runningcode/fladle/pull/88).

Robinhood also uses Flank via Fladle and we're eager for a new stable release.

**Comment by runningcode** [comment]
Would it help to release a version of Fladle to help with testing? I just need to check for backward compatibility if it helps.
Also is there a chance of a release candidate version of Flank before the final release?

**Comment by bootstraponline** [comment]
> Also is there a chance of a release candidate version of Flank before the final release?

That's an interesting idea. I think we could consider it for the future. I'm pretty confident the current state of flank isn't RC ready. We will be soon though.

**Comment by bootstraponline** [comment]
https://github.com/Flank/flank/releases/tag/v20.05.0
