### ISSUE TITLE
Crash on XML parsing

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#764]
Posted by Andrey Mischenko on Slack. Flank version unknown.

https://firebase-community.slack.com/archives/C1MTSQ5QT/p1588569925404500

We got invalid XML on one of our tests from test lab, it’s because Firebase converts some characters in failure message to html entities, which is invalid XML, which cause fails of our CI when try to get results
Invalid XML looks like:

```
<testcase name="test_name" classname="some.class.Name" time="23.194">
    <failure>java.net.ConnectException: Failed to connect to ... at &#8;&#8;&#8;(Coroutine boundary.&#8;(&#8;)
```

In original message we do not have html entities, just UTF character for Backspace https://unicode-table.com/en/0008/

I think it will be solved if Firebase will not encode html entities, or encode it using xml encoding using <!Entity> tag, or just replace &  with &amp;  it will not be perfect, but better than broken xml parsing (edited)

**Comment by gildor** [comment]
It's not a bug of Flank itself. Of course, Flank may fix it by sanitizing XML before attempt to parse it, but not sure that it worth it. But it's a very unfortunate bug of Firebase

**Comment by bootstraponline** [comment]
I think we should preprocess the XML before parsing. Flank is use to working around weird FTL bugs. 😄

**Comment by gildor** [comment]
> Flank version unknown
It's reproducible for me on `flankVersion = "8.1.0"`, also it causes infinite hanging of test execution:

`test_firebase_testlab - #459 Aborted after 3 days 20 hr` 😬

**Comment by bootstraponline** [comment]
I think the infinite hang is fixed but I'm not sure we fixed the XML parsing crash.

**Comment by gildor** [comment]
Yes, I meant that hang is fixed

**Comment by pawelpasterz** [comment]
> `test_firebase_testlab - #459 Aborted after 3 days 20 hr` 😬

Oh mann....
