### ISSUE TITLE
Convert Flank | Ubuntu Public to GitHub Actions

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#768]
Convert the Bitrise `Flank | Ubuntu Public` build to run on GitHub actions.

Use `ubuntu-latest`

https://app.bitrise.io/app/fbdede5ce50cbc21#/builds

**Comment by piotradamczyk5** [comment]
Issue with custom problem about GitHub action environment will be reported. Waiting for response

**Comment by bootstraponline** [comment]
- [branch](https://github.com/Flank/flank/tree/%23768-bitrise-ubuntu-workflow-into-github-actions)
- [github actions workflow](https://github.com/Flank/flank/actions?query=workflow%3Aubuntu-workflow)

**Comment by bootstraponline** [comment]
@piotradamczyk5 feedback from GitHub support:

> Could you try updating to actions/cache@v2 to see if that resolves the issue?
> 
> https://github.com/Flank/flank/actions/runs/114965577/workflow#L29
> https://help.github.com/en/actions/language-and-framework-guides/building-and-testing-java-with-gradle#caching-dependencies

**Comment by piotradamczyk5** [comment]
> @piotradamczyk5 feedback from GitHub support:
> 
> > Could you try updating to actions/cache@v2 to see if that resolves the issue?
> > 
> > * https://github.com/Flank/flank/actions/runs/114965577/workflow#L29
> > * https://help.github.com/en/actions/language-and-framework-guides/building-and-testing-java-with-gradle#caching-dependencies

Still same issue
https://github.com/Flank/flank/runs/749221640?check_suite_focus=true
