### ISSUE TITLE
Downloading the flank jars from releases in Github seems to return 403

### ISSUE THREAD

**Issue by narenkmanoharan** [Flank/flank#773]
We have a task to download the flank jar from github releases in our build and looks like it seems to be getting 403s now.

```
Execution failed for task ':app:downloadFlank'.

> de.undercouch.gradle.tasks.download.org.apache.http.client.ClientProtocolException: Forbidden (HTTP status code: 403, URL: https://github.com/TestArmada/flank/releases/download/v8.0.1/flank.jar)

```

If i manually click on any jar on the releases, i get a "SignatureDoesNotMatch" error on AWS.

![image](https://user-images.githubusercontent.com/9508432/81350933-f1c5c700-9077-11ea-839c-0290884943fe.png)

Let me know if you need any other info. Thanks!

**Comment by bootstraponline** [comment]
https://github.com/TestArmada/flank/releases/download/v8.0.1/flank.jar should be working again.

GitHub had an outage.

**Comment by bootstraponline** [comment]
Also FYI the new URL is https://github.com/Flank/flank/releases/download/v8.0.1/flank.jar since we graduated to a top level org. You might want to update your scripts. 🙂

**Comment by narenkmanoharan** [comment]
Thanks!
