### ISSUE TITLE
Flank 20.05.1 is not available on maven central.

### ISSUE THREAD

**Issue by runningcode** [Flank/flank#782]
20.05.0 is available. just not 20.05.1
https://mvnrepository.com/artifact/com.github.flank/flank

**Comment by bootstraponline** [comment]
https://github.com/jfrog/jfrog-cli/pull/690

jfrog cli doesn't support auto sync, we're contributing this upstream. Until then I have to manually push the button.

**Comment by bootstraponline** [comment]
20.05.1 should be on maven central now.
