### ISSUE TITLE
Does `--dump-shards` take in to account additional-app-test-apks?

### ISSUE THREAD

**Issue by runningcode** [Flank/flank#791]
I'm running `--dump-shards` on this branch
https://github.com/runningcode/fladle/tree/no/configure-root

I have several different Instrumented tests in different modules, but when I run `--dump-shards`, I only see 
```
[
  [
    "class com.osacky.flank.gradle.sample.ExampleInstrumentedTest#runAndFail",
    "class com.osacky.flank.gradle.sample.ExampleInstrumentedTest#seeView"
  ]
]
```
That is, I only see the instrumented tests from the main apk.

Is there documentation on `--dump-shards`? Does it also take in to account `test-targets`?

Thanks.

**Comment by bootstraponline** [comment]
Oh, that's a good point. I think it only works on the main apk right now. We should fix this.

**Comment by bootstraponline** [comment]
dump-shards should take into account test-targets, however I'm not sure if we support `additional-app-test-apks` with dump-shards.
