### ISSUE TITLE
Print messages by stdout

### ISSUE THREAD

**Issue by adamfilipow92** [Flank/flank#797]
Other thing, that just came to my mind, if we should stop using `System.err` to print messages. I am wondering if we should stick to stdout. Since it is CLI app user would by default redirect stderr somewhere else. Just thinking, what do you think?

_Originally posted by @pawelpasterz in https://github.com/Flank/flank/pull/795_

**Comment by pawelpasterz** [comment]
@bootstraponline WDYT?

**Comment by bootstraponline** [comment]
@pawelpasterz Can we do some research on stdout vs stderr? There might be a valid use case. 

> That's actually just what I wanted: I saw the errors printed to the console but all of the matched output was sent to the file. In the time of Unix v6 both the errors AND the output would have been sent to the file, which I would have needed to clean up manually. Woohoo for stderr.
https://www.jstorimer.com/blogs/workingwithcode/7766119-when-to-use-stderr-instead-of-stdout

> When redirecting output from an application using the ">" symbol, error messages still print to the screen. This is because error messages are often sent to the Standard Error stream instead of the Standard Out stream.
>
> https://support.microsoft.com/en-us/help/110930/redirecting-error-messages-from-command-prompt-stderr-stdout

**Comment by pawelpasterz** [comment]
To be resolved in #803
