### ISSUE TITLE
Super sharding

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#804]
Blocked on: https://github.com/Flank/flank/issues/718

Let's complete the refactor before working on this ticket. 

Flank is a massively parallel test runner. 50 does not sound very massive.

> The number of shards specified must be >= 1 and <= 50.
> https://cloud.google.com/sdk/gcloud/reference/alpha/firebase/test/android/run

We could consider building an advanced feature on top of server side sharding. This would detect when we are above the server side sharding limit, and make a new matrix. A set of 100 shards would be broken down into two matrices of 50 shards.

This might complicate the JUnit XML merging, however this would unlock truly limitless sharding. Some other features may break as well. Thought will have to be put into the design to see what would break in this new execution mode.

**Comment by pawelpasterz** [comment]
As sharding limits will change in the near future (up to 250) and may probably again in the future we should consider implementation that will be independent of this limit but also take it under the consideration during shards calculation.

> Let's complete the refactor before working on this ticket.

Please, definitely 😄

**Comment by bootstraponline** [comment]
https://firebase-community.slack.com/archives/C72V6UW8M/p1597979321010300?thread_ts=1597950801.008900&cid=C72V6UW8M will make super sharding unnecessary.
