### ISSUE TITLE
Automate updating gcloud sdk

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#806]
Currently the gcloud SDK is updated by manually running a script. Let's write a small Kotlin program that automates:

- GitHub Actions job that runs periodically
- Fetch the current gcloud sdk stable version
- Check if the stable version is in the repo, if not overwrite the repo with the new release
- Push the change to GitHub

https://github.com/Flank/gcloud_cli

I think we can create a bot user scoped only to the gcloud cli and use that token for the automated updates.

https://github.com/Flank/gcloud_cli/issues/1

**Comment by piotradamczyk5** [comment]
[PR](https://github.com/Flank/gcloud_cli/pull/9) created in [Flank/gcloud_cli](https://github.com/Flank/gcloud_cli/pull/9)
