### ISSUE TITLE
Fix parameterized testing

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#809]
Google has updated orchestrator to support parameterized tests. If this works, then we should update the readme with instructions for end users that they should update the androidx test dependency to run parameterized tests.

- https://github.com/android/android-test/releases/tag/androidx-test-1.3.0-beta02
- https://github.com/android/android-test/issues/215

**Comment by dbarwacz** [comment]
I find it really interesting that we've been running parametrised tests on flank recently without problems. Both in AS and on FTL using flank.

**Comment by bootstraponline** [comment]
I confirmed this is currently broken in Flank.

https://github.com/Flank/flank/pull/786
https://github.com/bootstraponline/flank_bug

**Comment by jan-gogo** [comment]
@bootstraponline Since ~3 months [flank is using manual sharding](https://github.com/Flank/flank/commit/9871d9e90043e3f03c6bbd0e7ff0a9b41239cfea#diff-512ed72c0353f95e845a3b91fb805a56R52) ([beta option](https://cloud.google.com/sdk/gcloud/reference/beta/firebase/test/android/run#--test-targets-for-shard)), so correct way to compare gcloud with flank is:
```
gcloud beta firebase test android run \
  --type instrumentation \
  --app app-single-success-debug.apk \
  --test app-single-success-debug-androidTest.apk \
  --device model=NexusLowRes,version=28,locale=en,orientation=portrait \
  --test-targets-for-shard "class com.example.test_app.InstrumentedTest#test"
```
with this arguments [gcloud gives error](https://console.firebase.google.com/project/flank-open-source/testlab/histories/bh.da0c237aaa33732/matrices/7268176501461410860) too.

**Comment by jan-gogo** [comment]
But it works for 
```
  --test-targets-for-shard "class com.example.test_app.InstrumentedTest"
```
So looks like we cannot shard tests methods from parametrized tests. I hope that is root of problem.

**Comment by dbarwacz** [comment]
I have the same problem when running parametrized tests locally in IDE.
Please correct me if I'm wrong, as I haven't check in source code, but it
seems to me that Parametrized runner can't launch specific test method - it
can only 'work' with test class being launched.

**Comment by jan-gogo** [comment]
> I have the same problem when running parametrized tests locally in IDE.
Please correct me if I'm wrong, as I haven't check in source code, but it
seems to me that Parametrized runner can't launch specific test method - it
can only 'work' with test class being launched.

That's right. Now, we know the source of problem, so it's time for implementation.

**Comment by jan-gogo** [comment]
@bootstraponline I see next problem. To fix problem with parameterized tests we need to recognize parameterized classes. Unfortunately [DexParser](https://github.com/linkedin/dex-test-parser) not returns any info about test classes.

**Comment by bootstraponline** [comment]
@jan-gogo This is awesome progress. Let's document the current status of parameterized testing in Flank and update the readme with this information.

**Comment by bootstraponline** [comment]
```yaml
gcloud:
  app:  ./app-single-success-debug.apk
  test: ./app-single-success-debug-androidTest.apk
  use-orchestrator: false

flank:
  disable-sharding: true
```



> Since ~3 months [flank is using manual sharding](https://github.com/Flank/flank/commit/9871d9e90043e3f03c6bbd0e7ff0a9b41239cfea#diff-512ed72c0353f95e845a3b91fb805a56R52) ([beta option](https://cloud.google.com/sdk/gcloud/reference/beta/firebase/test/android/run#--test-targets-for-shard)), so correct way to compare gcloud with flank is:

@jan-gogo when sharding is disabled (`disable-sharding: true`) I don't think we should be using manual sharding. We should be able to get the same result as `gcloud firebase test android run flank.yml:gcloud` when sharding is disabled in Flank.

**Comment by jan-gogo** [comment]
That's right. for `disable-sharding: true` flank gives `success` on output
```
AndroidArgs
    gcloud:
      results-bucket: test-lab-v9cn46bb990nx-kz69ymd4nm9aq
      results-dir: 2020-06-08_23-46-26.386000_brfl
      record-video: false
      timeout: 15m
      async: false
      client-details: 
      network-profile: null
      results-history-name: null
      # Android gcloud
      app: gs://test-lab-v9cn46bb990nx-kz69ymd4nm9aq/2020-06-08_16:40:58.988069_fIhy/app-single-success-debug.apk
      test: gs://test-lab-v9cn46bb990nx-kz69ymd4nm9aq/2020-06-08_16:40:58.988069_fIhy/app-single-success-debug-androidTest.apk
      additional-apks: 
      auto-google-login: false
      use-orchestrator: false
      directories-to-pull:
      other-files:
      performance-metrics: false
      num-uniform-shards: null
      test-runner-class: null
      test-targets:
      robo-directives:
      robo-script: null
      device:
        - model: NexusLowRes
          version: 28
          locale: en
          orientation: portrait
      num-flaky-test-attempts: 0

    flank:
      max-test-shards: 1
      shard-time: -1
      num-test-runs: 1
      smart-flank-gcs-path: 
      smart-flank-disable-upload: false
      files-to-download:
      test-targets-always-run:
      disable-sharding: true
      project: flank-open-source
      local-result-dir: results
      full-junit-result: true
      # Android Flank Yml
      keep-file-path: false
      additional-app-test-apks:
      run-timeout: -1
      legacy-junit-result: false
      ignore-failed-tests: false
      output-style: single

RunTests
  1 test / 1 shard

  1 matrix ids created in 0m 4s
  https://console.developers.google.com/storage/browser/test-lab-v9cn46bb990nx-kz69ymd4nm9aq/2020-06-08_23-46-26.386000_brfl

Matrices webLink
  matrix-2u7m5d516tkva https://console.firebase.google.com/project/flank-open-source/testlab/histories/bh.da0c237aaa33732/matrices/8385546085876157767/executions/bs.c7bedd3fccf3419

  2m 23s Test executions status: FINISHED:1
  2m 23s matrix-2u7m5d516tkva FINISHED

FetchArtifacts
  .
  Updating matrix file

CostReport
  Virtual devices
    $0.02 for 1m

MatrixResultsReport
  1 / 1 (100.00%)
More details are available at [https://console.firebase.google.com/project/flank-open-source/testlab/histories/bh.da0c237aaa33732/matrices/8385546085876157767]
┌─────────┬────────────────────────┬────────────────────┐
│ OUTCOME │    TEST_AXIS_VALUE     │    TEST_DETAILS    │
├─────────┼────────────────────────┼────────────────────┤
│ success │  matrix-2u7m5d516tkva  │                    │
└─────────┴────────────────────────┴────────────────────┘
  Uploading JUnitReport.xml .

Process finished with exit code 0

```

also on current `master`.

**Comment by jan-gogo** [comment]
We are tracking current progress here:
https://github.com/adamfilipow92/flank_parametrized_tests/tree/master/test_apk
