### ISSUE TITLE
Reduce release_notes.md merge conflicts

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#814]
Now that Flank is actively developed, there are a lot of merge conflicts in release_notes.md. Maybe we should have a bunch of empty lines to reduce merge conflicts?

> Conflicting files
>
> release_notes.md

**Comment by pawelpasterz** [comment]
Research (automation) needed

**Comment by piotradamczyk5** [comment]
Worth reading https://about.gitlab.com/blog/2018/07/03/solving-gitlabs-changelog-conflict-crisis/

**Comment by bootstraponline** [comment]
https://www.conventionalcommits.org/en/v1.0.0-beta.4/
https://github.com/conventional-changelog/conventional-changelog
