### ISSUE TITLE
Better validation for unsupported params in robo test

### ISSUE THREAD

**Issue by digitalbuddha** [Flank/flank#816]
Hi folks, I was running a robo test and got the following message
```
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Environment Variables not supported on Android Robo tests",
    "reason" : "badRequest"
  } ],
  "message" : "Environment Variables not supported on Android Robo tests",
  "status" : "INVALID_ARGUMENT"
}
```

It would be helpful to fail fast and save the uploading of the apks when a request is going to come back invalid. Specifically I would like validation added for invalid arguments. when. running robotests (please and thank you)

Enjoy your day

**Comment by bootstraponline** [comment]
Agreed. Thanks for reporting!
