### ISSUE TITLE
Replace buildSrc with includeBuild

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#821]
Use includeBuild instead of buildSrc

- https://proandroiddev.com/stop-using-gradle-buildsrc-use-composite-builds-instead-3c38ac7a2ab3

**Comment by pawelpasterz** [comment]
We need to decide if it is actually needed

**Comment by bootstraponline** [comment]
Do you think this is a good pattern to adopt? I think there's a bunch of other work that's higher priority for sure.

**Comment by pawelpasterz** [comment]
This is not high priority (ATM)
