### ISSUE TITLE
Fix max-test-shards: -1 to use the max allowed shards

### ISSUE THREAD

**Issue by prolificcoder** [Flank/flank#824]
**Describe the bug**
Test lab no longer accepts -1 as the max-shard number 
**To Reproduce**
1. Set    max-test-shards: -1 in flank.yml
2. Error: Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
 {
   "code" : 400,
   "errors" : [ {
     "domain" : "global",
     "message" : "num_shards must be >= 1 and <= 50.",
     "reason" : "badRequest"
   } ],
   "message" : "num_shards must be >= 1 and <= 50.",
   "status" : "INVALID_ARGUMENT"
 }

**Expected behavior**
GIve a flank error or remove the readme reference to -1

**Details (please complete the following information):**
 Invoke tests on the builds in FTL
 version: v20.05.2
 revision: 7618ebdb5a74db4b448de0b93357221de3ab10c2
 AndroidArgs
     gcloud:
       results-bucket: cloud-test-sofi-test
       results-dir: null
       record-video: true
       timeout: 15m
       async: false
       client-details: 
       network-profile: null
       results-history-name: null
       # Android gcloud
       app: /builds/sofiinc/mobile/wealth-android/app/build/outputs/apk/debug/app-debug.apk
       test: /builds/sofiinc/mobile/wealth-android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
       additional-apks: 
       auto-google-login: false
       use-orchestrator: false
       directories-to-pull:
       other-files:
       performance-metrics: false
       num-uniform-shards: null
       test-runner-class: null
       test-targets:
         - package com.sofi.mobile.tests.money
         -  notAnnotation com.sofi.mobile.Quarantine
       robo-directives:
       robo-script: null
       device:
         - model: Nexus5X
           version: 26
           locale: en
           orientation: portrait
       num-flaky-test-attempts: 1
     flank:
       max-test-shards: -1
       shard-time: -1
       num-test-runs: 1
       smart-flank-gcs-path: 
       smart-flank-disable-upload: false
       files-to-download:
       test-targets-always-run:
       disable-sharding: false
       project: sofi-test
       local-result-dir: ../app/build/test-results/money-tests/
       # Android Flank Yml
       keep-file-path: false
       additional-app-test-apks:
       run-timeout: -1
       legacy-junit-result: false
       ignore-failed-tests: false

**Additional context**
`set to -1 to use one shard per test. default: 1` from readme

**Comment by bootstraponline** [comment]
We should automatically convert -1 to the maximum shard amount as this changes over time. The current limit of 50 will be changing to 250 for virtual devices.

**Comment by prolificcoder** [comment]
@bootstraponline what is the value I should now to get this behaviour?

**Comment by bootstraponline** [comment]
50 is currently the max value, we'll fix flank to auto convert `-1` to the max value.

**Comment by prolificcoder** [comment]
gotcha. looks like the older version that I was using was able to do that somehow already and is it not hitting the google limit. 
Do you know when they are going to 250?

**Comment by bootstraponline** [comment]
Bypassing the limit will be possible once we implement super sharding: https://github.com/Flank/flank/issues/804

Flank now uses Google's underlying sharding implementation which is currently capped at 50. I think in 3-4 weeks they'll increase it to 250. A bunch of customers have commented that 50 is too low.

![image](https://user-images.githubusercontent.com/1173057/83207206-6f28a880-a107-11ea-8233-30c854ed70a9.png)
