### ISSUE TITLE
Generate doc and commit to master after each merge

### ISSUE THREAD

**Issue by piotradamczyk5** [Flank/flank#832]
**Is your feature request related to a problem? Please describe.**
Sometimes documentation is not committed and generated locally after changes. We should have always up-to-date documentation on master branch

**Describe the solution you'd like**
Add Github actions step to generate doc and commit them to master branch using some bot account

**Describe alternatives you've considered**
We could take care it locally, but PR will be bigger and sometimes we could miss update documentation

**Additional context**
@bootstraponline do we have any bot account?

**Comment by bootstraponline** [comment]
> @bootstraponline do we have any bot account?

I don't think we have a bot account currently. We could create one or maybe make a GitHub app?

I think this idea is great.

**Comment by bootstraponline** [comment]
I think we also need to make sure the doc is deterministic. We can't have different results each time.
