### ISSUE TITLE
Show available devices 

### ISSUE THREAD

**Issue by digitalbuddha** [Flank/flank#835]
Hi folks I needed to run for a particular device and couldn't figure out the device name to send. It would be nice to a device lookup that wraps the gcloud command `gcloud firebase test android models list`

Please and thank you

**Comment by piotradamczyk5** [comment]
Let's match it with gcloud output https://firebase.google.com/docs/test-lab/android/command-line#configure_your_test

**Comment by bootstraponline** [comment]
As part of showing available devices, let's also support fetching the software versions.

> You can use the same API for getting device catalog, and just specify type as PROVIDED_SOFTWARE .
