### ISSUE TITLE
[iOS] matrix path not found in json

### ISSUE THREAD

**Issue by andreschab90** [Flank/flank#844]
**Describe the bug**
I see the following warning for all shards in the flank ouput `matrix path not found in json ...`

**To Reproduce**
Steps to reproduce the behaviour:
1. Run ios test suite via flank
2. See warning in the output

**Expected behaviour**
none warning should be shown

**Details (please complete the following information):**
 - Have you tested on the latest Flank snapshot? no
 - flank version: v20.06.0
- revision: 77f18db6109b49496fe82c99a553f16414f7366a

<img width="1039" alt="Screenshot 2020-06-11 at 10 40 23" src="https://user-images.githubusercontent.com/24413222/84399611-5806b200-ac01-11ea-805e-77aeff25d1b2.png">

**Comment by adamfilipow92** [comment]
Can you attach your flank.yml? I want to be sure we going to the right side.
Thanks! @andreschab90

**Comment by andreschab90** [comment]
@piotradamczyk5 

gcloud:
  results-bucket: testlab
  record-video: true
  timeout: 30m
  async: false
  results-history-name: PROD
  num-flaky-test-attempts: 1
  test: $BITRISE_TEST_BUNDLE_ZIP_PATH
  xctestrun-file: $BITRISE_XCTESTRUN_FILE_PATH
  device:
  - model: iphonexr
    version: 13.2
    locale: en
    orientation: portrait
flank:
  max-test-shards: 15
  shard-time: -1
  num-test-runs: 1
  smart-flank-gcs-path: gs://testlab-/firebase-test-calculation/results.xml
  smart-flank-disable-upload: true
  disable-sharding: false
  project: testing
