### ISSUE TITLE
Move all checked in apks to test_artifacts

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#849]
Move the apks from 
https://github.com/Flank/flank/tree/master/test_app/apks

into the test_artifact repo.
https://github.com/Flank/test_artifacts

Consolidating all binary files in https://github.com/Flank/test_artifacts will ensure that the Flank repo size remains reasonable over time.

**Comment by pawelpasterz** [comment]
Needs second round of refinement

**Comment by bootstraponline** [comment]
https://firebase-community.slack.com/archives/C72V6UW8M/p1592959060387200

upon further discussion, we should document the pros/cons of a few different options for replacing test_artifacts.

Possible ideas include:
- Git LFS
- Git submodules
- Some other download logic?
- Other ideas...

**Comment by adamfilipow92** [comment]
Other option is [git-annex] (https://git-annex.branchable.com) [here is] (https://lwn.net/Articles/774125/) a little comparision between git annex and lfs.

**Comment by jan-gogo** [comment]
It's important to choose option which covers also versioning we don't want to always share same artifacts between different branches.

**Comment by piotradamczyk5** [comment]
@jan-gogo I think that it is solved by test artifacts ? right?

**Comment by jan-gogo** [comment]
> @jan-gogo I think that it is solved by test artifacts ? right?

Exactly

**Comment by piotradamczyk5** [comment]
> > @jan-gogo I think that it is solved by test artifacts ? right?
> 
> Exactly

So I will close the issue

**Comment by piotradamczyk5** [comment]
Fixed by introducing test_artifacts gradle task.
[More info](https://github.com/Flank/flank/blob/master/docs/test_artifacts.md)

**Comment by piotradamczyk5** [comment]
Fixed by introducing test_artifacts gradle task.
[More info](https://github.com/Flank/flank/blob/master/docs/test_artifacts.md)
