### ISSUE TITLE
Evaluate Kotlin code formatter

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#851]
Evaluate Kotlin code formatters and select one for the project.

Facebook's ktfmt looks interesting. There might be other options to research as well.
https://github.com/facebookincubator/ktfmt

**Comment by piotradamczyk5** [comment]
[KtLint](https://github.com/pinterest/ktlint) is cool and it has Intellij IDEA integration built in.

**Comment by bootstraponline** [comment]
do we use KtLint currently via detekt?

**Comment by piotradamczyk5** [comment]
They shared many rules, but if we add KtLint formatting to Intellij IDEA, all auto formating and so on will be common for all team members. 
There is also an option to validate code and autoformat code, we could use git hooks for it (pre-commit) or (pre-push)

**Comment by bootstraponline** [comment]
that sounds awesome!

Super linter also looks cool.
https://github.com/github/super-linter
https://github.blog/2020-06-18-introducing-github-super-linter-one-linter-to-rule-them-all/

**Comment by piotradamczyk5** [comment]
super-linter does not support Kotlin, but there is alternative https://github.com/marketplace/actions/kotlin-linter

**Comment by Sloox** [comment]
@bootstraponline @piotradamczyk5 
The latest version of detekt makes use of klint by default: https://detekt.github.io/detekt/formatting.html
By adding another layer of formatting such as the linting tools discussed above it will definitely cause issues.

Alot of the formatting was updated by me in the detekt update task: https://github.com/Flank/flank/pull/1000
I am personally happy with klint as it is already integrated in intellij automatically and our detekt is fully updated and makes use of it. 
Is there a need for an additional or alternative? Do we as a team feel the formatting is not up to scratch with the current implementation?

There are some tweaks that i can make to the detekt that can be more strict on the klint integration (looking at the docs above there are some more features to enable/disable) etc.

WDYT?

**Comment by piotradamczyk5** [comment]
@Sloox 
Thank you for that update.

In that case, I think that we could just make 
- run `detekt` with autocorrection with every push or
-  make team wide pre-commit rule to run before commit/push locally(I personally use it). 

WDYT?

**Comment by bootstraponline** [comment]
sounds good 😁

**Comment by piotradamczyk5** [comment]
> @piotradamczyk5 I will add some plugins to detekt so on the ./gradlew check command it will confirm the styling is inline with Klint. (by making some modifications). This will automatically stop the build from passing and i assume the team will fix before committing anyways for a clean build. I will also do another check of all the rulesets available and see if anything is applicable.
> A pre-commit rule is not a bad idea either. You mean that the code you modify is auto-formatted before commit yes?

Yes that's what I mean
