### ISSUE TITLE
Consider adding to firebaseopensource.com

### ISSUE THREAD

**Issue by rosariopfernandes** [Flank/flank#860]
This is a great project and it surely would be helpful for Firebase Developers who use Test Lab. Consider [adding](https://github.com/firebase/firebaseopensource.com/issues/new?template=new_project.md) it to [firebaseopensource.com](https://firebaseopensource.com) :)

**Comment by pawelpasterz** [comment]
https://github.com/firebase/firebaseopensource.com/issues/184
