### ISSUE TITLE
Clearly explain how to enable smart flank for Android in documentation

### ISSUE THREAD

**Issue by lcdsmao** [Flank/flank#902]
**Author the user story for this feature**

As an Android developer, I want the documentation to clearly explain how to enable smart flank for Android.

**Describe the solution you'd like**
After exploring the source code, I found the config need to fulfill two requirements:
- Set a valid value to `smart-flank-gcs-path`
- Set either the `legacy-junit-result` or `full-junit-result` to be `true`

It would be better if the document could state these two points.😀

**Comment by kozaxinan** [comment]
I am also struggling to enable smart sharding feature. According to code https://github.com/Flank/flank/blob/master/test_runner/src/main/kotlin/ftl/reports/util/ReportManager.kt#L133. Like original post suggest, `legacy-junit-result` or `full-junit-result` to be `true`
