### ISSUE TITLE
Fast fail when device orientation is misspelled

### ISSUE THREAD

**Issue by adamfilipow92** [Flank/flank#928]
**Author the user story for this feature**

As a user, I want to fast fail when I misspell orientation so I can faster fix my config and avoid unnecessary upload apks to gcloud.

**Describe the solution you'd like**
Fast fail with exit code: 18 when orientation is misspelled. 

**Additional context**
Verifying this parameter allows the user to keep some time. I checked gcloud cli and it verifying orientation before upload apks.

WDYT?
@bootstraponline @pawelpasterz @jan-gogo @piotradamczyk5

**Comment by bootstraponline** [comment]
agreed! let's add this feature
