### ISSUE TITLE
Add full-junit-result to Fladle

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#936]
https://github.com/runningcode/fladle/issues/157

**Comment by adamfilipow92** [comment]
If I fully understand.

If we want to use smart-flank we need to have enabled one of the options
1. full-junit-result
2. legacy-junit-result

WIthout one of that smart-flank not working
My proposal is
1. Fix legacy-junit-result flag [947](https://github.com/Flank/flank/issues/947)
2. Add fast fail when smart-flank enabled but any of junit command not set with clearly explain what to do.
3. Add docs about using smart-flank mentioned here [902](https://github.com/Flank/flank/issues/902)

WDYT?
@bootstraponline @jan-gogo @Pasterzp @piotradamczyk5 @Sloox

**Comment by bootstraponline** [comment]
@adamfilipow92 I think that makes sense!

Do we know why smart flank requires those junit options? I think we just need the timing info from a complete run.

**Comment by bootstraponline** [comment]
https://github.com/Flank/flank/blob/master/docs/smart_flank.md is the information we have documented about smart flank.

**Comment by adamfilipow92** [comment]
> @adamfilipow92 I think that makes sense!
> 
> Do we know why smart flank requires those junit options? I think we just need the timing info from a complete run.

In JUnitResult we remove fail nodes if any success [#798] https://github.com/Flank/flank/pull/798 and I think there can be a problem but I need to more investigate it to be 100% sure.

**Comment by bootstraponline** [comment]
> In JUnitResult we remove fail nodes if any success [#798](https://github.com/Flank/flank/pull/798) and I think there can be a problem but I need to more investigate it to be 100% sure.

I think smart flank ignores failed nodes though (as specified in the smart flank doc).

**Comment by adamfilipow92** [comment]
Hmmm, true, smart flank using only passed tests. I analyzed where is the problem. When we did not set legacy/full junit flag, flank not uploading smart-flank report. I tested https://github.com/Flank/flank/pull/935/files and this fixes the problem.

**Comment by adamfilipow92** [comment]
For now, we can run smart flank without set ```--full-junit-result``` and ```--legacy-junit-result``` but if we use FullJUnitResult in gcs path and current run don't have set flag ```--full-junit-result``` flank override full junit result by junit result it's can be little confusing. I add fast fail to verify if we use the same type of JUnit result in this pr: https://github.com/Flank/flank/pull/1056

**Comment by bootstraponline** [comment]
sounds good!

**Comment by adamfilipow92** [comment]
Closed by #1057
