### ISSUE TITLE
Improve error message on iOS when test or xctestrun-file not set

### ISSUE THREAD

**Issue by adamfilipow92** [Flank/flank#937]
**Author the user story for this feature**

As a user, I want to see a better message when I don't set a ```test``` or ```xctestrun-file``` so I can easily understand what I do wrong.

**Is your feature request related to a problem? Please describe.**

now message for iOS look like
```
IosArgs
  ...
RunTests
java.io.FileNotFoundException: /Users/.../Repos/flank/test_runner (Is a directory)
...

Process finished with exit code 1

```

on android, we have a clear message

```

One of following options must be specified [test, robo-directives, robo-script].

Process finished with exit code 2

```

**Describe the solution you'd like**
I think we can display a message like on android devices.

WDYT

@bootstraponline @jan-gogo @pawelpasterz @piotradamczyk5 @Sloox

**Comment by bootstraponline** [comment]
I like this idea!

**Comment by Sloox** [comment]
If there is a nice message on android it should be the same for IOS too. It makes perfect sense!
