### ISSUE TITLE
Update detekt to latest version 

### ISSUE THREAD

**Issue by piotradamczyk5** [Flank/flank#949]
**Author the user story for this feature**

As a Developer, I want to use `detekt` with latest available version so I can have my static analyzer up to date

**Is your feature request related to a problem? Please describe.**
Detekt releases newer versions than we used, but it has some changes in configuration. Please update `detekt` as well as configuration.

**Describe the solution you'd like**
Please update `config/detekt.yml` configuration to work with latest `detekt` version [`v.1.10.0-RC1`](https://github.com/detekt/detekt/releases/tag/v1.11.0-RC1)

**Describe alternatives you've considered**
How about setting up dependabot to do the job later on?

**Additional context**
Flank and Flank-scripts use same config, so please update both repositories.

**Comment by Sloox** [comment]
This also works for Flank & Flank-scripts
