### ISSUE TITLE
Add analytics-uuid/Bugsnag to README

### ISSUE THREAD

**Issue by inktomi** [Flank/flank#973]
As an end user, I want to understand what analytics Flank sends and how to control them so I can make good decisions for my business.

**Is your feature request related to a problem? Please describe.**
The only mention of how to disable analytics (eg, BugSnag) is in code. That's findable, but a bit bad for end users. For example, this test class shows how to disable analytics. 

https://github.com/Flank/flank/blob/acd142d8062c3ab38ec5ca85c38bb21476d8587a/test_runner/src/test/kotlin/ftl/util/FlankBugsnagInitHelperTest.kt

**Describe the solution you'd like**
It would be great if this was documented in the README so that it would be easier to understand what analytics Flank is sending. From there, I could make a better decision about leaving them enabled or turning them off. The README should also contain information about how to turn analytics off, for instance `echo "DISABLED" > ~/.gsutil/analytics-uuid`

**Comment by bootstraponline** [comment]
Agreed! Let's create a dedicated doc that details analytics in Flank and link to this from the readme.

**Comment by bootstraponline** [comment]
https://github.com/Flank/gcloud_cli/blob/137d864acd5928baf25434cf59b0225c4d1f9319/google-cloud-sdk/platform/gsutil/gslib/metrics.py#L62

I'm not sure where gcloud CLI has this document, Flank is using the same logic.

**Comment by inktomi** [comment]
I think it would be useful to have a list of what sort of analytics are collected as well as how to turn them off. Ideally we want to provide as much information as we can, but without knowing exactly what data is sent it's hard to make that case.
