### ISSUE TITLE
Paremeterized test has empty shard with test class

### ISSUE THREAD

**Issue by kozaxinan** [Flank/flank#985]
**Describe the bug**
> A clear and concise description of what the bug is.

Having one parameterized test method in a test class creates multiple shards. One for parameterized tests and one for class of the tests. Since there is no normal tests in shard with `class parameterized.TestClass`, shards finishes with no tests and results error.

**To Reproduce**
> Steps to reproduce the behavior:

1. Run a parameterized test with single test method in it,
2. Open test result on firebase test lab an see two shards. One with tests and one with no test and failed result.

**Expected behavior**
> A clear and concise description of what you expected to happen.

There shouldn't be a shard if class has no test other than parameterized tests.

**Details (please complete the following information):**
> Have you tested on the latest Flank snapshot?
>
> Post the output of ` flank --version`.

Flank 20.08.1

**Comment by kozaxinan** [comment]
This is not a real issue. https://github.com/Flank/flank/issues/984 Confused me about which test are actually needs to be in the shards. After fixing suppress issue, it is clear that parameterized test land in single shard and there is no extra shard.

**Comment by Sloox** [comment]
@kozaxinan Good to know 👍
